### ISSUE TITLE
[V3] Image Cog load bug

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1049]
```[24/10/2017 11:16] ERROR core_commands load 62: Package loading failed
Traceback (most recent call last):
  File "/root/red/lib/python3.5/site-packages/redbot/core/core_commands.py", line 60, in load
    ctx.bot.load_extension(spec)
  File "/root/red/lib/python3.5/site-packages/redbot/core/bot.py", line 125, in load_extension
    lib.setup(self)
  File "/root/red/lib/python3.5/site-packages/redbot/cogs/image/__init__.py", line 8, in setup
    loop.create_task(n.set_giphy_key())
AttributeError: 'Image' object has no attribute 'set_giphy_key'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f0ae46f7b38>```

**Comment by palmtree5** [comment]
Fixed by #1057
