### ISSUE TITLE
Trivia frequently crashing

### ISSUE THREAD

**Issue by shrx** [Cog-Creators/Red-DiscordBot#109]
Trivia bot is frequently crashing with

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/client.py", line 267, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 607, in process_commands
    yield from command.invoke(ctx)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 342, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 46, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 38, in trivia
    await t.load_questions(message.content)
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 90, in load_questions
    if self.question_list: await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 152, in new_question
    await self.new_question()
  File "/home/shrx/Red-DiscordBot/cogs/trivia.py", line 141, in new_question
    await trivia_manager.bot.say("**Question number {}!**\n\n{}".format(str(self.count), self.current_q["QUESTION"]))
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 254, in say
    result = yield from self.send_message(destination, *args, **kwargs)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/client.py", line 970, in send_message
    yield from utils._verify_successful_response(resp)
  File "/home/shrx/.local/lib/python3.5/site-packages/discord/utils.py", line 192, in _verify_successful_response
    raise HTTPException(response, message, text)
discord.errors.HTTPException: Bad Gateway (status code: 502)
```

**Comment by Twentysix26** [comment]
If you're using the default lists it's very very probable that's on discord's end. I had a user with a similar issue

**Comment by shrx** [comment]
Yeah I'm using the default lists.
How to fix it?
Is it possible to include retry mechanisms?

**Comment by Twentysix26** [comment]
Can't do much other than waiting

**Comment by shrx** [comment]
Yeah anything would help, the bot should not hang because of a Bad Gateway error.

**Comment by irdumbs** [comment]
I agree, events like trivia should account for losing connection etc

**Comment by shrx** [comment]
I use this custom send_message function for my bot, it seems to help with the connection problems. It feels like a hack though.

```
    @asyncio.coroutine
    def sendMessage(self, channel, reply):
        while True:
            try:
                yield from self.send_message(channel, reply)
            except (HTTPError, ValueError) as err:
                print(str(err.message))
                sleep(1)
                continue
            except Exception as err:
                raise err
                break
            else:
                break
        return
```

**Comment by tekulvw** [comment]
Make sure you update discord.py, recently a patch was pushed that tries to resend on 502's

**Comment by irdumbs** [comment]
only resends once. i think we should try multiple times like shrx's exmple. maybe edited

```
    async def sendMessage(self, channel, reply):
        while True:
            try:
                await self.send_message(channel, reply)
                break
            except (HTTPError, ValueError) as err:
                print(str(err.message))
                await asyncio.sleep(1)
```

haven't looked into the errors yet. You say that catches 502?
should we not have it retrying forever?

**Comment by shrx** [comment]
https://github.com/Rapptz/discord.py/blob/03862a71453c1e8c8d5fed18dc87ddd3ad04d16f/discord/client.py#L938

```
 if resp.status == 502 and retries < 5:
```

looks like it tries 5 times, sleeping an additional second for each reply. Added in commit https://github.com/Rapptz/discord.py/commit/7adf761a35adeb6339f7a800be3119484927b12f

**Comment by shrx** [comment]
I think this is sufficient to prevent failed messages for now, so I will close the issue.
