### ISSUE TITLE
[V3] ImportError due to TYPE_CHECKING on 3.5.1

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1103]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Error when running on 3.5.1 due to `typing.TYPE_CHECKING` being 3.5.2+
### Expected behavior
That error should be handled properly
### Actual behavior
```
Traceback (most recent call last):
  File "/home/pi/djbotv3/bin/redbot", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.0b2', 'console_scripts', 'redbot')()
  File "/home/pi/djbotv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 570, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/pi/djbotv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2755, in load_entry_point
    return ep.load()
  File "/home/pi/djbotv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2409, in load
    return self.resolve()
  File "/home/pi/djbotv3/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2415, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/pi/djbotv3/lib/python3.5/site-packages/redbot/__main__.py", line 7, in <module>
    from redbot.core.bot import Red, ExitCodes
  File "/home/pi/djbotv3/lib/python3.5/site-packages/redbot/core/__init__.py", line 3, in <module>
    from .config import Config
  File "/home/pi/djbotv3/lib/python3.5/site-packages/redbot/core/config.py", line 7, in <module>
    from .data_manager import cog_data_path, core_data_path
  File "/home/pi/djbotv3/lib/python3.5/site-packages/redbot/core/data_manager.py", line 3, in <module>
    from typing import TYPE_CHECKING, List
ImportError: cannot import name 'TYPE_CHECKING'
```
Putting this here on behalf of @Electromaster232

This is occurring even after #1080 which supposedly fixed TYPE_CHECKING on 3.5.1

**Comment by tekulvw** [comment]
Fixed with #1155
