### ISSUE TITLE
[V3 Core] Catch folder/file not found errors

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#1151]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
The bot fails to launch if the instance files arn't found and returns a error.

### Expected behavior
None/A proper user friendly error.

### Actual behavior
Error: 
```
(test_env) C:\develop\test_env\Scripts>redbot bot2
Traceback (most recent call last):
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\testdata\\core'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\testdata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\develop\test_env\Scripts\redbot-script.py", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.0b4', 'console_scripts', 'redbot')()
  File "c:\develop\test_env\lib\site-packages\redbot\__main__.py", line 107, in main
    log, sentry_log = init_loggers(cli_flags)
  File "c:\develop\test_env\lib\site-packages\redbot\__main__.py", line 58, in init_loggers
    logfile_path = core_data_path() / 'red.log'
  File "c:\develop\test_env\lib\site-packages\redbot\core\data_manager.py", line 112, in core_data_path
    core_path.mkdir(exist_ok=True, parents=True)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "c:\users\boxed\appdata\local\programs\python\python36\Lib\pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\'
```
### Steps to reproduce

1. Remove/move folder with data
2. Start bot
3. The above.

**Comment by Kowlin** [comment]
Update: Error only happens when the drive is not found.

**Comment by tekulvw** [comment]
To give some more info, this will happen any time that the data directory (defined during instance setup) can no longer be found.
