### ISSUE TITLE
[V3] Error in command repl

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1159]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

So I first tried to use the core repl function on V3 for the first time. I set a very basic value and got an error

### Steps to reproduce

1. `=repl`
2. `level = 1`

![screen shot 2017-12-10 at 19 42 22](https://user-images.githubusercontent.com/23153234/33808207-a5778400-dde2-11e7-99a7-861432d50eda.png)

Full error:

```Py
Exception in command 'repl'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redbot/core/dev_commands.py", line 273, in repl
    msg = self.sanitize_output(ctx, msg)
  File "/usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/redbot/core/dev_commands.py", line 64, in sanitize_output
    result = input_.replace(token, r)
AttributeError: 'NoneType' object has no attribute 'replace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by Tobotimus** [comment]
Fixed in b34a58e

Thanks for reporting this issue :)
