### ISSUE TITLE
[V3] Error on [p]names command

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#1174]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem

A. Cog update on single cog failed
B. Command `names` failed

### Expected behavior

A. Cog update should update single cog
B. Command `names` should show user's name and nickname history

### Actual behavior

A. Cog update on single cog keep giving help content
B. Command `names` gives an error
### Steps to reproduce

Case A
Do cog update on single cog

Case B
Do `[p]names <usermention>`

### Extra detail

Case A have no traceback

Case B has this traceback
```
Exception in command 'names'
Traceback (most recent call last):
  File "/home/envs/nana/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/envs/nana/lib/python3.6/site-packages/redbot/cogs/mod/mod.py", line 1131, in names
    names = [escape(name, mass_mentions=True) for name in names]
  File "/home/envs/nana/lib/python3.6/site-packages/redbot/cogs/mod/mod.py", line 1131, in <listcomp>
    names = [escape(name, mass_mentions=True) for name in names]
  File "/home/envs/nana/lib/python3.6/site-packages/redbot/core/utils/chat_formatting.py", line 284, in escape
    text = text.replace("@​everyone", "@\u200beveryone")
AttributeError: 'NoneType' object has no attribute 'replace'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/envs/nana/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/envs/nana/lib/python3.6/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/envs/nana/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'replace'
```

**Comment by palmtree5** [comment]
#1187 fixes the second issue here

**Comment by palmtree5** [comment]
#1188 should fix the second part

**Comment by Tobotimus** [comment]
The two cases you describe should be entirely separate issues. Closing this now since #1188 fixes Case B, and I'll open a new issue for Case A.
