### ISSUE TITLE
[V3 Context] Handle DMs properly during send_interactive

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1220]
(*forwarded from @palmtree5*)

### Type:

- Bug

### Brief description of the problem
When a user in DM types `more` during a case of `ctx.send_interactive` (for example, a long response to `[p]debug`), an error occurs.

### Expected behavior
When a user types `more`, the bot's message *"type `more` to continue"* should be deleted.

### Actual behavior
```py
Exception in command 'debug'
Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/dev_commands.py", line 124, in debug
    await ctx.send_interactive(self.get_pages(result), box_lang="py")
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/context.py", line 120, in send_interactive
    await self.channel.delete_messages((query, resp))
AttributeError: 'DMChannel' object has no attribute 'delete_messages'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 489, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'DMChannel' object has no attribute 'delete_messages'
```

### Steps to reproduce

1. Open a DM with the bot
2. Do `[p]debug dir(bot)`
3. Type `more` when queried

**Comment by Tobotimus** [comment]
Fixed in 80d6868
