### ISSUE TITLE
No changes but suddenly status code: 403

### ISSUE THREAD

**Issue by redned70** [Cog-Creators/Red-DiscordBot#1227]
### Type:

- [ ] Suggestion
- [x] Bug
### Brief description of the problem
using around half the commands now produce error including []yt and []stop and others but things like []sing work. Nothing was changed at all, tried reinstalling, making new bot app etc.

### Expected behavior
plays song from youtube or stop singing etc

### Actual behaviour
does nothing in Discord but produces following errors:

[31/12/2017 19:02] ERROR red on_command_error 369: Exception in command 'yt'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\ned\Desktop\Exile\GiT\Red-DiscordBot\cogs\audio.py", line 2010,
 in yt_search
    await self.bot.say("Searching...")
  File "lib\discord\ext\commands\bot.py", line 309, in _augmented_msg
    msg = yield from coro
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib\discord\client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild
_id, tts=tts, embed=embed)
  File "lib\discord\http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions
Ignoring exception in on_command_error
Traceback (most recent call last):
  File "lib\discord\client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 378, in on_command_error
    await ctx.bot.send_message(channel, inline(message))
  File "red.py", line 92, in send_message
    return await super().send_message(*args, **kwargs)
  File "lib\discord\client.py", line 1151, in send_message
    data = yield from self.http.send_message(channel_id, content, guild_id=guild
_id, tts=tts, embed=embed)
  File "lib\discord\http.py", line 196, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Missing Permissions

### Steps to reproduce

1.  It just started happening was working fine with no changes so don't know how to reproduce

**Comment by redned70** [comment]
BTW it does appear to have the correct permissions in the server and in channels

**Comment by tekulvw** [comment]
The bot does not have permissions to send messages in the channel you issued the command in.

**Comment by redned70** [comment]
looks like it integrated differently, don't know why, it is now working but im still not sure quite what it was but hey ho. thanks anyway
