### ISSUE TITLE
[V3] redbot-setup misbehaves with service accounts on linux

### ISSUE THREAD

**Issue by mikeshardmind** [Cog-Creators/Red-DiscordBot#1235]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem
It creates (or tries to anyway) a home directory for a user which isn't intended to have one (service account)
### Expected behavior
write to `/usr/local/share`
### Actual behavior
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/redbot/.config/Red-DiscordBot'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
FileNotFoundError: [Errno 2] No such file or directory: '/home/redbot/.config'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/share/redbot-env/bin/redbot-setup", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.0b5', 'console_scripts', 'redbot-setup')()
  File "/usr/local/share/redbot-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/share/redbot-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/local/share/redbot-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/local/share/redbot-env/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/share/redbot-env/lib/python3.6/site-packages/redbot/setup.py", line 15, in <module>
    config_dir.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.6/pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.6/pathlib.py", line 1230, in mkdir
    self.parent.mkdir(parents=True, exist_ok=True)
  File "/usr/lib/python3.6/pathlib.py", line 1226, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: '/home/redbot'
```
(Can't create a home directory for a service account)
### Steps to reproduce
```
sudo useradd -r -s /bin/nologin redbot
sudo python3.6 -m venv /usr/local/share/redbot-env
sudo  /usr/local/share/redbot-env/bin/pip3.6 install -U --process-dependency-links red-discordbot[voice]
sudo -H -u redbot  /usr/local/share/redbot-env/bin/redbot-setup
```

**Comment by mikeshardmind** [comment]
PR fixes it: alternative solution if preferable could be a flag for manually specifying a data directory, but the flag would need to exist (and be used) on both the setup and the normal bot use.

**Comment by mikeshardmind** [comment]
Issues caused by this (b80c327) which were not caught during testing as certain cases were not properly tested:
1. Users running as root (really...) were affected by this. 
2. Logging misbehaves if running the bot using `sudo -u `
