### ISSUE TITLE
Yarl 1.0.0 drops unquote

### ISSUE THREAD

**Issue by skeith** [Cog-Creators/Red-DiscordBot#1258]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
do redbot-setup with yarl 1.0.0 installed

### Expected behavior
redbot setup work

### Actual behavior
redbot setup failed
traceback as follow (taken from v3support)
```
Traceback (most recent call last):
  File "C:\Users\ayberkenis\AppData\Local\Programs\Python\Python35-32\Scripts\re                                    dbot-setup-script.py", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.0b6', 'console_scripts', 'redbot-setup                                    ')()
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\pkg_resources\__init__.py", line 565, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\pkg_resources\__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\pkg_resources\__init__.py", line 2291, in load
    return self.resolve()
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\pkg_resources\__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\redbot\setup.py", line 12, in <module>
    from redbot.core.cli import confirm
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\redbot\core\cli.py", line 4, in <module>
    from redbot.core.bot import Red
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\redbot\core\bot.py", line 14, in <module>
    from . import (
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\redbot\core\rpc.py", line 3, in <module>
    from aiohttp.web import Application
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\aiohttp\web.py", line 14, in <module>
    from . import (hdrs, web_exceptions, web_fileresponse, web_middlewares,
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\aiohttp\web_middlewares.py", line 5, in <module>
    from aiohttp.web_urldispatcher import SystemRoute
  File "c:\users\ayberkenis\appdata\local\programs\python\python35-32\lib\site-p                                    ackages\aiohttp\web_urldispatcher.py", line 17, in <module>
    from yarl import URL, unquote
ImportError: cannot import name 'unquote'
```

### Steps to reproduce

1. install redbot on machine with yarl 1.0.0
2. redbot setup will fail

reference : https://pypi.python.org/pypi/yarl/1.0.0 | https://github.com/aio-libs/yarl/pull/155/files

**Comment by TheWyn** [comment]
Also occurs on Arch linux.

Installed reqs: ```python python-pip git ffmpeg base-devel openssl libffi libsodium```

Installed Red V3 dev via: ```pip3 install -U --process-dependency-links git+https://github.com/Cog-Creators/Red-DiscordBot@V3/develop#egg=red-discordbot[voice]```

Log:
![alt text](https://cdn.discordapp.com/attachments/154659242253484033/402672349750493198/2.PNG "")

**Comment by Tobotimus** [comment]
I don't think this is an issue with the bot, it looks like a version mismatch with your aiohttp and yarl versions. But out of curiosity, what is your aiohttp version?

**Comment by skeith** [comment]
@Tobotimus I don't have issue with aiohttp 2.2.5 and yarl 0.16.0. 

The issue is posted after a case I handled on v3support with aiohttp 2.2.5 and yarl 1.0.0

Wyn case also on the same version, aiohttp 2.2.5 and yarl 1.0.0

**Comment by TheWyn** [comment]
@Tobotimus 

![](https://cdn.discordapp.com/attachments/387398816317440000/402675606631874560/2.PNG "")

**Comment by Tobotimus** [comment]
See aio-libs/aiohttp#2662, aiohttp<2.3.8 is incompatible with yarl>=1.0.0 (1.0.0 was only released about 24 hours ago). As a workaround you should downgrade to yarl 0.18.0 with something like `pip3 install yarl==0.18.0`. Closing as this is not an issue with the bot.

**Comment by Kowlin** [comment]
I recommend a hard lock to 0.18 for Yarl until we're 1.0 compatible

**Comment by Tobotimus** [comment]
Good point Kowlin. Gonna reopen this until #1262 is merged
