### ISSUE TITLE
OAuth Bot: Multible voice channels.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#127]
The new authentication tokens do not support multible voice servers:

``` Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 267, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 608, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 380, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/robert/docubot/cogs/audio.py", line 71, in play
    if await self.check_voice(msg.author, msg):
  File "/home/robert/docubot/cogs/audio.py", line 539, in check_voice
    elif len(v_channel.voice_members) == 1:
AttributeError: 'NoneType' object has no attribute 'voice_members'
```

**Comment by tekulvw** [comment]
still not in discordpy, there are forks floating around though

**Comment by Kowlin** [comment]
Awaiting fix from Danny.

**Comment by tekulvw** [comment]
Still waiting, will be waiting for a while
