### ISSUE TITLE
OAuth Bot: Error on name/avatar change

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#128]
The bot is unable to change names due the fact that email & password don't exist.

``` Python
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 267, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 608, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 615, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 380, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "red.py", line 218, in name
    await bot.edit_profile(settings.password, username=" ".join(name))
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 1504, in edit_profile
    'email': fields.get('email', self.email),
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 248, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class 'discord.ext.commands.bot.Bot'>' object has no attribute 'email'
```

**Comment by tekulvw** [comment]
iirc you just pass in your token as the Authorization header and don't need a password

**Comment by Kowlin** [comment]
Fixed in the latest Discord.py commit, 
https://github.com/Rapptz/discord.py/commit/29d3f5a886545067a18d6d5e7f540074b86d7959
