### ISSUE TITLE
Getting this error:

### ISSUE THREAD

**Issue by PetriVukan** [Cog-Creators/Red-DiscordBot#1292]
When I try to install Red and/or install a cog it tells me this: 

```
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 311, in run
    os.path.join(options.target_dir, item)
  File "/usr/lib/python3.5/shutil.py", line 542, in move
    raise Error("Destination path '%s' already exists" % real_dst)
shutil.Error: Destination path '/home/butler/Red-DiscordBot/lib/multidict-4.1.0.egg-info/multidict-4.1.0.egg-info' already exists
```

**Comment by tekulvw** [comment]
If you are having issues still, please join the support server.
