### ISSUE TITLE
Error on [p]cog update

### ISSUE THREAD

**Issue by bobloy** [Cog-Creators/Red-DiscordBot#1323]
### Type:

- [ ] Suggestion
- [ X] Bug

### Brief description of the problem
`[p]cog update` fails with ValueError

### Expected behavior
Cogs to update normally
### Actual behavior

```Exception in command 'cog update'
Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Program Files\Python35\Lib\site-packages\redbot\cogs\downloader\downloader.py", line 303, in _cog_update
    updated = await self._repo_manager.update_all_repos()
  File "C:\Program Files\Python35\Lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 642, in update_all_repos
    repo, (old, new) = await self.update_repo(repo_name)
ValueError: not enough values to unpack (expected 2, got 1)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\program files\python35\lib\site-packages\discord\ext\commands\bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "c:\program files\python35\lib\site-packages\discord\ext\commands\core.py", line 899, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "c:\program files\python35\lib\site-packages\discord\ext\commands\core.py", line 493, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "c:\program files\python35\lib\site-packages\discord\ext\commands\core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: not enough values to unpack (expected 2, got 1)
```

### Steps to reproduce

1.  Fresh RedBot
2. Add repo (I used https://github.com/bobloy/Fox-V3)
3. Made a change to info.json (Was using tabs and spaces in same file)
4. `[p]cog update`

**Comment by tekulvw** [comment]
Fixed with merge of #1324
