### ISSUE TITLE
[V3] Cleanup returns trace

### ISSUE THREAD

**Issue by TheWyn** [Cog-Creators/Red-DiscordBot#1332]
Using Red 3.0.0b8 cleanup returns trace:

```
Exception in command 'cleanup messages'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/redbot/cogs/cleanup/cleanup.py", line 233, in messages
    async for message in channel.history(limit=1000, before=tmp):
UnboundLocalError: local variable 'tmp' referenced before assignment

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 904, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 498, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: UnboundLocalError: local variable 'tmp' referenced before assignment
```

Command used to cause trace: `[p]cleanup messages 1`

**Comment by tekulvw** [comment]
This was fixed in #1334
