### ISSUE TITLE
[V3 Downloader] [p]findcog errors out on search

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1360]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
Use [p]findcog on a command and it will error out.

### Expected behavior
[p]findcog should return the cog name and repo

### Actual behavior
```
[27/02/2018 08:53] ERROR events on_command_error 181: Exception in command 'findcog'
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\discord\ext\commands\core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\redbot\cogs\downloader\downloader.py", line 449, in findcog
    installed, cog_installable = await self.is_installed(cog_name)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\redbot\cogs\downloader\downloader.py", line 380, in is_installed
    for installable in await self.installed_cogs():
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\redbot\cogs\downloader\downloader.py", line 76, in installed_cogs
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\redbot\cogs\downloader\downloader.py", line 76, in <genexpr>
    return tuple(Installable.from_json(v, self._repo_manager) for v in installed)
  File "C:\Program Files (x86)\Python36-32\lib\site-packages\redbot\cogs\downloader\installable.py", line 200, in from_json
    repo_name = data['repo_name']
KeyError: 'repo_name'
```

### Steps to reproduce

1. [p]findcog with any command name

**Comment by aikaterna** [comment]
Fixed with the suggestion of removing old data from pre-beta 9.
