### ISSUE TITLE
[V3 Admin] [p]announce still relies on default channel

### ISSUE THREAD

**Issue by endms3231** [Cog-Creators/Red-DiscordBot#1378]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
if i using announce command it has happening this problem.
### Expected behavior
i thought i'd see an announcement on the channel on which the bot was invited.
### Actual behavior
The error log was output with the message(The announcement has begun.).
however, the announce was not seen anywhere...
### Steps to reproduce

1. V3 redbot installed.
2. [p]load admin
3. [p]announce
4. happening

error log
```
Task exception was never retrieved
future: <Task finished coro=<Announcer.announcer() done, defined at c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py:50> exception=AttributeError("'Guild' object has no attribute 'default_channel'",)>
Traceback (most recent call last):
  File "c:\users\endms\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py", line 60, in announcer
    channel = await self._get_announce_channel(g)
  File "c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py", line 46, in _get_announce_channel
    channel = guild.default_channel
AttributeError: 'Guild' object has no attribute 'default_channel'
Task exception was never retrieved
future: <Task finished coro=<Announcer.announcer() done, defined at c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py:50> exception=AttributeError("'Guild' object has no attribute 'default_channel'",)>
Traceback (most recent call last):
  File "c:\users\endms\appdata\local\programs\python\python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py", line 60, in announcer
    channel = await self._get_announce_channel(g)
  File "c:\users\endms\appdata\local\programs\python\python35\lib\site-packages\redbot\cogs\admin\announcer.py", line 46, in _get_announce_channel
    channel = guild.default_channel
AttributeError: 'Guild' object has no attribute 'default_channel'
 ```

**Comment by Tobotimus** [comment]
Fixed in #1381.
