### ISSUE TITLE
V3 Economy cog bugs

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1400]
### Type:

- [ ] Suggestion
- [x] Bug

We noticed there were a lot of problems and bugs with the new economy cog. It would be great if we can list all of them there (just comment) so we can fix all of that.

For myself, I found the following problems

- credits name is not used in the commands (there may be a problem with saving)
- no warning when switching bank between global and per-guild (that wipe all banks) thx @aikaterna for finding it
- error when using `[p]bank reset`
```Py
Exception in command 'bank reset'
Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/cogs/economy/economy.py", line 227, in reset
    success = await bank.wipe_bank()
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/bank.py", line 285, in wipe_bank
    await _conf.clear_all_users()
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 1058, in clear_all_users
    await self._clear_scope(self.USER)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 1011, in _clear_scope
    await group.clear()
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 153, in clear
    await self.driver.clear(*self.identifiers)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/drivers/red_json.py", line 70, in clear
    del partial[identifiers[-1]]
KeyError: 'USER'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 904, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 498, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'USER'
```
- error when using `[p]bankset toggleglobal`
```Py
Exception in command 'bankset toggleglobal'
Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/cogs/bank/bank.py", line 66, in bankset_toggleglobal
    await bank.set_global(not cur_setting)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/bank.py", line 422, in set_global
    await _conf.clear_all_users()
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 1058, in clear_all_users
    await self._clear_scope(self.USER)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 1011, in _clear_scope
    await group.clear()
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/config.py", line 153, in clear
    await self.driver.clear(*self.identifiers)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/core/drivers/red_json.py", line 70, in clear
    del partial[identifiers[-1]]
KeyError: 'USER'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 904, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 498, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'USER'
```
thx @palmtree5 for finding the 2 last errors

If you have other errors or problem you found, please leave a comment

**Comment by tekulvw** [comment]
The reset and toggle global bugs should have both been fixed with #1374

**Comment by tekulvw** [comment]
What do you mean by "credits name is not used in the commands"?

All other bugs have been fixed.

**Comment by laggron42** [comment]
I noticed that it was actually due to the recent switch (I set the bank global just after changing the name, so it was removed without warning (which is also fixed in aikaterna's PR))

**Comment by tekulvw** [comment]
So are all the issues here fixed?

**Comment by laggron42** [comment]
All the known issues are fixed yeah.
