### ISSUE TITLE
Error when trying to add playlist

### ISSUE THREAD

**Issue by ItsEeb** [Cog-Creators/Red-DiscordBot#146]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 267, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "C:\Users-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 607, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 343, in invoke
    yield from injected(_ctx.args, *_ctx.kwargs)
  File "C:\Users-\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 47, in wrapped
    ret = yield from coro(_args, *_kwargs)
  File "C:\Users-\Documents\Red\Red-DiscordBot\cogs\audio.py", line 668, in addplaylist
    if links:
UnboundLocalError: local variable 'links' referenced before assignment

**Comment by Twentysix26** [comment]
It shouldn't throw that error but you're most likely using an invalid link
