### ISSUE TITLE
[V3 Image] [p]imgur search errors out

### ISSUE THREAD

**Issue by palmtree5** [Cog-Creators/Red-DiscordBot#1484]
### Type:

- [ ] Suggestion
- [x] Bug

### Brief description of the problem
`[p]imgur search` produces an error
### Expected behavior
It should give links to images
### Actual behavior
`Error in command 'imgur search'. Check your console or logs for details.`
### Steps to reproduce

1. do `[p]imgur search cats`
2. get error

Traceback:

```py
Exception in command 'imgur search'
Traceback (most recent call last):
  File "/home/palm/redv3/lib/python3.5/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/palm/redv3/lib/python3.5/site-packages/redbot/cogs/image/image.py", line 47, in imgur_search
    data = await search_get.json()
  File "/home/palm/redv3/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 730, in json
    headers=self.headers)
aiohttp.client_exceptions.ClientResponseError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html; charset=utf-8'
```

**Comment by tekulvw** [comment]
Fixed with #1485
