### ISSUE TITLE
[V2] Audio System Timeout Error

### ISSUE THREAD

**Issue by ElyFura** [Cog-Creators/Red-DiscordBot#1510]
Please be sure to read through other issues as well to make sure what you are suggesting/reporting has not already
been suggested/reported

### Type:

- [ ] Suggestion
- [X ] Bug

### Brief description of the problem
All Audio Commands wont work

### Expected behavior
Playing  Audio in the voice Channel
### Actual behavior
Joining the channel and giving an error
### Steps to reproduce

1. Type !yt or !play word  or url
2.  Wait

`[07/04/2018 20:05] ERROR audio _join_voice_channel 709:
Traceback (most recent call last):
  File "/var/www/vhosts/gamingforcure.org/bot.gamingforcure.org/Red-DiscordBot/cogs/audio.py", line 707, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[07/04/2018 20:05] ERROR red on_command_error 369: Exception in command 'play'
Traceback (most recent call last):
  File "/var/www/vhosts/gamingforcure.org/bot.gamingforcure.org/Red-DiscordBot/cogs/audio.py", line 707, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "/usr/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/var/www/vhosts/gamingforcure.org/bot.gamingforcure.org/Red-DiscordBot/cogs/audio.py", line 1513, in play
    await self._join_voice_channel(voice_channel)
  File "/var/www/vhosts/gamingforcure.org/bot.gamingforcure.org/Red-DiscordBot/cogs/audio.py", line 711, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel,"
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel, please try again in 10 minutes.
`

**Comment by viggou** [comment]
Same error here. I have had this problem for a long time.

**Comment by palmtree5** [comment]
"The voice channel may be full. Otherwise, try changing the server's region. Try a different server region or wait. This is most likely an issue on discord's end."

**Comment by ElyFura** [comment]
I Tried it with every avaiable region, also the bot is able to join the channel it just does nothing and gives the error
![screenshot_104](https://user-images.githubusercontent.com/1097125/38459699-7ac7a6fe-3aad-11e8-889a-19d140849d60.png)

**Comment by tekulvw** [comment]
This is either an issue on the discord or one with the underlying library we use to connect to discord. There's not really anything we can do about this for V2.

**Comment by Kowlin** [comment]
As @tekulvw said, we aren't really intending to fix this, especially with V3 just around the corner. Closing and marking this as won't fix.
