### ISSUE TITLE
[Lavalink V3] Not restarting rest session

### ISSUE THREAD

**Issue by TheWyn** [Cog-Creators/Red-DiscordBot#1542]
### Type:

- [ ] Suggestion
- [X] Bug

### Brief description of the problem

When discord has as a hiccup, lavalink still thinks the same session is up and tries to act normally.  Instead when attempting to play a song, Red reports back the song is running (Only after thinking it connected to the voice channel), stop commands still work as shown below.  When using the `[p]disconnect` command is issued then the play command, Red gives the `session is closed` trace.  Restarting the machine fixes the issue, restarting Red, Audio cog or Lavalink jar separately does not fix the issue.

```

Apr 17 20:23:52 arch python3.6[389]: Attempting a reconnect in 1.79s
Apr 17 20:23:52 arch python3.6[389]: Traceback (most recent call last):
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 378, in connect
Apr 17 20:23:52 arch python3.6[389]:     proto = yield from self._create_connection(req)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 687, in _create_connection
Apr 17 20:23:52 arch python3.6[389]:     _, proto = yield from self._create_direct_connection(req)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 698, in _create_direct_connection
Apr 17 20:23:52 arch python3.6[389]:     hosts = yield from self._resolve_host(req.url.raw_host, req.port)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 669, in _resolve_host
Apr 17 20:23:52 arch python3.6[389]:     self._resolver.resolve(host, port, family=self._family)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/resolver.py", line 31, in resolve
Apr 17 20:23:52 arch python3.6[389]:     host, port, type=socket.SOCK_STREAM, family=family)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
Apr 17 20:23:52 arch python3.6[389]:     result = self.fn(*self.args, **self.kwargs)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
Apr 17 20:23:52 arch python3.6[389]:     for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
Apr 17 20:23:52 arch python3.6[389]: socket.gaierror: [Errno -3] Temporary failure in name resolution
Apr 17 20:23:52 arch python3.6[389]: The above exception was the direct cause of the following exception:
Apr 17 20:23:52 arch python3.6[389]: Traceback (most recent call last):
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/client.py", line 408, in connect
Apr 17 20:23:52 arch python3.6[389]:     yield from self._connect()
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/shard.py", line 286, in _connect
Apr 17 20:23:52 arch python3.6[389]:     f.result()
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/shard.py", line 84, in poll
Apr 17 20:23:52 arch python3.6[389]:     self.ws = yield from asyncio.wait_for(coro, timeout=180.0, loop=self.loop)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/asyncio/tasks.py", line 358, in wait_for
Apr 17 20:23:52 arch python3.6[389]:     return fut.result()
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/gateway.py", line 199, in from_client
Apr 17 20:23:52 arch python3.6[389]:     gateway = yield from client.http.get_gateway()
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/http.py", line 754, in get_gateway
Apr 17 20:23:52 arch python3.6[389]:     data = yield from self.request(Route('GET', '/gateway'))
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/http.py", line 156, in request
Apr 17 20:23:52 arch python3.6[389]:     r = yield from self._session.request(method, url, **kwargs)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/helpers.py", line 97, in __iter__
Apr 17 20:23:52 arch python3.6[389]:     ret = yield from self._coro
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 231, in _request
Apr 17 20:23:52 arch python3.6[389]:     conn = yield from self._connector.connect(req)
Apr 17 20:23:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/connector.py", line 383, in connect
Apr 17 20:23:52 arch python3.6[389]:     .format(key, exc.strerror)) from exc
Apr 17 20:23:52 arch python3.6[389]: aiohttp.client_exceptions.ClientConnectorError: [Errno -3] Cannot connect to host discordapp.com:443 ssl:T>
Apr 17 21:21:59 arch python3.6[389]: [17/04/2018 21:21] ERROR events on_command_error 198: Exception in command 'play'
Apr 17 21:21:59 arch python3.6[389]: Traceback (most recent call last):
Apr 17 21:21:59 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
Apr 17 21:21:59 arch python3.6[389]:     ret = yield from coro(*args, **kwargs)
Apr 17 21:21:59 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/redbot/cogs/audio/audio.py", line 499, in play
Apr 17 21:21:59 arch python3.6[389]:     tracks = await player.get_tracks(query)
Apr 17 21:21:59 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/lavalink/rest_api.py", line 74, in get_tracks
Apr 17 21:21:59 arch python3.6[389]:     async with self._session.get(url, headers=self._headers) as resp:
Apr 17 21:21:59 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
Apr 17 21:21:59 arch python3.6[389]:     self._resp = yield from self._coro
Apr 17 21:21:59 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 168, in _request
Apr 17 21:21:59 arch python3.6[389]:     raise RuntimeError('Session is closed')
Apr 17 21:21:59 arch python3.6[389]: RuntimeError: Session is closed
Apr 17 22:12:52 arch python3.6[389]: [17/04/2018 22:12] ERROR events on_command_error 198: Exception in command 'play'
Apr 17 22:12:52 arch python3.6[389]: Traceback (most recent call last):
Apr 17 22:12:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
Apr 17 22:12:52 arch python3.6[389]:     ret = yield from coro(*args, **kwargs)
Apr 17 22:12:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/redbot/cogs/audio/audio.py", line 499, in play
Apr 17 22:12:52 arch python3.6[389]:     tracks = await player.get_tracks(query)
Apr 17 22:12:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/lavalink/rest_api.py", line 74, in get_tracks
Apr 17 22:12:52 arch python3.6[389]:     async with self._session.get(url, headers=self._headers) as resp:
Apr 17 22:12:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 603, in __aenter__
Apr 17 22:12:52 arch python3.6[389]:     self._resp = yield from self._coro
Apr 17 22:12:52 arch python3.6[389]:   File "/usr/lib/python3.6/site-packages/aiohttp/client.py", line 168, in _request
Apr 17 22:12:52 arch python3.6[389]:     raise RuntimeError('Session is closed')
Apr 17 22:12:52 arch python3.6[389]: RuntimeError: Session is closed


```
### Expected behavior

Restart the session if needed (or when discord having problems).

Screenshot, as you can see while Red reports back it's playing Rip & Tear, but Red never actually connects to a voice channel, The play command trace is posted above:  ![bug](https://user-images.githubusercontent.com/841141/38906938-607ba64c-4287-11e8-9501-a8e138c93876.PNG)

**Comment by TheWyn** [comment]
Moved to https://github.com/Cog-Creators/Red-Lavalink/issues/29
