### ISSUE TITLE
[V3 Mongo] Error when removing instance

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1573]
### Type:

- [ ] Suggestion
- [x] Bug

When removing an instance with the launcher, this error occurs
```Py
pi@raspberrypi:~ $ export PATH=.local/bin/
pi@raspberrypi:~ $ redbot-launcher
==========================
Red Discord Bot - Launcher
==========================

1. Run Red w/ autorestart in case of issues
2. Run Red
3. Update Red
4. Update Red (development version)
5. Create Instance
6. Remove Instance
7. Debug information (use this if having issues with the launcher or bot)
0. Exit
> 6
You have chosen to remove an instance. The following is a list of instances that currently exist:

Oxibot

Red

Please select one of the above by entering its name
> Red
Would you like to make a backup of the data for this instance? (y/n)n
Removing the instance...
Traceback (most recent call last):
  File ".local/bin/redbot-launcher", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.6/site-packages/redbot/launcher.py", line 358, in main
    main_menu()
  File "/home/pi/.local/lib/python3.6/site-packages/redbot/launcher.py", line 323, in main_menu
    asyncio.get_event_loop().run_until_complete(remove_instance())
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/pi/.local/lib/python3.6/site-packages/redbot/setup.py", line 379, in remove_instance
    m = Mongo("Core", **instance_data["STORAGE_DETAILS"])
NameError: name 'Mongo' is not defined
```

**Comment by palmtree5** [comment]
Fixed in #1710
