### ISSUE TITLE
[V3] Mod - Unmute still not working

### ISSUE THREAD

**Issue by Ray-MRQ** [Cog-Creators/Red-DiscordBot#1595]
# Command bugs
Did you find a bug with a command? Fill out the following:
-->unmute server

#### Command name

unmute

#### What cog is this command from?

mod

#### What were you expecting to happen?

server unmute a user

#### What actually happened?

fails to unmute,  
```py
Exception in command 'unmute server'
Traceback (most recent call last):
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/redbot/cogs/mod/mod.py", line 988, in guild_unmute
    success, message = await self.unmute_user(guild, channel, author, user)
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/redbot/cogs/mod/mod.py", line 1018, in unmute_user
    overwrites.send_messages = old_values["send_messages"]
TypeError: 'NoneType' object is not subscriptable

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/home/ramimqr/Red-V3/venv/lib/python3.6/site-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: 'NoneType' object is not subscriptable
```
![image](https://user-images.githubusercontent.com/10146271/39638254-8f37f0f6-4fbd-11e8-9634-d0b32c62cccc.png)

#### How can we reproduce this issue?

attempt an unmute server on a user

**Comment by Tobotimus** [comment]
Thanks for bringing this to our attention. It seems as though the bugfix (#1568) was accidentally reverted by an unrelated PR (#1582).
