### ISSUE TITLE
V3: __init__.py bug

### ISSUE THREAD

**Issue by Hendersonyt** [Cog-Creators/Red-DiscordBot#1675]
# Other bugs

#### What were you trying to do?

loading a custom cog

#### What were you expecting to happen?

it to load.

#### What actually happened?

error:
[17/05/2018 22:45] ERROR core_commands load 349: Package loading failed
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\redbot\core\core_commands.py", line 347, in load
    await ctx.bot.load_extension(spec)
  File "c:\program files\python36\lib\site-packages\redbot\core\bot.py", line 225, in load_extension
    lib.setup(self)
  File "C:\Users\Ian\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\fg4cog\__init__.py", line 4, in setup
    bot.add_cog(fg4cog())
TypeError: __init__() missing 1 required positional argument: 

> 'bot'

#### How can we reproduce this issue?

the part 'bot.add_cog(Mycog())' shoud be  'bot.add_cog(Mycog)'
was casuing a huge issue, I changed it to 'bot.add_cog(Mycog)' to fix the issue.

**Comment by palmtree5** [comment]
Hint:

```
TypeError: __init__() missing 1 required positional argument:
bot
```
1. This is not a Red issue
2. Your solution won't work, try `bot.add_cog(Mycog(bot))` instead of dropping the `()`

**Comment by Hendersonyt** [comment]
adds a error:
[17/05/2018 23:13] ERROR core_commands load 349: Package loading failed
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\redbot\core\core_commands.py", line 347, in load
    await ctx.bot.load_extension(spec)
  File "c:\program files\python36\lib\site-packages\redbot\core\bot.py", line 225, in load_extension
    lib.setup(self)
  File "C:\Users\Ian\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\fg4cog\__init__.py", line 4, in setup
    bot.add_Cog(fg4cog(bot))
AttributeError: 'Red' object has no attribute 'add_Cog'

**Comment by palmtree5** [comment]
`add_cog`, not `add_Cog` (yes, I typoed that, but also read the docs)
