### ISSUE TITLE
[V3 Audio] No response whilst downloading Lavalink.jar

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#1709]
When loading Audio and Lavalink.jar needs to be downloaded, the bot takes a very long time to respond, which will leave users wondering if the bot is even loading audio.

Just a simple message saying "Downloading Lavalink.jar" or making the bot type whilst downloading makes sure the user knows something is happening.

Also just a quick side-issue which should be an easy fix, this error occurs if the user does not have Java installed:
```
[24/05/2018 06:25] ERROR core_commands load 363: Package loading failed
Traceback (most recent call last):
  File "/home/tobyh/.pyenv/versions/3.6.5/envs/red/lib/python3.6/site-packages/redbot/core/core_commands.py", line 361, in load
    await ctx.bot.load_extension(spec)
  File "/home/tobyh/.pyenv/versions/3.6.5/envs/red/lib/python3.6/site-packages/redbot/core/bot.py", line 227, in load_extension
    await lib.setup(self)
  File "/home/tobyh/.pyenv/versions/3.6.5/envs/red/lib/python3.6/site-packages/redbot/cogs/audio/__init__.py", line 53, in setup
    await start_lavalink_server(bot.loop)
  File "/home/tobyh/.pyenv/versions/3.6.5/envs/red/lib/python3.6/site-packages/redbot/cogs/audio/manager.py", line 66, in start_lavalink_server
    java_available, java_version = await has_java(loop)
TypeError: 'bool' object is not iterable
```

**Comment by tekulvw** [comment]
Fixed with #1756
