### ISSUE TITLE
converting to bot account

### ISSUE THREAD

**Issue by bonesoul** [Cog-Creators/Red-DiscordBot#172]
i created new bot account as guided here; https://twentysix26.github.io/Red-Docs/red_guide_bot_accounts/#logging-in-with-a-token

deleted my old data/red/settings.json and created a new one using my bot token but now getting this error when i try running it;

```
Adding PASSWORD field to red settings.json

Loading cogs...

Traceback (most recent call last):
  File "red.py", line 537, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "red.py", line 529, in main
    yield from bot.login(settings.email)
TypeError: login() missing 1 required positional argument: 'password'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 545, in <module>
    loop.run_until_complete(bot.logout())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 508, in logout
    yield from self.close()
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 558, in close
    if self.ws.open:
AttributeError: 'NoneType' object has no attribute 'open'
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /var/www/vapistbot/cogs/streams.py:369> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_manager() running at /var/www/vapistbot/cogs/audio.py:726> wait_for=<Future pending cb=[Task._wakeup()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f5f8f563048>
```

**Comment by Twentysix26** [comment]
Update discord.py

**Comment by bonesoul** [comment]
i already use the latest commit? https://github.com/Twentysix26/Red-DiscordBot/commit/67be0157f9cd871a6d47491b03066c60c73155b4

**Comment by Twentysix26** [comment]
discord.py =/= Red

`pip3 install --upgrade git+https://github.com/Rapptz/discord.py@async`

**Comment by bonesoul** [comment]
i'have updated discord.py, but still having the same issue.

**Comment by Twentysix26** [comment]
It clearly didn't work then
`pip3 uninstall discord.py`
`pip3 install git+https://github.com/Rapptz/discord.py@async`

**Comment by bonesoul** [comment]
thanks done

**Comment by Esclick** [comment]
I have the same error

**Comment by franc-ist** [comment]
@Esclick update discord.py and Red.
