### ISSUE TITLE
[V3] Error thrown in [p]now if reacting with something other than what bot is looking for.

### ISSUE THREAD

**Issue by skipfie** [Cog-Creators/Red-DiscordBot#1727]
# Command bugs

#### Command name

[p]now

#### What cog is this command from?

audio

#### What were you expecting to happen?

nothing

#### What actually happened?

Error thrown.

`Exception in command 'now'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/audio/audio.py", line 379, in now
    react = reacts[r.emoji]
KeyError: PartialEmoji(animated=False, name='ahegao', id=400894350340390913)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: PartialEmoji(animated=False, name='ahegao', id=400894350340390913)`

#### How can we reproduce this issue?

1. Call command [p]now
2. React with emoji that it does not look for

**Comment by Tobotimus** [comment]
Resolved by #1752
