### ISSUE TITLE
[V3] Bot crashes on [p]restart

### ISSUE THREAD

**Issue by pabloleban** [Cog-Creators/Red-DiscordBot#1739]
# Command bugs

#### Command name

[p]restart

#### What cog is this command from?

Core

#### What were you expecting to happen?

Reconnect.

#### What actually happened?

It just shuts down and never reconnects.

#### How can we reproduce this issue?

[p]restart

#### Stacktrace

```
Task exception was never retrieved
future: <Task finished coro=<close() done, defined at /root/.local/lib/python3.6/site-packages/lavalink/lavalink.py:259> exception=AttributeError("'NoneType' object has no attribute 'close'",)>
Traceback (most recent call last):
  File "/root/.local/lib/python3.6/site-packages/lavalink/lavalink.py", line 266, in close
    await node.disconnect()
  File "/root/.local/lib/python3.6/site-packages/lavalink/node.py", line 387, in disconnect
    await node.disconnect()
  File "/root/.local/lib/python3.6/site-packages/lavalink/node.py", line 266, in disconnect
    await self._ws.close()
AttributeError: 'NoneType' object has no attribute 'close'
Traceback (most recent call last):
  File "/usr/local/bin/redbot", line 11, in <module>
    sys.exit(main())
  File "/root/.local/lib/python3.6/site-packages/redbot/__main__.py", line 163, in main
    red.rpc.close()
AttributeError: 'Red' object has no attribute 'rpc'

```

**Comment by mikeshardmind** [comment]
Update your bot, this was already fixed in #1726
