### ISSUE TITLE
[V3 Core] Error with set if used in DM

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#1741]
# Command bugs

#### Command name

set

#### What cog is this command from?

Core commands

#### What were you expecting to happen?

show the help list

#### What actually happened?

```Py
Exception in command 'set'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 518, in _set
    admin_role_id = await ctx.bot.db.guild(ctx.guild).admin_role()
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/config.py", line 760, in guild
    return self._get_base_group(self.GUILD, guild.id)
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 923, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

#### How can we reproduce this issue?

Try the `[p]set` command in DM

**Comment by Tobotimus** [comment]
Thanks for submitting this issue!

Fixed in #1748
