### ISSUE TITLE
Asyncio Python 3.5 Error

### ISSUE THREAD

**Issue by Kenner-G** [Cog-Creators/Red-DiscordBot#1751]
1. Run Red /w autorestart in case of issues
2. Run Red
3. Update
4. Install requirements
5. Maintenance (repair, reset...)

0. Quit
> 2
Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "lib\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "lib\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "lib\discord\voice_client.py", line 43, in <module>
    import websockets
  File "lib\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "lib\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "lib\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "lib\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
Red has been terminated. Exit code: 1
Press enter to continue.

Help! :(

**Comment by skeith** [comment]
You can also try asking on the red discord server for faster response and solving

**Comment by mikeshardmind** [comment]
This appears to be a python3.7 issue due to the highlight of `async` throwing a syntax error. If you are using python3.7, please be advised that red does not currently support python3.7 due the version of websockets we use.

**Comment by Tobotimus** [comment]
Doesn't look like an issue with the bot for me, please ask further questions in the #support channel at https://discord.gg/red
