### ISSUE TITLE
[V3 Help] Error when bot is blocked by user

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#1901]
#### Command name

[p]help with the bot being blocked and the help message being sent via DM

#### What cog is this command from?

help_formatter.py

#### What were you expecting to happen?

For the bot to say "I couldn't send the help message to you in DM. Either you blocked me or you disabled DMs in this server."

#### What actually happened?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/help_formatter.py", line 417, in help
    await destination.send(embed=embed)
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 769, in send
    data = yield from state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 212, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/help_formatter.py", line 420, in help
    await destination.send(embed=embed)
  File "/usr/local/lib/python3.6/dist-packages/discord/abc.py", line 769, in send
    data = yield from state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/usr/local/lib/python3.6/dist-packages/discord/http.py", line 212, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: FORBIDDEN (status code: 403): Cannot send messages to this user
```

#### How can we reproduce this issue?

1. Have enough cogs loaded so that the help message goes to DM
2. Block the bot
3. [p]help

**Comment by Kowlin** [comment]
Fixed with merge of #1955.
