### ISSUE TITLE
[v2 Downloader] requirements with dotted package names crash the library check

### ISSUE THREAD

**Issue by calebj** [Cog-Creators/Red-DiscordBot#1926]
#### Command name

`cog install calebj captcha`

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

Downloader should have pulled in the dependencies like normal using pip before installing the cog.

#### What actually happened?

Best guess is that since `wheezy.captcha` is a namespace package with a dot in the PyPI name, it's confusing the check. The `wheezy` module will import successfully when any subpackages are installed, but there is no package named just `wheezy` on PyPI. This doesn't happen when the package is already installed.

```
Exception in command 'cog install'
Traceback (most recent call last):
  File "/data/red/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/data/red/cogs/downloader.py", line 397, in _install
    install_cog = await self.install(repo_name, cog, notify_reqs=True)
  File "/data/red/cogs/downloader.py", line 447, in install
    requirements = [r for r in requirements
  File "/data/red/cogs/downloader.py", line 448, in <listcomp>
    if not self.is_lib_installed(r)]
  File "/data/red/cogs/downloader.py", line 530, in is_lib_installed
    return bool(find_spec(name))
  File "/usr/lib/python3.5/importlib/util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ImportError: No module named 'wheezy'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/red/.local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 846, in process_commands
    yield from command.invoke(ctx)
  File "/data/red/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 634, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/data/red/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 374, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/data/red/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 54, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ImportError: No module named 'wheezy'
```

#### How can we reproduce this issue?

1. Attempt to install Captcha from my [cog repo's develop branch](https://github.com/calebj/calebj-cogs/tree/develop/)
2. Cry. Cry a lot.

**Comment by Twentysix26** [comment]
```
>>> find_spec("wheezy.captcha")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\...\Python36-32\lib\importlib\util.py", line 88, in find_spec
    parent = __import__(parent_name, fromlist=['__path__'])
ModuleNotFoundError: No module named 'wheezy'
```
I'm getting a different type of exception. Might be worth catching both?

**Comment by calebj** [comment]
It's already caught, since `ModuleNotFoundError` is a subclass of `ImportError` [added in 3.6](https://docs.python.org/3.6/library/exceptions.html#ModuleNotFoundError).
