### ISSUE TITLE
cog repo add bug

### ISSUE THREAD

**Issue by doodthedoodthedood** [Cog-Creators/Red-DiscordBot#1962]
# Command bugs

#### Command name

cog repo add

#### What cog is this command from?

downloader

#### What were you expecting to happen?

The cog to be downloaded from the repo.

#### What actually happened?

I typed it in, and I got an error. So I checked my console, and here was the error message:
```
fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
fatal: ambiguous argument 'origin/HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
[26/07/2018 19:29] ERROR red on_command_error 369: Exception in command 'cog repo add'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\(myname)\Red-DiscordBot\cogs\downloader.py", line 97, in _repo_add
    self.update_repo(repo_name)
  File "C:\Users\(myname)\Red-DiscordBot\cogs\downloader.py", line 673, in update_repo
    raise UpdateError(name, *e.args) from None
cogs.downloader.UpdateError: ('jumper-cogs', 'Error resetting to origin/HEAD')
```

#### How can we reproduce this issue?

I entered in ?cog repo add jumper-cogs https://github.com/spAnser/Jumper-Cogs, said I agree, than got the error.

**Comment by tekulvw** [comment]
Not fixing, V2 is feature locked. Please update to V3.
