### ISSUE TITLE
[V3 Reports] Error when report interact is used in DM

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#2015]
# Command bugs

#### Command name

[p]report interact <case_no>

#### What cog is this command from?

Reports

#### What were you expecting to happen?

For this command to not be usable in DMs

#### What actually happened?

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 62, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/reports/reports.py", line 322, in response
    rec = await self.config.custom("REPORT", guild.id, ticket_number).report()
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 886, in invoke
    yield from ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/commands/commands.py", line 159, in invoke
    await super().invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 927, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 514, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 71, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

#### How can we reproduce this issue?

Use [p]report interact in a DM.

**Comment by Tobotimus** [comment]
Resolved by #2016.
