### ISSUE TITLE
Launcher Runtime Error catch misinforms user

### ISSUE THREAD

**Issue by JJW8071** [Cog-Creators/Red-DiscordBot#2020]
# Other bugs

#### What were you trying to do?

Load a custom cog.

#### What actually happened?

Redbot (or perhaps the Launcher) catches a runtime error when attempting to load a cog with improper import statements.  The runtime error statement is:
`RuntimeError: The <custom cog> cog in the <customcog.customcog> package, is not using Red's command module, and cannot be added. If this is your cog, please use from "redbot.core import commands" in place of "from discord.ext import commands". For more details on this requirement, see this page: http://red-discordbot.readthedocs.io/en/v3-develop/framework_commands.html`

This message should include "from ".  If taken literally as presented a new error posts.

`RuntimeError: The <custom cog> cog in the <customcog.customcog> package, is not using Red's command module, and cannot be added. If this is your cog, please use from "from redbot.core import commands" in place of "from discord.ext import commands". For more details on this requirement, see this page: http://red-discordbot.readthedocs.io/en/v3-develop/framework_commands.html`

#### How can we reproduce this issue?

Remove "from" from "from redbot.core import commands".  If "from" is not included then a new error posts:

`Traceback (most recent call last):
  File "C:\Users\jason\AppData\Local\Programs\Python\Python36\lib\site-packages\redbot\core\core_commands.py", line 86, in _load
    self._cleanup_and_refresh_modules(spec.name)
  File "C:\Users\jason\AppData\Local\Programs\Python\Python36\lib\site-packages\redbot\core\core_commands.py", line 118, in _cleanup_and_refresh_modules
    importlib._bootstrap._exec(lib.__spec__, lib)
  File "<frozen importlib._bootstrap>", line 618, in _exec
  File "<frozen importlib._bootstrap_external>", line 674, in exec_module
  File "<frozen importlib._bootstrap_external>", line 781, in get_code
  File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\jason\AppData\Local\Red-DiscordBot\Red-DiscordBot\cogs\CogManager\cogs\customcog\customcog.py", line 1
    redbot.core import commands
                     ^
SyntaxError: invalid syntax`

**Comment by Tobotimus** [comment]
Thanks for opening the issue, this was resolved by #2021.
