### ISSUE TITLE
Python 3.7 with Discord.py Rewrite Branch Issues

### ISSUE THREAD

**Issue by GamingFTW** [Cog-Creators/Red-DiscordBot#2030]
In an attempt to run Red Discord with Python 3.7 by using [Discord.py rewrite branch ](https://github.com/Rapptz/discord.py/tree/rewrite) we ran into some problems.

```
Starting Red...
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f77c2d27400>
Could not import cairosvg. Standard emoji conversions will be limited to 72x72 png.
Logging into Discord...
red.py:599: RuntimeWarning: coroutine 'Client.login' was never awaited
  bot=not bot.settings.self_bot)
[19/08/2018 02:33] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "/usr/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
TypeError: cannot 'yield from' a coroutine object in a non-coroutine generator
/srv/red/Hanazuki/Red-DiscordBot/cogs/owner.py:53: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self.session.close()
/srv/red/Hanazuki/Red-DiscordBot/cogs/bigmoji.py:91: RuntimeWarning: coroutine 'ClientSession.close' was never awaited
  self.session.close()
Task was destroyed but it is pending!
task: <Task pending coro=<Scheduler.queue_manager() running at /srv/red/Hanazuki/Red-DiscordBot/cogs/scheduler.py:286> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f77c007e138>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /srv/red/Hanazuki/Red-DiscordBot/cogs/streams.py:624> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f77c007e198>()]>>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f77c2d943c8>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f77c2e56438>
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7f77c2d1beb8>
Red has been terminated. Exit code: 1
Press enter to continue...
```

The newer aiohttp 3.3.2 and websockets 6.0 libraries have support issues with the current version Red Discord.
While the new libraries don't work with the default version of discord.py, discord.py rewrite aims to fix that.

I know what I'm doing is absolutely crazy.

**Comment by Tobotimus** [comment]
@GamingFTW We're aware with our compatibility with our dependencies, we actually pin discord.py to a specific commit on the rewrite branch and update periodically. This particular pinned version won't install if you've preinstalled a different revision of discord.py, unless you use the flags `--no-cache-dir --force-reinstall --process-dependency-links` when installing Red.

Python 3.7, aiohttp 3.3 and websockets 6 have been supported since the merge of #1974. Thus, they will be supported in the next beta release, due next Sunday.
