### ISSUE TITLE
Unable to add Soundcloud track list as a playlist

### ISSUE THREAD

**Issue by AsuraTakun** [Cog-Creators/Red-DiscordBot#2055]
# Command bugs

#### Command name

/playlist add

#### What cog is this command from?

Core?

#### What were you expecting to happen?

Creates a new playlist that plays the tracks here: [RunescapeSoundtrack](https://soundcloud.com/runescapesoundtrack)

#### What actually happened?

```
[25/08/2018 22:05] ERROR red on_command_error 369: Exception in command 'playlist add'
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "E:\Roleplaying\Red-DiscordBot\cogs\audio.py", line 1619, in playlist_add
    songlist = await self._parse_playlist(url)
  File "E:\Roleplaying\Red-DiscordBot\cogs\audio.py", line 815, in _parse_playlist
    return await self._parse_sc_playlist(url)
  File "E:\Roleplaying\Red-DiscordBot\cogs\audio.py", line 838, in _parse_sc_playlist
    playlist.append(entry.url)
AttributeError: 'dict' object has no attribute 'url'
```

#### How can we reproduce this issue?

Try to add the aforementioned soundcloud tracks as a playlist. Note: This particular user has not created a playlist of the tracks, it is just the individual tracks in a list.

**Comment by tekulvw** [comment]
Not fixing, V2 is feature locked. Please update to V3.
