### ISSUE TITLE
Got error on startting red

### ISSUE THREAD

**Issue by gsans101** [Cog-Creators/Red-DiscordBot#2082]
When i want to start red it gives me this error:

Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "lib\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "lib\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "lib\discord\voice_client.py", line 43, in <module>
    import websockets
  File "lib\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "lib\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "lib\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "lib\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^
SyntaxError: invalid syntax
Red has been terminated. Exit code: 1

**Comment by aikaterna** [comment]
Use Python 3.5.4 instead of 3.7. Feel free to join us in the Red Discord server for any other support questions.

**Comment by gsans101** [comment]
Thanks!
