### ISSUE TITLE
(V3) Errors after updating

### ISSUE THREAD

**Issue by evacfk** [Cog-Creators/Red-DiscordBot#2089]
# Other bugs

#### What were you trying to do?

Update red to latest build

#### What were you expecting to happen?

Start Red after updating

#### What actually happened?

This error on any kind of command (redbot-setup, redbot, redbot-launcher).
`Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 666, in _build_master
    ws.require(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 984, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (websockets 6.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('websockets<4.0,>=3.0'), {'discord.py'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/redbot-setup", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3147, in <module>
    @_call_aside
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3131, in _call_aside
    f(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 3160, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 668, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 681, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/local/lib/python3.6/dist-packages/pkg_resources/__init__.py", line 875, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (websockets 6.0 (/usr/local/lib/python3.6/dist-packages), Requirement.parse('websockets<4.0,>=3.0'), {'discord.py'})`

#### How can we reproduce this issue?

I'm not sure, I tried updating to latest dev build originally, and that caused this issue.

**Comment by Tobotimus** [comment]
Please try reinstalling with these commands:

    pip3 uninstall Red-Trivia
    pip3 install -U --process-dependency-links --force-reinstall --no-cache-dir --user Red-DiscordBot[voice]

Don't worry if the first command fails, simply move onto the next one. If you still have issues please let us know.

**Comment by evacfk** [comment]
This resolved the issue, thank you.

Final question, my systemd now provides errors when trying to start the bot.

` [Unit]
Description=%I redbot
After=multi-user.target

[Service]
ExecStart=/home/evacbots/.local/bin/redbot %I --no-prompt
User=evacbots
Group=evacbots
Type=idle
Restart=always
RestartSec=15
RestartPreventExitStatus=0

[Install]
WantedBy=multi-user.target
 `

This is the script i'm using.

The execstart directory listed there does not exist for me.

` evacbots@evacbot:~/.local/bin$ ls
chardetect  d  distro  easy_install  easy_install-3.6  futurize  markdown_py  pasteurize  pygmentize  virtualenv `

**Comment by palmtree5** [comment]
```
/home/evacbots/.local/bin/redbot
```
should be
```
/usr/local/bin/redbot
```
based on the traceback you posted before in which `redbot-setup` was in `/usr/local/bin`

**Comment by evacfk** [comment]
Thank you, issue is resolved.

I did not realize my redbot  had changed directories, original systemd i posted has always worked until now.

Thanks again.
