### ISSUE TITLE
[V3] Incompatible with 3.6.0/3.6.1

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2092]
# Other bugs

As a note, this is an issue someone in v3-support had but I've confirmed it on a test install as well.

#### What were you trying to do?

Run Red on 3.6.0 / 3.6.1. Currently setup.py allows installations on these two versions.

#### What were you expecting to happen?

Red begins and runs normally.

#### What actually happened?

Config attempts an import from `typing` (`AsyncContextManager`) that was only [added in Python 3.6.2](https://docs.python.org/3/whatsnew/changelog.html#id136) (and 3.5.4, apparently).
```py
Traceback (most recent call last):
  File "C:\Users\\Desktop\python\testenvs\3.6.1\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\\Desktop\python\testenvs\3.6.1\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\\AppData\Roaming\Python\Python36\site-packages\redbot\__main__.py", line 7, in <module>
    from redbot.core.bot import Red, ExitCodes
  File "C:\Users\\AppData\Roaming\Python\Python36\site-packages\redbot\core\__init__.py", line 1, in <module>
    from .config import Config
  File "C:\Users\\AppData\Roaming\Python\Python36\site-packages\redbot\core\config.py", line 4, in <module>
    from typing import Any, Union, Tuple, Dict, Awaitable, AsyncContextManager, TypeVar, TYPE_CHECKING
ImportError: cannot import name 'AsyncContextManager'
```

#### How can we reproduce this issue?

1. Install Python 3.6.0 or 3.6.1
2. Install Red
3. Run Red

**Comment by Tobotimus** [comment]
Resolved by #2093 in the meaning that 3.6.0 and 3.6.1 are no longer supported.
