### ISSUE TITLE
[V3 Core] Backup TypeError

### ISSUE THREAD

**Issue by Zephyrkul** [Cog-Creators/Red-DiscordBot#2094]
# Command bugs

#### Command name

backup

#### What cog is this command from?

Core

#### What were you expecting to happen?

Dunno, I was testing to see what backup does, but an error is likely not expected behavior.

#### What actually happened?

For whatever reason I get two of the same error for every run of `[p]backup`. Only one bot is running.
```py
[03/09/2018 20:59] ERROR events on_command_error 205: Exception in command 'backup'
Traceback (most recent call last):
  File "/home/zephyrkul/.pyenv/versions/red/lib/python3.7/site-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/zephyrkul/.pyenv/versions/red/lib/python3.7/site-packages/redbot/core/core_commands.py", line 1087, in backup
    m = Mongo("Core", **basic_config["STORAGE_DETAILS"])
TypeError: __init__() missing 1 required positional argument: 'identifier'
[03/09/2018 20:59] ERROR events on_command_error 210: Exception in command 'backup'
Traceback (most recent call last):
  File "/home/zephyrkul/.pyenv/versions/red/lib/python3.7/site-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/zephyrkul/.pyenv/versions/red/lib/python3.7/site-packages/redbot/core/core_commands.py", line 1087, in backup
    m = Mongo("Core", **basic_config["STORAGE_DETAILS"])
TypeError: __init__() missing 1 required positional argument: 'identifier'
```

#### How can we reproduce this issue?

Run `[p]backup` on a mongodb backend.

**Comment by Tobotimus** [comment]
Resolved by #2210.
