### ISSUE TITLE
[CustomCom] Old custom commands causing issues with new changes

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#2113]
Calling an old custom command created prior to #2051 results in the following traceback:
```py
[09/09/2018 14:13] ERROR events on_error 182: Exception in message
Traceback (most recent call last):
  File "/home/tobyh/Red-DiscordBot/.venv/lib/python3.7/site-packages/discord/client.py", line 221, in _run_event
    await coro(*args, **kwargs)
  File "/home/tobyh/Red-DiscordBot/.venv/lib/python3.7/site-packages/redbot/cogs/customcom/customcom.py", line 325, in on_message
    await self.call_cc_command(ctx, raw_response, message)
  File "/home/tobyh/Red-DiscordBot/.venv/lib/python3.7/site-packages/redbot/cogs/customcom/customcom.py", line 334, in call_cc_command
    await self.cc_command(*ctx.args, **ctx.kwargs, raw_response=raw_response)
  File "/home/tobyh/Red-DiscordBot/.venv/lib/python3.7/site-packages/redbot/cogs/customcom/customcom.py", line 352, in cc_command
    low = min(int(result[1]) for result in results)
ValueError: min() arg is an empty sequence
```

**Comment by Tobotimus** [comment]
Resolved by #2114.
