### ISSUE TITLE
aiohttp Dependency Issue

### ISSUE THREAD

**Issue by ACBobby** [Cog-Creators/Red-DiscordBot#2189]
#### What were you trying to do?

Launch Red with either redbot [Instance] or redbot-launcher.

#### What were you expecting to happen?

The bot to run, or in the case of the launcher, present me with the menu.

#### What actually happened?

Python error for requirements. Seems to requite aiohttp <3.4.0 but >= 3.3.0. The install command pulls 3.4.4 from the repository.

#### How can we reproduce this issue?

Ubuntu 18.04.1 -- pull the bot (without audio; non-dev branch) using the pip3 command.

Some addition info. I had actually uninstalled aiohttp with pip3 uninstall and then ran the install command again in order to make sure the installer was pulling the version that Red was wanting, and it resulted in the same issue.

```
(venv) bdawson@herbert:~$ pip3 install -U --process-dependency-links --no-cache-dir Red-DiscordBot
Requirement already up-to-date: Red-DiscordBot in ./venv/lib/python3.6/site-packages
Requirement already up-to-date: aiohttp-json-rpc==0.11.2 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Collecting aiohttp==3.4.4 (from Red-DiscordBot)
  Downloading https://files.pythonhosted.org/packages/52/f9/c22977fc95346911d8fe507f90c3c4e4f445fdf339b750be6f03f090498d/aiohttp-3.4.4-cp36-cp36m-manylinux1_x86_64.whl (1.1MB)
    100% |████████████████████████████████| 1.1MB 16.3MB/s
Requirement already up-to-date: appdirs==1.4.3 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: async-timeout==3.0.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: attrs==18.2.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: chardet==3.0.4 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: colorama==0.3.9 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: discord.py>=1.0.0a0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: fuzzywuzzy==0.17.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: idna-ssl==1.1.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: idna==2.7 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: multidict==4.4.2 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: python-levenshtein==0.12.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: pyyaml==3.13 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: raven==6.9.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: raven-aiohttp==0.7.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: schema==0.6.8 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: websockets==6.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: yarl==1.2.6 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: distro==1.3.0 in ./venv/lib/python3.6/site-packages (from Red-DiscordBot)
Requirement already up-to-date: setuptools in ./venv/lib/python3.6/site-packages (from python-levenshtein==0.12.0->Red-DiscordBot)
Installing collected packages: aiohttp
Successfully installed aiohttp-3.4.4
(venv) bdawson@herbert:~$ redbot-launcher
Traceback (most recent call last):
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 578, in _build_master
    ws.require(__requires__)
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 895, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aiohttp 3.4.4 (/home/bdawson/venv/lib/python3.6/site-packages), Requirement.parse('aiohttp<3.4.0,>=3.3.0'), {'discord.py'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/bdawson/venv/bin/redbot-launcher", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3112, in <module>
    @_call_aside
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3096, in _call_aside
    f(*args, **kwargs)
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 3125, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 580, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 593, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/bdawson/venv/lib/python3.6/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (aiohttp 3.4.4 (/home/bdawson/venv/lib/python3.6/site-packages), Requirement.parse('aiohttp<3.4.0,>=3.3.0'), {'discord.py'})
(venv) bdawson@herbert:~$
```

**Comment by Tobotimus** [comment]
Your discord.py version is likely out of date. Unfortunately due to a limitation with pip it won't upgrade discord.py unless you supply the `--force-reinstall` flag to the pip install command, so try this:
```
pip install -U --process-dependency-links --force-reinstall --no-cache-dir Red-Discordbot
```
Let me know if this fixes your issue :smiley:

**Comment by ACBobby** [comment]
Looks like that fixed it. Much appreciated!
