### ISSUE TITLE
[V3 Audio] [p]playlist list Traceback

### ISSUE THREAD

**Issue by Clasko** [Cog-Creators/Red-DiscordBot#2190]
# Command bugs

#### Command name

[p]playlist list

#### What cog is this command from?

audio

#### What were you expecting to happen?

A list of the saved playlist

#### What actually happened?

I get a Traceback:
```
[06/10/2018 13:59] ERROR events on_command_error 208: Exception in command 'playlist list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 1100, in _playlist_list
    _("Author: {name}").format(self.bot.get_user(author)),
KeyError: 'name'
[06/10/2018 13:59] ERROR events on_command_error 213: Exception in command 'playlist list'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 1100, in _playlist_list
    _("Author: {name}").format(self.bot.get_user(author)),
KeyError: 'name'
```

#### How can we reproduce this issue?
Update Red to 3.0.0rc1.post1 and try to list saved playlists

**Comment by Tobotimus** [comment]
Resolved by #2191.
