### ISSUE TITLE
[V3] Info command bug 

### ISSUE THREAD

**Issue by causefx** [Cog-Creators/Red-DiscordBot#2221]
# Command bugs

#### Command name

info

#### What cog is this command from?

Main

#### What were you expecting to happen?

info version 

#### What actually happened?

```
Exception in command 'info'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/core/core_commands.py", line 276, in info
    outdated = StrictVersion(data["info"]["version"]) > StrictVersion(__version__)
  File "/usr/lib/python3.6/distutils/version.py", line 40, in __init__
    self.parse(vstring)
  File "/usr/lib/python3.6/distutils/version.py", line 137, in parse
    raise ValueError("invalid version number '%s'" % vstring)
ValueError: invalid version number '3.0.0rc1.post1'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/bot.py", line 898, in invoke
    await ctx.command.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 614, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: invalid version number '3.0.0rc1.post1'
```

#### How can we reproduce this issue?

run info

**Comment by yamikaitou** [comment]
Update Red to the latest version using PIP

**Comment by causefx** [comment]
That worked!  Thank you and sorry!
