### ISSUE TITLE
[Cleanup] No member converter on "Cleanup user"

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2224]
# Command bugs
#### Command name
``cleanup user <user> <amount>``

#### What cog is this command from?
Cleanup

#### What were you expecting to happen?
Cleaning up the amount of user.

#### What actually happened?
See Traceback:
```
[11/10/2018 11:04] ERROR events on_command_error 208: Exception in command 'cleanup user'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/cleanup/cleanup.py", line 172, in user
    member = await commands.converter.MemberConverter().convert(ctx, user)
AttributeError: module 'redbot.core.commands.converter' has no attribute 'MemberConverter'
[11/10/2018 11:04] ERROR events on_command_error 213: Exception in command 'cleanup user'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/discord/ext/commands/core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/redbot/cogs/cleanup/cleanup.py", line 172, in user
    member = await commands.converter.MemberConverter().convert(ctx, user)
AttributeError: module 'redbot.core.commands.converter' has no attribute 'MemberConverter'
```
#### How can we reproduce this issue?
``cleanup user <user> <amount>``

**Comment by Kowlin** [comment]
Fixed in #2225
