### ISSUE TITLE
[Streams] discord.NotFound error on load

### ISSUE THREAD

**Issue by Tobotimus** [Cog-Creators/Red-DiscordBot#2227]
This was reported as an error received by a user when trying to load streams:
```py
Exception during loading of cog
Traceback (most recent call last):
  File "/home/jjay/rewrite/lib/python3.6/site-packages/redbot/core/core_commands.py", line 100, in _load
    await bot.load_extension(spec)
  File "/home/jjay/rewrite/lib/python3.6/site-packages/redbot/core/bot.py", line 228, in load_extension
    await lib.setup(self)
  File "/home/jjay/rewrite/lib/python3.6/site-packages/redbot/cogs/streams/__init__.py", line 6, in setup
    await cog.initialize()
  File "/home/jjay/rewrite/lib/python3.6/site-packages/redbot/cogs/streams/streams.py", line 74, in initialize
    self.streams = await self.load_streams()
  File "/home/jjay/rewrite/lib/python3.6/site-packages/redbot/cogs/streams/streams.py", line 629, in load_streams
    msg = await chn.get_message(raw_msg["message"])
  File "/home/jjay/rewrite/lib/python3.6/site-packages/discord/abc.py", line 844, in get_message
    data = await self._state.http.get_message(channel.id, id)
  File "/home/jjay/rewrite/lib/python3.6/site-packages/discord/http.py", line 211, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message
```

**Comment by Tobotimus** [comment]
Resolved by #2228.
