### ISSUE TITLE
[V3 General] urban command throws an error if the message is deleted before menu timeout

### ISSUE THREAD

**Issue by MeatyChunks** [Cog-Creators/Red-DiscordBot#2259]
# Command bugs

#### Command name

urban

#### What cog is this command from?

general

#### What were you expecting to happen?

The bot should silently pass over the error I think.

#### What actually happened?

The bot finds the dictionary result, if the reply is deleted, an error is thrown when the menu timer expires after 30 seconds.

#### How can we reproduce this issue?

!urban test
!cleanup self 2
wait the 30 seconds and an error is seen in chat with the following traceback:
```python
ERROR events on_command_error 208: Exception in command 'urban'
Traceback (most recent call last):
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\redbot\core\utils\menus.py", line 85, in menu
    timeout=timeout,
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\redbot\cogs\general\general.py", line 301, in urban
    timeout=30,
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\redbot\core\utils\menus.py", line 89, in menu
    await message.clear_reactions()
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\discord\message.py", line 748, in clear_reactions
    await self._state.http.clear_reactions(self.id, self.channel.id)
  File "c:\users\Ferret\appdata\local\programs\python\python36\lib\site-packages\discord\http.py", line 211, in request
    raise NotFound(r, data)
discord.errors.NotFound: NOT FOUND (status code: 404): Unknown Message
```

**Comment by Tobotimus** [comment]
Resolved by #2344.
