### ISSUE TITLE
Audio playback issue

### ISSUE THREAD

**Issue by theleaplock** [Cog-Creators/Red-DiscordBot#228]
Hello I am experiencing this error:

Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Leap\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 244, in _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "red.py", line 68, in on_message
    await bot.process_commands(message)
  File "C:\Users\Leap\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  File "C:\Users\Leap\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 384, in invoke
    yield from injected(_ctx.args, *_ctx.kwargs)
  File "C:\Users\Leap\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 47, in wrapped
    ret = yield from coro(_args, *_kwargs)
  File "C:\Users\Leap\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 75, in play
    if await self.check_voice(msg.author, msg):
  File "C:\Users\Leap\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 689, in check_voice
    if self.bot.is_voice_connected():
TypeError: is_voice_connected() missing 1 required positional argument: 'server'

I am not sure how to fix it. I tried updating red and updating/reinstalling discord.py but I still have the same issue. Thank you very much for the help.

**Comment by tekulvw** [comment]
You updated a bit too much. The most recent version of discord.py breaks Red's audio cog.

Use this command to downgrade back to a stable version:
`pip3 install --upgrade git+https://github.com/Rapptz/discord.py@5fa715c35033c4fd5438649a03f4d2835e7a7f06`

**Comment by theleaplock** [comment]
Ahaha! Updating too much, that's a first for me. Thanks for the solution tekulvw that fixed my problems!
