### ISSUE TITLE
ERROR red <module> 634: Fatal exception, attempting graceful logout

### ISSUE THREAD

**Issue by vinbarney** [Cog-Creators/Red-DiscordBot#2327]
I have been having an Issue with RED BOT for the past 1-2 weeks(was working perfectly for nearly 2 years) the bot will stop playing music and restarts with this

(ERROR red <module> 634: Fatal exception, attempting graceful logout)
It will happen every couple of minutes (sometimes it will stay on for an hour sometimes for 2 mins)

I tried reinstalling Python 3.5 (With updated pip) +Git + new instance of the bot, Installed the requirements and ffmpeg (Did it a couple of times actually) and still the same issue tried opening a cmd and make it ping google every second for 1 hour and I can't find any disconnections within that hour although the bot logged out and auto restarted at least 5 times.

I didn't change anything on my computer (Hardware + software) no windows update no app updates other than games and discord so nothing major changed for this behaviour to start.

Sorry for the bad block of text

Full error log:

[11/12/2018 23:30] ERROR red <module> 634: Fatal exception, attempting graceful logout Traceback (most recent call last): File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\selector_events.py", line 723, in _read_ready data = self._sock.recv(self.max_size) ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host

The above exception was the direct cause of the following exception:

Traceback (most recent call last): File "lib\aiohttp\client.py", line 202, in request yield from resp.start(conn, read_until_eof) File "lib\aiohttp\client_reqrep.py", line 640, in start message = yield from httpstream.read() File "lib\aiohttp\streams.py", line 641, in read result = yield from super().read() File "lib\aiohttp\streams.py", line 476, in read yield from self._waiter File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 381, in __iter_ yield self # This tells Task to wait for completion. File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 310, in _wakeup future.result() File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 294, in result raise self._exception aiohttp.errors.ServerDisconnectedError

The above exception was the direct cause of the following exception:

Traceback (most recent call last): File "red.py", line 614, in <module> loop.rununtil_complete(main(bot)) File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\base_events.py", line 467, in run_until_complete return future.result() File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 294, in result raise self._exception File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 242, in _step result = coro.throw(exc) File "red.py", line 603, in main yield from bot.connect() File "lib\discord\client.py", line 451, in connect self.ws = yield from DiscordWebSocket.from_client(self, resume=True) File "lib\discord\gateway.py", line 198, in from_client gateway = yield from client.http.get_gateway() File "lib\discord\http.py", line 633, in get_gateway data = yield from self.request(Route('GET', '/gateway')) File "lib\discord\http.py", line 137, in request r = yield from self.session.request(method, url, **kwargs) File "lib\aiohttp\client.py", line 555, in __iter_ resp = yield from self.coro File "lib\aiohttp\client.py", line 209, in _request raise aiohttp.ClientResponseError() from exc aiohttp.errors.ClientResponseError Task was destroyed but it is pending! task: <Task pending coro=<Audio.queue_scheduler() running at D:\MusicBot\cogs\audio.py:2419> wait_for=<Future pending cb=[Task._wakeup()]>> Task was destroyed but it is pending! task: <Task pending coro=<Audio.disconnect_timer() running at D:\MusicBot\cogs\audio.py:2213> wait_for=<Future pending cb=[Task._wakeup()]>> Task exception was never retrieved future: <Task finished coro=<WebSocketCommonProtocol.run() done, defined at lib\websockets\protocol.py:428> exception=ConnectionResetError(10054, 'An existing connection was forcibly closed by the remote host', None, 10054, None)> Traceback (most recent call last): File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 242, in _step result = coro.throw(exc) File "lib\websockets\protocol.py", line 434, in run msg = yield from self.read_message() File "lib\websockets\protocol.py", line 456, in read_message frame = yield from self.read_data_frame(max_size=self.max_size) File "lib\websockets\protocol.py", line 511, in read_data_frame frame = yield from self.read_frame(max_size) File "lib\websockets\protocol.py", line 546, in read_frame self.reader.readexactly, is_masked, max_size=max_size) File "lib\websockets\framing.py", line 86, in read_frame data = yield from reader(2) File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\streams.py", line 668, in readexactly yield from self._wait_for_data('readexactly') File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\streams.py", line 458, in _wait_for_data yield from self._waiter File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 381, in __iter_ yield self # This tells Task to wait for completion. File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 310, in _wakeup future.result() File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 294, in result raise self._exception File "C:\Users\awsan\AppData\Local\Programs\Python\Python35\lib\asyncio\selector_events.py", line 723, in _read_ready data = self._sock.recv(self.max_size) ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host Task was destroyed but it is pending! task: <Task pending coro=<Streams.stream_checker() running at D:\MusicBot\cogs\streams.py:624> wait_for=<Future pending cb=[Task._wakeup()]>> Task was destroyed but it is pending! task: <Task pending coro=<Audio.cache_manager() done, defined at D:\MusicBot\cogs\audio.py:2155> wait_for=<Future pending cb=[Task._wakeup()]>>

**Comment by Kowlin** [comment]
This seems to co-incite with the timing of the Discord downtime, and the error logs reflects that. So simply said, Discord was having issues, this was seen across all bots and users on Discord. So this is outside of our scope.
