### ISSUE TITLE
[V3] redbot-setup errors when importing data from MongoDB to JSON

### ISSUE THREAD

**Issue by yamikaitou** [Cog-Creators/Red-DiscordBot#2372]
# Other bugs

#### What were you trying to do?

Edit an existing instance using `redbot-setup --edit`, switch from MongoDB to JSON and import the data

#### What were you expecting to happen?

For it to work

#### What actually happened?

Produced an error
```
Would you like to import your data? (y/n) y
Traceback (most recent call last):
  File "/home/red/.pyenv/versions/3.7.1/bin/redbot-setup", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.0rc3.post1', 'console_scripts', 'redbot-setup')()
  File "/home/red/.pyenv/versions/3.7.1/lib/python3.7/site-packages/redbot/setup.py", line 378, in main
    loop.run_until_complete(edit_instance())
  File "/home/red/.pyenv/versions/3.7.1/lib/python3.7/asyncio/base_events.py", line 573, in run_until_complete
    return future.result()
  File "/home/red/.pyenv/versions/3.7.1/lib/python3.7/site-packages/redbot/setup.py", line 278, in edit_instance
    await mongo_to_json(current_data_dir, storage_details)
  File "/home/red/.pyenv/versions/3.7.1/lib/python3.7/site-packages/redbot/setup.py", line 201, in mongo_to_json
    collection_names = await db.collection_names(include_system_collections=False)
  File "/home/red/.pyenv/versions/3.7.1/lib/python3.7/site-packages/motor/core.py", line 554, in __call__
    self.delegate.name)
TypeError: MotorCollection object is not callable. If you meant to call the 'collection_names' method on a MotorCollection object it is failing because no such method exists. 
```

#### How can we reproduce this issue?

Have an existing instance configured to use MongoDB. Edit the instance, change the storage backend to JSON, import the data

**Comment by Tobotimus** [comment]
Resolved by #2373.
