### ISSUE TITLE
[v3 Audio] Lavalink SSLProtocolException: Connection reset

### ISSUE THREAD

**Issue by EelcoLos** [Cog-Creators/Red-DiscordBot#2434]
#### Command name

[p]play any youtube video

#### What cog is this command from?

Audio

#### What were you expecting to happen?

To fully play the track provided

#### What actually happened?

Near the end of the track (around the 75-90%-ish mark) lavalink errors to a SSLProtocolException
![afbeelding](https://user-images.githubusercontent.com/5102501/52471191-8fd69300-2b90-11e9-8259-7e7752338dd6.png)

```
[19:04:48] [ ERROR] [LocalAudioTrackExecutor] Error in playback of GYk14hnua8k
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:269)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:38)
	at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:27)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:75)
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:67)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:90)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:348)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.RuntimeException: javax.net.ssl.SSLProtocolException: Connection reset
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:309)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.lambda$process$0(MatroskaAudioTrack.java:39)
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:257)
	... 9 common frames omitted
Caused by: javax.net.ssl.SSLProtocolException: Connection reset
	at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:126)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:321)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:264)
	at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:259)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:137)
	at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1155)
	at java.base/sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1125)
	at java.base/sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:823)
	at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
	at org.apache.http.impl.io.SessionInputBufferImpl.read(SessionInputBufferImpl.java:198)
	at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:176)
	at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:135)
	at java.base/java.io.BufferedInputStream.fill(BufferedInputStream.java:252)
	at java.base/java.io.BufferedInputStream.read1(BufferedInputStream.java:292)
	at java.base/java.io.BufferedInputStream.read(BufferedInputStream.java:351)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:172)
	at com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:185)
	at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
	at com.sedmelluq.discord.lavaplayer.container.matroska.format.MutableMatroskaBlock.getNextFrameBuffer(MutableMatroskaBlock.java:54)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.processFrameInBlock(MatroskaStreamingFile.java:372)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseClusterSimpleBlock(MatroskaStreamingFile.java:336)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.parseNextCluster(MatroskaStreamingFile.java:321)
	at com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.provideFrames(MatroskaStreamingFile.java:297)
	... 11 common frames omitted
Caused by: java.net.SocketException: Connection reset
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:186)
	at java.base/java.net.SocketInputStream.read(SocketInputStream.java:140)
	at java.base/sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:448)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decodeInputRecord(SSLSocketInputRecord.java:237)
	at java.base/sun.security.ssl.SSLSocketInputRecord.decode(SSLSocketInputRecord.java:190)
	at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:108)
	... 29 common frames omitted
```

#### How can we reproduce this issue?

1. run Red docker wise(v3 rc2 or higher, I'm using https://hub.docker.com/r/supersandro2000/reddiscord as image, which pulls from de develop tree, which shows the following lavalink settings, using [p]audioset settings): 
![afbeelding](https://user-images.githubusercontent.com/5102501/52471420-24d98c00-2b91-11e9-8c50-593b8e1901f7.png)
2. make sure the audio cog is loaded within that container
3. play a youtube link

--------

It might be noted that I'm using the same external folder since rc2. However, for consistency reasons, I deleted the lavalink jar and restarted the discord container, which in turn re-downloads the lavalink jar file. The same thing happens.

I don't know what to think of any more, except a full clean extra try (as in: new discord token, new volume/container, etc). I expect the same result coming out of that try to be honest, though.

**Comment by mikeshardmind** [comment]
I've not run into this issue as described on Red as we currently recommend. We do not have a supported docker image yet, because none of the proposed solutions have been determined to meet quality standards yet.

I suspect this is actually an issue with the Jar being provided by the Dockerfile in question, but cannot confirm this as the repo these come from is not actually also hosting those files publicly.

See:
https://github.com/SuperSandro2000/docker-images/blob/master/reddiscord/run.sh

For where the image is actually copying in an arbitrary jar.

**Comment by EelcoLos** [comment]
> For where the image is actually copying in an arbitrary jar.

For what I can see, the lavalink @SuperSandro2000 is linking is in the makefile, which refers to the official lavalink release here:
https://github.com/SuperSandro2000/docker-images/blob/cda1efef2bde30b71a2c6992be3fb39fc81b812f/reddiscord/Makefile#L12

**Comment by mikeshardmind** [comment]
I see that, unfortunately, in the same step, he's also modifying the jar, and this isn't an error which is occurring on Red as we support it.

**Comment by Kowlin** [comment]
Closing this, due to that this is outside of our scope to fix.

**Comment by SuperSandro2000** [comment]
If he is running on arm he uses the modified jar. Amd64 uses a pure vanilla one.
