### ISSUE TITLE
Cog Repository Error

### ISSUE THREAD

**Issue by QuiteSmashing** [Cog-Creators/Red-DiscordBot#2452]
# Command bugs

#### Command name

[p]repo add

#### What cog is this command from?

downloader

#### What were you expecting to happen?

Install a Cog Repository to use within a server

#### What actually happened?

"Something went wrong during the cloning process"

Error log from Command Prompt

[14/02/2019 13:18] ERROR downloader _repo_add 237: Something went wrong whilst cloning https://github.com/Twentysix26/26-Cogs (to revision: None)
Traceback (most recent call last):
  File "C:\Users\jackt\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\downloader\downloader.py", line 228, in _repo_add
    repo = await self._repo_manager.add_repo(name=name, url=repo_url, branch=branch)
  File "C:\Users\jackt\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\downloader\repo_manager.py", line 565, in add_repo
    await r.clone()
  File "C:\Users\jackt\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\downloader\repo_manager.py", line 205, in clone
    raise errors.CloningError("Error when running git clone.")
redbot.cogs.downloader.errors.CloningError: Error when running git clone.

#### How can we reproduce this issue?

using [p]repo add (cog) to get error message (At least from what I am doing)

**Comment by Twentysix26** [comment]
For now my personal repository is v2 only. As such, it will not work with v3.

**Comment by yamikaitou** [comment]
V2 repos and cogs will not work with v3. 26 does not have a v3 repo either. You can find v3 repos at https://cogboard.red/t/approved-repositories/210 right now
