### ISSUE TITLE
"[p]local" doesn't play audio files

### ISSUE THREAD

**Issue by samclane** [Cog-Creators/Red-DiscordBot#2468]
# Command bugs

#### Command name

[p]local folder/play

#### What cog is this command from?

audio

#### What were you expecting to happen?

Play the single MP3/WAV file in the folder given. `[p]play <URL>` works fine, so I'm confused as to why this doesn't work. 

#### What actually happened?

Most of the time, Red says "Nothing found." when a folder is selected. Sometimes, however, the song file is listed. However, when selected Red gives "Nothing found." again. Here's the traceback from my `lavalink.log`:

```
[18:11:03] [ ERROR] [DefaultAudioPlayerManager] Error in loading item localtracks/oof/Roblox Death Sound (Oof).mp3
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libconnector.so was not found
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93)
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:16)
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.getInstance(Mp3DecoderLibrary.java:14)
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder.<init>(Mp3Decoder.java:26)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.<init>(Mp3TrackProvider.java:66)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:56)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:76)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:45)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:46)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:33)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:432)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	... 4 common frames omitted
[18:11:03] [ ERROR] [AudioLoader] Load failed
com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when looking up the track
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.dispatchItemLoadFailure(DefaultAudioPlayerManager.java:236)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:225)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libconnector.so was not found
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.extractLibrary(NativeLibLoader.java:93)
	at com.sedmelluq.discord.lavaplayer.natives.NativeLibLoader.load(NativeLibLoader.java:77)
	at com.sedmelluq.discord.lavaplayer.natives.ConnectorNativeLibLoader.loadConnectorLibrary(ConnectorNativeLibLoader.java:16)
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3DecoderLibrary.getInstance(Mp3DecoderLibrary.java:14)
	at com.sedmelluq.discord.lavaplayer.natives.mp3.Mp3Decoder.<init>(Mp3Decoder.java:26)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3TrackProvider.<init>(Mp3TrackProvider.java:66)
	at com.sedmelluq.discord.lavaplayer.container.mp3.Mp3ContainerProbe.probe(Mp3ContainerProbe.java:56)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.checkContainer(MediaContainerDetection.java:76)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:61)
	at com.sedmelluq.discord.lavaplayer.container.MediaContainerDetection.detectContainer(MediaContainerDetection.java:45)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.detectContainerForFile(LocalAudioSourceManager.java:46)
	at com.sedmelluq.discord.lavaplayer.source.local.LocalAudioSourceManager.loadItem(LocalAudioSourceManager.java:33)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItemOnce(DefaultAudioPlayerManager.java:432)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.checkSourcesForItem(DefaultAudioPlayerManager.java:418)
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$createItemLoader$0(DefaultAudioPlayerManager.java:217)
	... 4 common frames omitted
```

This line seems to be the culprit:

`Caused by: java.lang.UnsatisfiedLinkError: Required library at /natives/linux-arm/libconnector.so was not found`

How do I install this library? And why was it not installed in the first place, so others may avoid this mistake?

#### How can we reproduce this issue?

"v3-dev" installed on "Raspbian Stretch" with a VirtualEnv. 

`localtracks` folder is located at `/home/<USER>/.local/share/Red-DiscordBot/cogs/Audio/localtracks`. I had to make the `localtracks` folder manually, but the bot immediately saw the sub-folders. The structure goes:

```
../Red-DiscordBot/cogs/Audio/localtracks
---/folder1/
------/song1.mp3
---/folder2/
-----/song2.mp3
```

and so on...

**Comment by aikaterna** [comment]
Hi there, please visit the Red server at discord.gg/red if you're not already a member, go to the #support channel, download the Lavalink.jar we have pinned, and replace your jar. This will resolve the libconnector.so issue, and after that I'm curious if that will resolve your mp3 decoding issues.

The reason why libconnector.so is not included with the jar we distribute is that the folks that manage Lavalink and Lavaplayer haven't created jars with the natives for ARM processors yet on the CI server. We've got some folks trying to facilitate that on our side, so perhaps in the future we will have an all-in-one solution regarding Lavalink.jar files for everyone.

**Comment by samclane** [comment]
Works great!

So you (the RedBot team) have to compile a special .jar file with the correct ARM libconnector.so included?

**Comment by aikaterna** [comment]
Currently, yes. The jar we distribute is also significantly older than I would like to provide at this point, but Lavalink v3 jars don't come with natives for ARM or Macs at the moment. Once those two systems have support in auto generated builds on the Lavalink CI we will switch from distributing a Lavalink v2 jar and just go with an up to date one.

**Comment by samclane** [comment]
That seems like it might take a while. Is there a way to put a link to the modified jar into the `audio` cog install message, so people like me don't fill up the issues section? Or is it there and I just completely missed it?

**Comment by aikaterna** [comment]
We dont have info regarding the native libs being missing for some processors outside of our support channels, so you didn't miss anything. There is some discussion going around via the contributors and devs about how to distribute what we have based on OS or CPU arch, so maybe a cleaner user experience will be possible for this via Red 3.1. The details haven't been worked out on it yet.

**Comment by samclane** [comment]
Well, it's on the radar. Thanks for the quick response time!
