### ISSUE TITLE
[V3 Audio] The output of 'java -version' was unexpected

### ISSUE THREAD

**Issue by NeepOwO** [Cog-Creators/Red-DiscordBot#2524]
#### What were you trying to do?

Trying to load audio cog.  `!load audio`

#### What were you expecting to happen?

I was expecting it to load normally and to be usable.

#### What actually happened?

bot say: `Failed to load package audio. Check your console or logs for details.`
Throwing in the terminal this:
```
[17/03/2019 11:56] ERROR core_commands _load 111: Package loading failed
Traceback (most recent call last):
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\core\core_commands.py", line 105, in _load
    await bot.load_extension(spec)
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\core\bot.py", line 224, in load_extension
    await lib.setup(self)
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\audio\__init__.py", line 27, in setup
    await start_lavalink_server(bot.loop)
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\audio\manager.py", line 102, in start_lavalink_server
    java_available, java_version = await has_java(loop)
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\audio\manager.py", line 56, in has_java
    version = await get_java_version(loop)
  File "C:\Users\zvdpr\AppData\Roaming\Python\Python37\site-packages\redbot\cogs\audio\manager.py", line 96, in get_java_version
    "The output of `java -version` was unexpected. Please report this issue on Red's "
RuntimeError: The output of `java -version` was unexpected. Please report this issue on Red's issue tracker.
```

#### How can we reproduce this issue?

idk, I have windows 10, python 3.7, 
`java - version`
```
java version "1.8.0_201"
Java(TM) SE Runtime Environment (build 1.8.0_201-b09)
Java HotSpot(TM) 64-Bit Server VM (build 25.201-b09, mixed mode)
```
I tried different versions of java (jre-8u202, jre-8u191)'
`python -m pip freeze`
```
aiohttp==3.5.4
aiohttp-json-rpc==0.12.1
alabaster==0.7.12
appdirs==1.4.3
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==18.2.0
Babel==2.6.0
certifi==2018.11.29
chardet==3.0.4
colorama==0.4.1
dnspython==1.16.0
docutils==0.14
fuzzywuzzy==0.17.0
idna==2.8
idna-ssl==1.1.0
imagesize==1.1.0
Jinja2==2.10
MarkupSafe==1.1.0
more-itertools==6.0.0
motor==2.0.0
multidict==4.5.2
packaging==19.0
pluggy==0.8.1
py==1.7.0
Pygments==2.3.1
pymongo==3.7.2
pyparsing==2.3.1
pytest==4.2.0
pytest-asyncio==0.10.0
python-Levenshtein-wheels==0.13.1
pytz==2018.9
PyYAML==3.13
Red-DiscordBot==3.0.2
Red-Lavalink==0.2.3
requests==2.21.0
schema==0.6.8
six==1.12.0
snowballstemmer==1.2.1
Sphinx==1.8.4
sphinx-rtd-theme==0.4.3
sphinxcontrib-asyncio==0.2.0
sphinxcontrib-websupport==1.1.0
urllib3==1.24.1
websockets==7.0
yarl==1.3.0
```

**Comment by Twentysix26** [comment]
The root issue was two different Java installations on the same machine. For whatever reason Red was calling the non functioning `java.exe` found in the Windows folder (I think we're messing with the `PATH` order?). The command prompt was instead calling the working one.  
For future reference, the error that Java was returning can be found [here](https://stackoverflow.com/questions/9313353/error-when-checking-java-version-could-not-find-java-dll)

**Comment by Tobotimus** [comment]
We don't touch the PATH, we get the path to the java executable with `shutil.which("java")`. So whatever environment Red was started in, that one in the Windows folder would be the first one on the PATH.
