### ISSUE TITLE
[Mod] Casesfor traceback

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2541]
# Other bugs

#### What were you trying to do?

run ``casesfor <invaliduserID>``

#### What were you expecting to happen?

Return an error on an invalid UserID

#### What actually happened?

```Traceback (most recent call last):
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 912, in invoke
    await ctx.command.invoke(ctx)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 632, in invoke
    await self.prepare(ctx)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 597, in prepare
    await self._parse_arguments(ctx)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 522, in _parse_arguments
    kwargs[name] = await self.transform(ctx, param)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 379, in transform
    return await self.do_conversion(ctx, converter, argument, param)
  File "/red-v3/lib/python3.7/site-packages/redbot/core/commands/commands.py", line 287, in do_conversion
    return await super().do_conversion(ctx, converter, argument, param)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 332, in do_conversion
    raise BadUnionArgument(param, converter.__args__, errors)
discord.ext.commands.errors.BadUnionArgument: Could not convert "member" into Member or int.```

#### How can we reproduce this issue?

Run ``casesfor <invalidUID>``

Resolvable by checking if the user is in the server or via ``bot.get_user_info`` if not in the server.

**Comment by mikeshardmind** [comment]
I can't reproduce this issue. If you have some more info on this, I definitely want to make sure this wasn't missed somehow.

**Comment by Kowlin** [comment]
Can't repo this my self anymore either, seems to have fixed in some prior commit.
