### ISSUE TITLE
Error when trying to play a song

### ISSUE THREAD

**Issue by Anismash** [Cog-Creators/Red-DiscordBot#255]
`Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 244, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 70, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 384, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/root/Red-DiscordBot/cogs/audio.py", line 403, in _sing
    if await self.check_voice(msg.author, msg):
  File "/root/Red-DiscordBot/cogs/audio.py", line 689, in check_voice
    if self.bot.is_voice_connected():
TypeError: is_voice_connected() missing 1 required positional argument: 'server'
`
i get this when i say !play or !sing. I tried to rejoin server but it didnt work.

**Comment by Anismash** [comment]
newest update fixed it
