### ISSUE TITLE
Music stops playing randomly

### ISSUE THREAD

**Issue by Unholyperfection** [Cog-Creators/Red-DiscordBot#256]
While playing music using a YouTube playlist through the bot I noticed the sound cut out. The console shows songs loading and playing with no errors but sound dose not play in the server. It happened once 10-20 songs in and again about 50 songs in (users gave me the last song played and I looked for it in the playlist. It is playing songs in order I don't have them randomized currently). The only way to get sound back that I have found is restarting the bot (will be trying to reload the audio cog next time it happens and can let you know if that helps)

If you need any more info I will do my best to provide it. 

Ps. I am running the latest update of the bot which contains the rewrite of the audio cog. Upload is over 10Mbps DL is over 80 Mbps. (tests run while experiencing the issue). Ample CPU, RAM, and drive space was available at the time.

**Comment by ddday** [comment]
And I quote [https://gyazo.com/5c2bc9256dab8c40e9a8c53663bb02a2](url)

**Comment by Unholyperfection** [comment]
I assume the email I got was from a staff member (the person sent this link: https://gyazo.com/5c2bc9256dab8c40e9a8c53663bb02a2)

Quote: "Ps. I am running the latest update of the bot which contains the rewrite of the audio cog. Upload is over 10Mbps DL is over 80 Mbps. (tests run while experiencing the issue). Ample CPU, RAM, and drive space was available at the time." 

This was included to verify the issue was not on my end (yes discord was working fine as everyone else could use voice fine. The bot was the only one having issues. As far as I am aware it is a problem with the discord bot API or red or both). I don't give a damn who is at fault. I was told to make a report while in the support chat a couple days ago so I did. 

If the issue isn't on your end close the thread or reply in a respectful manner "WE DON'T CARE" is the last thing you should ever send to a user as it drives down donations and reduces the chance of that user recommending it or any other bot,program, or service you offer in the future. I realize this isn't a company and you do this in your spare time but you should still care. You should also respect your users (especially ones like me who planned to donate and actively assist people in support chat using resources from a dev. If I don't know the answer I don't say anything.) There are very few users out there who will donate or offer up there time to help. I will over look it this time but please treat your users with respect and pick your words carefully. Even small mistakes can have large repercussions. I own a small businesses so I know first hand how hard it is, the amount of time it takes, and how unforgiving users/clients are when you mess up (even something as simple as a spelling mistake). I know this is a lecture but I like the bot and I have never had any issues with staff in the chat so I want to see it succeed. So every thing I say I mean and I sincerely hope you take it to heart. Treat it like a business and one day it might be one.

Sincerely,
A.P

**Comment by ddday** [comment]
_slowly claps_

**Comment by ddday** [comment]
I apologize for commenting that rude screenshot link.

**Comment by Unholyperfection** [comment]
Don't worry about it. Had I known it was you I would have seen it as a joke. Make sure I know it's you when you send that stuff so I can come up with a good response other than a story (might still get one lol) (based on past and present conversations XD)

**Comment by ddday** [comment]
hah

**Comment by ddday** [comment]
;P

**Comment by Unholyperfection** [comment]
Re-opened at the request of Irdumb 
Unholyprfection - Today at 10:52 PM
I can re-open the issue if you want until it is fixed by discord or a bug is found in the bot and fixed. I can post updates there as I test in case you aren't on at that particular moment

irdumb - Today at 10:53 PM
please do"

**Comment by Unholyperfection** [comment]
Issue Recap.
audio stops every 15 min-2 hours.
if multiple people are in the chat it stops for everyone.
using a YouTube playlist with over 24 hours of music currently. Other playlists do the same thing.
using the latest update
plenty of resources available for it on my PC (from CPU to network it all has plenty of extra red could use)
it happens when playing the playlist in order and when using mix
It dose this randomly. random songs, random playlists, and random times
no errors in console
reloading audio doesn't fix it
only known way to fix it at this time is a bot restart
In the console songs load and play with no errors and the playlist continues regardless of if the audio is being sent over discord
!stop and !disconnect currently do nothing but create errors if run

I will post updates and info as it is available. Feel free to ask questions or for more info. I will do my best to provide it

**Comment by irdumbs** [comment]
what errors do `!stop` and `!disconnect` give?

**Comment by Unholyperfection** [comment]
Sorry I had some personal business I needed to attend to. The error only seemed to pop up the first time. I just tried to recreate it and I was able to get the bot to disconnect and start playing music after I ran !playlist mix P2 (yes my playlists are labeled P1, P2, etc... faster to type and easier to remember lol) 

If it happens again I will put the error here. I sent will the log right after it happened.

Well right after typing that I get errors XD. Music is still playing but my console looks like this (same error each time. posted the whole console to show it was being spammed):

```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py:1558> exception=AttributeError("'NoneType' object has no attribute 'id'",)>
Traceback (most recent call last):
  File "C:\Program Files (x86)\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 1607, in queue_manager
    await self._download_next(server, curr_dl, next_dl)
  File "C:\Users\austi_000\Desktop\Discord Bot\Red-DiscordBot\cogs\audio.py", line 381, in _download_next
    if curr_dl.song.id != next_dl.song.id:
AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Kowlin** [comment]
One thing I found from the error is this, `ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.`
It seems that some video's have age restrictions. And the bot will always appear as a guest from YouTube's end.
This will cause the error.

**Comment by irdumbs** [comment]
can watch when Red get's older 👍

**Comment by Unholyperfection** [comment]
Sorry I was away as we had a long weekend here. The drag track is my new fave place to spend downtime lol. 

"One thing I found from the error is this, ERROR: huxX0DmElNU: YouTube said: Please sign in to view this video.
It seems that some video's have age restrictions. And the bot will always appear as a guest from YouTube's end.
This will cause the error."

While I thought the same thing I am assuming that instead of skipping the song (I think it normally auto skips when it happens but I'm sure you guys know lol) it is looping the request giving the same result each time. If it isn't set up to auto skip when it gets an error loading the song it might be worth putting in something to catch failed video requests and skip them. If this is a feature it is possible the loop isn't ending correctly.

Using !disconnect and waiting for a bit before starting it again seems to work now so it must just have been bad luck that it didn't work when I first tried it lol.

**Comment by Kowlin** [comment]
We should take this into account. The fact that we don't skip undownloadable songs is a long standing issue that nobody found out till about last week.

We're also trying a new ffmpeg version. And hope we can get better stability from that. So that will hopefully be announced when it's ready.

**Comment by tekulvw** [comment]
We do skip undownloadable songs now. Haven't heard any continued complaints about this particular issue so I'm closing it
