### ISSUE TITLE
Windows 2016 Server

### ISSUE THREAD

**Issue by CrypticKingJoe** [Cog-Creators/Red-DiscordBot#2647]
Everything installed perfectly, but when it came to the bot running this happened 

https://i.gyazo.com/3edd308d0e0c416f1cbb10db15985191.png

Traceback (most recent call last):
  File "C:\Python37\Scripts\redbot-launcher-script.py", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.0.2', 'console_scripts', 'redbot-launcher')()
  File "C:\Python37\lib\site-packages\redbot\launcher.py", line 476, in main
    main_menu()
  File "C:\Python37\lib\site-packages\redbot\launcher.py", line 386, in main_menu
    outdated, new_version = loop.run_until_complete(is_outdated())
  File "C:\Python37\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
  File "C:\Python37\lib\site-packages\redbot\launcher.py", line 375, in is_outdated
    async with session.get("{}/json".format(red_pypi)) as r:
  File "C:\Python37\lib\site-packages\aiohttp\client.py", line 1005, in __aenter__
    self._resp = await self._coro
  File "C:\Python37\lib\site-packages\aiohttp\client.py", line 476, in _request
    timeout=real_timeout
  File "C:\Python37\lib\site-packages\aiohttp\connector.py", line 522, in connect
    proto = await self._create_connection(req, traces, timeout)
  File "C:\Python37\lib\site-packages\aiohttp\connector.py", line 854, in _create_connection
    req, traces, timeout)
  File "C:\Python37\lib\site-packages\aiohttp\connector.py", line 992, in _create_direct_connection
    raise last_exc
  File "C:\Python37\lib\site-packages\aiohttp\connector.py", line 974, in _create_direct_connection
    req=req, client_error=client_error)
  File "C:\Python37\lib\site-packages\aiohttp\connector.py", line 927, in _wrap_create_connection
    req.connection_key, exc) from exc
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host pypi.python.org:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)')]

I have disabled my firewall and anti virus in the server
What else could it be?

**Comment by CrypticKingJoe** [comment]
Fixed 

You'll have to visit the Discord site with IE on the server to acquire the SSL certificate.
Simply open discordapp.com via IE
