### ISSUE TITLE
[Audio] !playlist add not working for SoundCloud

### ISSUE THREAD

**Issue by d0muu** [Cog-Creators/Red-DiscordBot#265]
`!playlist add` <name> <link> no longer works for SoundCloud playlists.

Error, after calling `!playlist add <name> <soundcloud link>`: 

```
Ignoring exception in on_message
Traceback (most recent call last):
  ..\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 244, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 71, in on_message
    await bot.process_commands(message)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 619, in invoke
    yield from ctx.invoked_subcommand.invoke(ctx)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 384, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  ..\Red-DiscordBot\cogs\audio.py
", line 1166, in playlist_add
    songlist = await self._parse_playlist(url)
  ..\Red-DiscordBot\cogs\audio.py
", line 588, in _parse_playlist
    return await self._parse_sc_playlist(url)
  ..\Red-DiscordBot\cogs\audio.py
", line 607, in _parse_sc_playlist
    playlist.append(entry.url)
AttributeError: 'dict' object has no attribute 'url'
Ignoring exception in on_message
Traceback (most recent call last):
  ..\Programs\Python\Python35-32\lib\site-packages\discord\client.py", line 244, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 71, in on_message
    await bot.process_commands(message)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 611, in process_commands
    yield from command.invoke(ctx)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 384, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  ..\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
```

`!song` no longer works for SoudCloud songs.

Error, after calling `!song` while SoundCloud song is playing: 

```
..\Red-DiscordBot\cogs\audio.py
", line 1440, in song
    "**Views:** {}\n\n<{}>".format(song.title, song.creator,
AttributeError: 'Song' object has no attribute 'creator'
```

Using latest discord.py and Red

**Comment by calebj** [comment]
~~The first error is fixed in my PR #276~~
I fixed the second issue as well.

**Comment by d0muu** [comment]
`!play` and `!song` should be resolved with #308

**Comment by d0muu** [comment]
**SoundCloud** functionality status
`!play` <URL> - Working (Fixed with 308)
`!song` - Working (Fixed with 308)

Outstanding SC issues:
`!playlist add` <name> <URL>
   Discord Error:

```
Red: Enumerating song list... This could take a few moments.
Red: Error in command 'playlist add' - AttributeError: 'dict' object has no attribute 'url'
```

   Full Error:

```
ERROR red on_command_error 86: Exception in command 'playlist add'
Traceback (most recent call last):
  File ".\Python\Python35-32\lib\site-packages\discord\ext\commands\core.py", line 48, in wrapped
    ret = yield from coro(*args, **kwargs)
  File ".\RED\Red-DiscordBot\cogs\audio.py", line 1294, in playlist_add
    songlist = await self._parse_playlist(url)
  File ".\RED\Red-DiscordBot\cogs\audio.py", line 673, in _parse_playlist
    return await self._parse_sc_playlist(url)
  File ".\RED\Red-DiscordBot\cogs\audio.py", line 692, in _parse_sc_playlist
    playlist.append(entry.url)
AttributeError: 'dict' object has no attribute 'url'
```

**Comment by Kowlin** [comment]
#308 was never intended to make playlists on Soundcloud work.

**Comment by d0muu** [comment]
My fault, apologies - I'll clarify the previous posts.

**Comment by tekulvw** [comment]
Moving to #623
