### ISSUE TITLE
Bot won`t start

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#2808]
Error 
```py
Traceback (most recent call last):
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Scripts\Scripts\redbot.exe\__main__.py", line 9, in <module>
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\__main__.py", line 108, in main
    cli_flags=cli_flags, description=description, dm_help=None, fetch_offline_members=True
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\bot.py", line 39, in __init__
    self.db = Config.get_core_conf(force_registration=True)
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\config.py", line 654, in get_core_conf
    driver_name, "Core", "0", data_path_override=core_path, **driver_details
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\drivers\__init__.py", line 38, in get_driver
    return JSON(*args, **kwargs)
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\drivers\red_json.py", line 70, in __init__
    self._load_data()
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\drivers\red_json.py", line 94, in _load_data
    self.data = self.jsonIO._load_json()
  File "c:\users\edgar\appdata\local\programs\python\python37-32\scripts\lib\site-packages\redbot\core\json_io.py", line 83, in _load_json
    data = json.load(f)
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\json\__init__.py", line 296, in load
    parse_constant=parse_constant, object_pairs_hook=object_pairs_hook, **kw)
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\json\__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\Edgar\AppData\Local\Programs\Python\Python37-32\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 215 column 9 (char 5633)
```

**Comment by Tobotimus** [comment]
Hi @Edgar06ka, it looks as though your core settings.json file is malformed. Did you edit it at all?

The file will be located in your data path at `core/settings.json`.

If you would like us to look at it, you can post it here, but **remove your token** from it first.

**Comment by ghost** [comment]
thank you
