### ISSUE TITLE
[Audio] Unhandled error for nonexistent folders in `[p]search` command

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#2818]
# Command bugs

#### Command name

`[p]search folder:<nonexistent folder>`

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Cog to handle the error gracefully (with meaningful error message)

#### What actually happened?

Bot sent: `Error in command 'search'. Check your console or logs for details.`
Here's traceback:
```
Exception in command 'search'
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 2956, in search
    tracks = await self._folder_tracks(ctx, player, query)
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 1241, in _folder_tracks
    for local_file in await self._all_folder_tracks(ctx, folder):
  File "/home/ubuntu/red-venv/lib/python3.7/site-packages/redbot/cogs/audio/audio.py", line 1192, in _all_folder_tracks
    for f in os.listdir(current_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/ubuntu/red-data/cogs/Audio/localtracks/Spotfy/'
```

#### How can we reproduce this issue?

Use this command (replace `<nonexistent folder>` with some folder that doesn't exist in `localtracks` folder)
`[p]search folder:<nonexistent folder>`

**Comment by Jackenmen** [comment]
I forgot to say, this also happen when using `[p]search localfolder:<nonexistent folder>`
