### ISSUE TITLE
[Modlog] Reason traceback.

### ISSUE THREAD

**Issue by Kowlin** [Cog-Creators/Red-DiscordBot#2844]
# Command bugs

#### Command name

``reason <a case that doesn't exist> <reason>``

#### What cog is this command from?

``modlog``

#### What were you expecting to happen?

A propper invalid modlog case edit

#### What actually happened?

``reason`` errors out on mongodb installs.

```
Traceback (most recent call last):
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/red-v3/lib/python3.7/site-packages/redbot/cogs/modlog/modlog.py", line 189, in reason
    await case_before.edit(to_modify)
  File "/red-v3/lib/python3.7/site-packages/redbot/core/modlog.py", line 145, in edit
    await _conf.custom(_CASES, str(self.guild.id), str(self.case_number)).set(self.to_json())
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/red-v3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```

**Comment by Jackenmen** [comment]
Unrelated to mongo, the command errors out on JSON backend as well.
