### ISSUE TITLE
[V3 ModLog] [p]case errors after resetting modlog cases

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#2855]
# Command bugs

#### Command name

[p]case

#### What cog is this command from?

ModLog

#### What were you expecting to happen?

No error

#### What actually happened?

Error

#### How can we reproduce this issue?

On a bot with this dev commit *c094076cc4657bbef56a7572aab9e24eb25de78c*, I made a case (by hackbanning a random person), ran `[p]modlogset resetcases`, then tried to do `[p]case 1`. Rather than saying "That case does not exist for that server", it errored with the following error:
```py
Exception in command 'case'
Traceback (most recent call last):
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\redbot\cogs\modlog\modlog.py", line 106, in case
    await ctx.send(embed=await case.message_content(embed=True))
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\redbot\core\modlog.py", line 207, in message_content
    filter_invites(f"{self.user} ({self.user.id})")
AttributeError: 'NoneType' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\users\flame\desktop\random\testingredbot\reddev\venv\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'NoneType' object has no attribute 'id'
```
This error does not appear following the same steps on my current 3.1.2 bot. All case numbers error after clearing cases (so `[p]case 222` also throws an error), but when a new case is created that number works as normal.

*Copied from a comment in #2848*

**Comment by Tobotimus** [comment]
Resolved by #2858
