### ISSUE TITLE
Connection loss causes crash?

### ISSUE THREAD

**Issue by rezafouladian** [Cog-Creators/Red-DiscordBot#291]
```
[31/05/2016 20:07] ERROR red <module> 391: Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 346, in poll_event
    msg = yield from self.recv()
  File "Python\Python35-32\lib\site-packages\websockets\protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\discord\client.py", line 403, in connect
    yield from self.ws.poll_event()
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 351, in poll_event
    raise ReconnectWebSocket() from e
discord.gateway.ReconnectWebSocket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "Python\Python35-32\lib\asyncio\base_events.py", line 601, in create_connection
    infos = f1.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "Python\Python35-32\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 604, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 11001] Can not connect to discordapp.com:443 [getaddrinfo failed]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 381, in <module>
    loop.run_until_complete(main())
  File "Python\Python35-32\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "red.py", line 376, in main
    yield from bot.connect()
  File "Python\Python35-32\lib\site-packages\discord\client.py", line 406, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 190, in from_client
    gateway = yield from get_gateway(client.token, loop=client.loop)
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 119, in get_gateway
    resp = yield from session.get(endpoints.GATEWAY, headers=headers)
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 529, in __iter__
    resp = yield from self._coro
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 320, in connect
    .format(key, exc.strerror)) from excaiohttp.errors.ClientOSError: [Errno 11001] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [getaddrinfo failed]]

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 346, in poll_event
    msg = yield from self.recv()
  File "Python\Python35-32\lib\site-packages\websockets\protocol.py", line 296, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1006, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\discord\client.py", line 403, in connect
    yield from self.ws.poll_event()
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 351, in poll_event
    raise ReconnectWebSocket() from e
discord.gateway.ReconnectWebSocket

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "Python\Python35-32\lib\asyncio\base_events.py", line 601, in create_connection
    infos = f1.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "Python\Python35-32\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 604, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 11001] Can not connect to discordapp.com:443 [getaddrinfo failed]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 381, in <module>
    loop.run_until_complete(main())
  File "Python\Python35-32\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "red.py", line 376, in main
    yield from bot.connect()
  File "Python\Python35-32\lib\site-packages\discord\client.py", line 406, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 190, in from_client
    gateway = yield from get_gateway(client.token, loop=client.loop)
  File "Python\Python35-32\lib\site-packages\discord\gateway.py", line 119, in get_gateway
    resp = yield from session.get(endpoints.GATEWAY, headers=headers)
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 529, in __iter__
    resp = yield from self._coro
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 320, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 11001] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [getaddrinfo failed]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 581, in _create_connection
    local_addr=self._local_addr)
  File "Python\Python35-32\lib\asyncio\base_events.py", line 601, in create_connection
    infos = f1.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "Python\Python35-32\lib\socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 310, in connect
    transport, proto = yield from self._create_connection(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 604, in _create_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 11001] Can not connect to discordapp.com:443 [getaddrinfo failed]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 392, in <module>
    loop.run_until_complete(bot.logout())
  File "Python\Python35-32\lib\asyncio\base_events.py", line 337, in run_until_complete
    return future.result()
  File "Python\Python35-32\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "Python\Python35-32\lib\site-packages\discord\client.py", line 378, in logout
    response = yield from self.session.post(endpoints.LOGOUT, headers=self.headers)
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 529, in __iter__
    resp = yield from self._coro
  File "Python\Python35-32\lib\site-packages\aiohttp\client.py", line 183, in _request
    conn = yield from self._connector.connect(req)
  File "Python\Python35-32\lib\site-packages\aiohttp\connector.py", line 320, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 11001] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [getaddrinfo failed]]
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at Red-DiscordBot\cogs\audio.py:1629> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at Red-DiscordBot\cogs\audio.py:1526> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at Red-DiscordBot\cogs\audio.py:1633> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at Red-DiscordBot\cogs\streams.py:369> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() running at Red-DiscordBot\cogs\audio.py:1484> wait_for=<Future pending cb=[Task._wakeup()]>>
```

**Comment by tekulvw** [comment]
I mean..yeah...what do you expect it to do? Wait forever until it can reconnect?

**Comment by rezafouladian** [comment]
Ideally it would have some sort of reconnect timer or something, or really anything other than crashing the entire process.

**Comment by tekulvw** [comment]
It did attempt a reconnect by the way. And this is why we have `startRedLoop.bat` for windows and supervisor and upstart guides for linux

**Comment by Kowlin** [comment]
Closing due inactivity and a problem on Discords end.
