### ISSUE TITLE
[Mod] userinfo Invalid Form Body in role section (to many characters)

### ISSUE THREAD

**Issue by CGDoctor8** [Cog-Creators/Red-DiscordBot#2910]
# Command bugs

#### Command name

userinfo

#### What cog is this command from?

mod

#### What were you expecting to happen?

for userinfo to output the info of the user

#### What actually happened?

an error
```py
Exception in command 'userinfo'
Traceback (most recent call last):
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/cogs/mod/names.py", line 164, in userinfo
    await ctx.send(embed=data)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/redbot/core/commands/context.py", line 64, in send
    return await super().send(content=content, **kwargs)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/http.py", line 222, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In embed.fields.2.value: Must be 1024 or fewer in length.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/redbot/.pyenv/versions/redbot/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 BAD REQUEST (error code: 50035): Invalid Form Body
In embed.fields.2.value: Must be 1024 or fewer in length.
```

#### How can we reproduce this issue?

1. Create a cancerous amount of roles (50)
2. Give all roles to desired user
3. Get userinfo from that user
<details>
  <summary>Images</summary>
  
![image](https://user-images.githubusercontent.com/39572468/62189084-5a368980-b32b-11e9-86c0-dded94161021.png)
![image](https://user-images.githubusercontent.com/39572468/62189092-5f93d400-b32b-11e9-91cd-034de2e01f06.png)
![image](https://user-images.githubusercontent.com/39572468/62189099-64588800-b32b-11e9-81e3-ce84250419cf.png)
![image](https://user-images.githubusercontent.com/39572468/62189135-7cc8a280-b32b-11e9-8a9a-0f9cb7d67834.png)
  
</details>

**Comment by mikeshardmind** [comment]
Oh boy. Rather than attempt embed pagination, I think there's a certain point where it's acceptable to tell the server owner we wont support displaying that many roles in user info.
