### ISSUE TITLE
[Audio] Error when playing audio on two different bots with the same token

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#2913]
# Command bugs

#### Command name

`[p]play`
#### What cog is this command from?

Audio

#### What were you expecting to happen?

No error, but it to not work (maybe a message?)

#### What actually happened?

Error:
```py
Exception in command 'play'
Traceback (most recent call last):
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\redbot\cogs\audio\audio.py", line 1611, in play
    await self._enqueue_tracks(ctx, query)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\redbot\cogs\audio\audio.py", line 1723, in _enqueue_tracks
    tracks = await player.get_tracks(query)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\lavalink\rest_api.py", line 198, in get_tracks
    result = await self.load_tracks(query)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\lavalink\rest_api.py", line 169, in load_tracks
    self.__check_node_ready()
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\lavalink\rest_api.py", line 144, in __check_node_ready
    raise RuntimeError("Cannot execute REST request when node not ready.")
RuntimeError: Cannot execute REST request when node not ready.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\users\flame\appdata\local\programs\python\python37-32\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: Cannot execute REST request when node not ready.
```

#### How can we reproduce this issue?

You need two bots on two computers running on the same token.
Referred to as A and B.

1. Run `[p]play <anything>` on A
2. Run `[p]stop` on A
3. Run `[p]play <anything>` on B (while the bot account is still in the channel)

**Comment by mikeshardmind** [comment]
> You need two bots on two computers running on the same token.

I'm gonna close this one. Running multiple bots on the same token isn't something we can properly control for with how much of the api interactions assume we have all the data about our own connection to discord.
