### ISSUE TITLE
[uptime] on latest dev version uptime command is broken

### ISSUE THREAD

**Issue by kennnyshiwa** [Cog-Creators/Red-DiscordBot#2984]
# Command bugs

#### Command name

uptime

#### What cog is this command from?

core

#### What were you expecting to happen?

uptime of the bot to be displayed

#### What actually happened?

```
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\python37\lib\site-packages\redbot\core\core_commands.py", line 334, in uptime
    since = ctx.bot.uptime.strftime("%Y-%m-%d %H:%M:%S")
AttributeError: 'Red' object has no attribute 'uptime'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\discord\ext\commands\bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "c:\python37\lib\site-packages\discord\ext\commands\core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'Red' object has no attribute 'uptime'
```

#### How can we reproduce this issue?

update to the latest dev version and then run ``[p]uptime``

**Comment by mikeshardmind** [comment]
Will be fixed in #2976
