### ISSUE TITLE
[V3 Downloader] Error from invalid characters in repo name

### ISSUE THREAD

**Issue by Flame442** [Cog-Creators/Red-DiscordBot#2999]
# Command bugs

#### Command name

`[p]repo add`

#### What cog is this command from?

Downloader

#### What were you expecting to happen?

A warning message that the repo name is invalid when naming a repo something with invalid characters (such as `:` in windows)

#### What actually happened?

Error:
```py
[2019-09-14 10:39:30] [ERROR] red: Exception in command 'repo add'
Traceback (most recent call last):
  File "<VENV>\lib\site-packages\redbot\cogs\downloader\downloader.py", line 233, in _repo_add
    repo = await self._repo_manager.add_repo(name=name, url=repo_url, branch=branch)
  File "<VENV>\lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 586, in add_repo
    r = Repo(url=url, name=name, branch=branch, folder_path=self.repos_folder / name)
  File "<VENV>\lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 66, in __init__
    self.folder_path.mkdir(parents=True, exist_ok=True)
  File "<Python>\lib\pathlib.py", line 1241, in mkdir
    self._accessor.mkdir(self, mode)
NotADirectoryError: [WinError 267] The directory name is invalid: '<datapath>\\cogs\\RepoManager\\repos\\:'
```

#### How can we reproduce this issue?

Run `[p]repo add : aaaaa`
Type "I agree" if prompted

**Comment by Jackenmen** [comment]
Partly related to #2827 - if we would only allow characters A-z, numbers and underscores this would be solved.
