### ISSUE TITLE
Getting Port error when using MongoDB

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#3030]
I am unsure if this belongs here but when setting up the database, i keep getting a port error when using mongoDB.

Traceback (most recent call last):
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Daryl\AppData\Local\Programs\Python\Python37\Scripts\redbot.exe\__main__.py", line 9, in <module>
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\__main__.py", line 112, in main
    cli_flags=cli_flags, description=description, dm_help=None, fetch_offline_members=True
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\core\bot.py", line 40, in __init__
    self.db = Config.get_core_conf(force_registration=True)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\core\config.py", line 652, in get_core_conf
    driver_name, "Core", "0", data_path_override=core_path, **driver_details
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\core\drivers\__init__.py", line 42, in get_driver
    return Mongo(*args, **kwargs)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\core\drivers\red_mongo.py", line 53, in __init__
    _initialize(**kwargs)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\redbot\core\drivers\red_mongo.py", line 41, in _initialize
    _conn = motor.motor_asyncio.AsyncIOMotorClient(url, retryWrites=True)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\motor\core.py", line 141, in __init__
    delegate = self.__delegate_class__(*args, **kwargs)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\pymongo\mongo_client.py", line 524, in __init__
    res = uri_parser.parse_uri(entity, port, warn=True)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\pymongo\uri_parser.py", line 357, in parse_uri
    nodes = split_hosts(hosts, default_port=None)
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\pymongo\uri_parser.py", line 227, in split_hosts
    nodes.append(parse_host(entity, port))
  File "c:\users\daryl\appdata\local\programs\python\python37\lib\site-packages\pymongo\uri_parser.py", line 122, in parse_host
    % (port,))
ValueError: Port must be an integer between 0 and 65535:

**Comment by Jackenmen** [comment]
You should probably go to support channel on Red's discord server (discord.gg/red), cause to me it looks like you provided wrong host address during setup.

**Comment by Kowlin** [comment]
There is not enough information here to resolve the issue, what were you trying to do when the error occured, what were the parameters you gave it when you did so, (stripping out sensitive information of course), etc
