### ISSUE TITLE
Dev Installation Issue

### ISSUE THREAD

**Issue by flaree** [Cog-Creators/Red-DiscordBot#3092]
# Update - 
Upon inspecting the files from migrating to a new VPS I had copied files from a previous dev version

# Other bugs

#### What were you trying to do?

I installed the dev version of Red over my existing 3.1.6 installation and attempting to start up a bot created prior to installing dev failed to load and gave the following error.

```
py
Traceback (most recent call last):
  File "/home/flare/.local/bin/redbot", line 11, in <module>
    load_entry_point('Red-DiscordBot==3.1.6', 'console_scripts', 'redbot')()
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/__main__.py", line 134, in main
    loop.run_until_complete(modlog._init(red))
  File "uvloop/loop.pyx", line 1417, in uvloop.loop.Loop.run_until_complete
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/core/modlog.py", line 59, in _init
    await register_casetypes(all_generics)
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/core/modlog.py", line 935, in register_casetypes
    ct = await register_casetype(**new_type)
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/core/modlog.py", line 882, in register_casetype
    ct = await get_casetype(name)
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/core/modlog.py", line 816, in get_casetype
    casetype = CaseType.from_json(name, data)
  File "/home/flare/.local/lib/python3.7/site-packages/redbot/core/modlog.py", line 568, in from_json
    return cls(name=name, **data_copy, **kwargs)
TypeError: __init__() got an unexpected keyword argument 'audit_type'
```

Deleting the modlog config file fixed the issue and the bot started afterwards

#### What were you expecting to happen?

Bot to start normally.

#### What actually happened?

The bot failed to launch and shouted the error above.

#### How can we reproduce this issue?

Install dev over 3.1.6 and an active modlog file and it errord on boot.

(Most likely an edge case but I though i'd post an issue just incase.)

**Comment by mikeshardmind** [comment]
The case where this can occur isn't something we can reasonably accommodate, as it would require all cogs to be aware of future changes that lhaven't even been considered yet.

It can only happen when you've downgraded and written data after already running a config migration for a schema change.
