### ISSUE TITLE
Timeout error

### ISSUE THREAD

**Issue by Specro** [Cog-Creators/Red-DiscordBot#311]
The bot was working ok till about a week ago when it started crashing. It happens when someone uses an audio command after some time the bot has been playing. It stays in the music channel but I can't hear any audio. I tried reloading audio but that doesn't help. I'm running this on Ubuntu 14.04.4 server. Maybe many people in the channel or long playlists be the cause of this?

```
[17/06/2016 15:51] ERROR audio _join_voice_channel 560: 
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/06/2016 15:51] ERROR red on_command_error 86: Exception in command 'play'
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 48, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/cerol/Red/cogs/audio.py", line 1172, in play
    await self._join_voice_channel(voice_channel)
  File "/home/cerol/Red/cogs/audio.py", line 561, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel")
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel
[17/06/2016 15:52] ERROR audio _join_voice_channel 560: 
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/06/2016 15:52] ERROR red on_command_error 86: Exception in command 'playlist start'
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 48, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/cerol/Red/cogs/audio.py", line 1373, in playlist_start
    await self._join_voice_channel(voice_channel)
  File "/home/cerol/Red/cogs/audio.py", line 561, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel")
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel
[17/06/2016 15:52] ERROR audio _join_voice_channel 560: 
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/06/2016 15:52] ERROR red on_command_error 86: Exception in command 'playlist start'
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 48, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/cerol/Red/cogs/audio.py", line 1373, in playlist_start
    await self._join_voice_channel(voice_channel)
  File "/home/cerol/Red/cogs/audio.py", line 561, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel")
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel
[17/06/2016 17:23] ERROR audio _join_voice_channel 560: 
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/06/2016 17:23] ERROR red on_command_error 86: Exception in command 'play'
Traceback (most recent call last):
  File "/home/cerol/Red/cogs/audio.py", line 558, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 2507, in join_voice_channel
    data = yield from asyncio.wait_for(voice_data_future, timeout=10.0, loop=self.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/discord/ext/commands/core.py", line 48, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/cerol/Red/cogs/audio.py", line 1172, in play
    await self._join_voice_channel(voice_channel)
  File "/home/cerol/Red/cogs/audio.py", line 561, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel")
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel 
```

**Comment by franc-ist** [comment]
This is an error with the Discord servers. Best thing to do is wait for a while and see if the load decreases (on Discord's end). If this happens repeatedly, try switching server region.

**Comment by tekulvw** [comment]
Agreed ^ this is an error that's is on your end
