### ISSUE TITLE
[Audio] Friendly handle when Lavalink node is not ready instead of crash

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#3238]
# Command bugs

#### Command name

play, and all other Audio commands interacting with the lavalink node.

#### What cog is this command from?

audio

#### What were you expecting to happen?

Friendly error like "Can't play tracks at the moment because Lavalink node is not ready." instead of just crashing.

#### What actually happened?

```py
Traceback (most recent call last):
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/martinebots/martinebotscogs/cogs_modified/audio/audio.py", line 3183, in play
    await self._enqueue_tracks(ctx, query)
  File "/home/martinebots/martinebotscogs/cogs_modified/audio/audio.py", line 3885, in _enqueue_tracks
    result, called_api = await self.music_cache.lavalink_query(ctx, player, query)
  File "/home/martinebots/martinebotscogs/cogs_modified/audio/apis.py", line 911, in lavalink_query
    results = await player.load_tracks(query)
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/lavalink/rest_api.py", line 300, in load_tracks
    self.__check_node_ready()
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/lavalink/rest_api.py", line 268, in __check_node_ready
    raise RuntimeError("Cannot execute REST request when node not ready.")
RuntimeError: Cannot execute REST request when node not ready.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/martinebots/martinebotsvenv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: Cannot execute REST request when node not ready.```

**Comment by Drapersniper** [comment]
Cheers I'll handle this by raising a user friendly message whenever that RuntimeError is raised by RLL.
