### ISSUE TITLE
[crash] help - missing perms

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3305]
```Traceback (most recent call last):
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/commands/help.py", line 661, in red_help
    await ctx.bot.send_help_for(ctx, thing_to_get_help_for)
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/bot.py", line 447, in send_help_for
    return await self._help_formatter.send_help(ctx, help_for)
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/commands/help.py", line 125, in send_help
    await self.format_bot_help(ctx)
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/commands/help.py", line 501, in format_bot_help
    await self.send_pages(ctx, pages, embed=False)
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/commands/help.py", line 645, in send_pages
    m = await (ctx.send(embed=pages[0]) if embed else ctx.send(pages[0]))
  File "/home/bb8/venv/lib/python3.7/site-packages/redbot/core/commands/context.py", line 81, in send
    return await super().send(content=content, **kwargs)
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/abc.py", line 823, in send
    data = await state.http.send_message(channel.id, content, tts=tts, embed=embed, nonce=nonce)
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/http.py", line 218, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/bb8/venv/lib/python3.7/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 FORBIDDEN (error code: 50013): Missing Permissions
```
Traces taken from BB8

**Comment by mikeshardmind** [comment]
We've had this come up before. The answer is to have a global check for commands on being able to respond. Last time, we sort of ignored it because there was no penalty to this, but repeated 403s carry a penalty now. While we could have every command check before sending, at the end of the day, there's a minimum set of perms we should be able to reasonably expect and not burden the code with repeated checks for the most basic of actions.
