### ISSUE TITLE
[Audio] Summon command graceful errorhandling

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3353]
# Command bugs

#### Command name

summon

#### What cog is this command from?

Audio

#### What were you expecting to happen?

The bot to inform the user what happened.

#### What actually happened?

Traceback error.

```py
Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7680, in summon
    can_skip = await self._can_instaskip(ctx, ctx.author)
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7527, in _can_instaskip
    if await self._channel_check(ctx):
  File "/data/venv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 7909, in _channel_check
    player = lavalink.get_player(ctx.guild.id)
  File "/data/venv/lib/python3.8/site-packages/lavalink/lavalink.py", line 110, in get_player
    node_ = node.get_node(guild_id)
  File "/data/venv/lib/python3.8/site-packages/lavalink/node.py", line 365, in get_node
    raise IndexError("No nodes found.")
IndexError: No nodes found.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/data/venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: IndexError: No nodes found.
```

#### How can we reproduce this issue?

1. Have lavalink down (easiest with external lavalink)
2. Use summon

**Comment by Drapersniper** [comment]
Context: This is not summon specific ...  and its a rare edge case from my experience will looking into it for the next feature release

**Comment by Drapersniper** [comment]
Blocked by #3459

**Comment by Drapersniper** [comment]
Handled by https://github.com/Cog-Creators/Red-DiscordBot/pull/3503

**Comment by Drapersniper** [comment]
Note that #3503  although mitigates this appears to not fix every instance of this, and further error handling in required here to ensure all cases are properly handled.
