### ISSUE TITLE
[Cleanup] `[p]cleanup messages 50`

### ISSUE THREAD

**Issue by Drapersniper** [Cog-Creators/Red-DiscordBot#3378]
```
Traceback (most recent call last):
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/bb8/redenv/lib/python3.8/site-packages/redbot/cogs/cleanup/cleanup.py", line 379, in messages
    await mass_purge(to_delete, channel)
  File "/home/bb8/redenv/lib/python3.8/site-packages/redbot/core/utils/mod.py", line 45, in mass_purge
    await messages[0].delete()
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/message.py", line 700, in delete
    await self._state.http.delete_message(self.channel.id, self.id)
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/http.py", line 220, in request
    raise NotFound(r, data)
discord.errors.NotFound: 404 NOT FOUND (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 863, in invoke
    await ctx.command.invoke(ctx)
  File "/home/bb8/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 587, in invoke
    await super().invoke(ctx)
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1158, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 728, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/home/bb8/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 88, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: NotFound: 404 NOT FOUND (error code: 10008): Unknown Message
```

**Comment by Flame442** [comment]
I'm pretty sure this is being caused by `[p]modset deletedelay` interfering with cleanup attempting to delete the invoking message. However, it shouldn't reach the part of the code that it did (where there is only 1 message left in the list after removing groups of 100) unless that was the first message. I'm going to look into this.
