### ISSUE TITLE
[General] Roll error on big numbers

### ISSUE THREAD

**Issue by Stonedestroyer** [Cog-Creators/Red-DiscordBot#3394]
#### Command name

Roll

#### What cog is this command from?

General

#### What were you expecting to happen?

To show the number or an error

#### What actually happened?

```py
[2020-01-17 12:05:40] [ERROR] red: Exception in command 'roll'
Traceback (most recent call last):
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\.venv\lib\site-packages\discord\ext\commands\core.py", line 79, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\redbot\cogs\general\general.py", line 94, in roll
    author=author, n=humanize_number(n)
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\redbot\core\utils\chat_formatting.py", line 483, in humanize_number
    return format_decimal(val, locale=get_babel_locale(override_locale))
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\.venv\lib\site-packages\babel\numbers.py", line 415, in format_decimal
    return pattern.apply(
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\.venv\lib\site-packages\babel\numbers.py", line 996, in apply
    number = self._quantize_value(value, locale, frac_prec)
  File "C:\Users\Stonedestroyer\OneDrive\Coding\Red-DiscordBot\.venv\lib\site-packages\babel\numbers.py", line 1065, in _quantize_value
    rounded = value.quantize(quantum)
decimal.InvalidOperation: [<class 'decimal.InvalidOperation'>]
```

#### How can we reproduce this issue?

[p]roll 9999999999999999

**Comment by Stonedestroyer** [comment]
May be related to https://github.com/Cog-Creators/Red-DiscordBot/issues/3284.
