### ISSUE TITLE
warnaction add throws OSErrors

### ISSUE THREAD

**Issue by MayhemBill** [Cog-Creators/Red-DiscordBot#3515]
# Command bugs

#### Command name

warnaction

#### What cog is this command from?

Warnings

#### What were you expecting to happen?

an action was created when I try to add automated actions to warnings

#### What actually happened?
```
Exception in command 'warnaction add'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
  File "/root/redenv/lib/python3.8/site-packages/redbot/cogs/warnings/warnings.py", line 103, in action_add
  File "/root/redenv/lib/python3.8/site-packages/redbot/cogs/warnings/helpers.py", line 111, in get_command_for_exceeded_points
  File "/root/redenv/lib/python3.8/site-packages/redbot/cogs/warnings/helpers.py", line 72, in get_command_from_input
  File "/usr/lib/python3.8/inspect.py", line 985, in getsource
    lines, lnum = getsourcelines(object)
  File "/usr/lib/python3.8/inspect.py", line 967, in getsourcelines
    lines, lnum = findsource(object)
  File "/usr/lib/python3.8/inspect.py", line 798, in findsource
    raise OSError('could not get source code')
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/commands/commands.py", line 794, in invoke
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 1234, in invoke
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: OSError: could not get source code
```

#### How can we reproduce this issue?

Install Red-Bot
try to add an action to warnings
profit?

**Comment by Flame442** [comment]
What command are you trying to add? Can you provide some more detailed steps to reproduce please?

**Comment by MayhemBill** [comment]
I tried to add several commands, first I tried `kick {user}` then I tried to do `ban {user}` both of them throw the same error.

the exact command I ran was `[p]warnaction add kick 5` I waited until it allowed me to respond with the command and entered the one I wanted.

as for steps to reproduce, I can't really help, this is all I did.

**Comment by Flame442** [comment]
And you never reach the point where it asks 
> Enter the command to be run when the user returns to a value **below** the points for this action to occur.

it just errors on the first input request?

Also, please post the output of `[p]debuginfo`.

**Comment by MayhemBill** [comment]
sorry, I should've been a bit more clear, after that point, that is when I entered the command.


```
Exception in command 'debuginfo'
Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
  File "/root/redenv/lib/python3.8/site-packages/redbot/core/core_commands.py", line 1643, in debuginfo
ModuleNotFoundError: No module named 'distro'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
  File "/root/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ModuleNotFoundError: No module named 'distro'
```
that is the output of debuginfo.

**Comment by MayhemBill** [comment]
Fixed it, unrelated issues to the bot.

**Comment by Jackenmen** [comment]
Reopening, cause we shouldn't use `inspect` to check for `is_owner` check here:
https://github.com/Cog-Creators/Red-DiscordBot/blob/V3/develop/redbot/cogs/warnings/helpers.py#L72-L78

We can just check for `command.requires.privilege_level` here.
