### ISSUE TITLE
[ERROR] audio _join_voice_channel 717

### ISSUE THREAD

**Issue by uponsorrows** [Cog-Creators/Red-DiscordBot#3567]
I've just created this bot today and tried using the audio commands (more specifically play and sing). Each time it would say "Error in command 'sing'. Check your console or logs for details." This is what the log says:
`[17/02/2020 14:41] ERROR audio _join_voice_channel 717:
Traceback (most recent call last):
  File "C:\Users\Amber\Desktop\CowBoy\Red-DiscordBot\cogs\audio.py", line 715, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\Amber\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/02/2020 14:41] ERROR red on_command_error 388: Exception in command 'sing'
Traceback (most recent call last):
  File "C:\Users\Amber\Desktop\CowBoy\Red-DiscordBot\cogs\audio.py", line 715, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\Amber\AppData\Local\Programs\Python\Python36-32\lib\asyncio\tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Users\Amber\Desktop\CowBoy\Red-DiscordBot\cogs\audio.py", line 2069, in sing
    await ctx.invoke(self.play, url_or_search_terms=url)
  File "lib\discord\ext\commands\context.py", line 112, in invoke
    ret = yield from command.callback(*arguments, **kwargs)
  File "C:\Users\Amber\Desktop\CowBoy\Red-DiscordBot\cogs\audio.py", line 1525, in play
    await self._join_voice_channel(voice_channel)
  File "C:\Users\Amber\Desktop\CowBoy\Red-DiscordBot\cogs\audio.py", line 719, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel,"
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel, please try again in 10 minutes.
Task exception was never retrieved
future: <Task finished coro=<_ensure_coroutine_connect() done, defined at lib\discord\gateway.py:53> exception=InvalidStatusCode('Status code not 101: 403',)>
Traceback (most recent call last):
  File "lib\discord\gateway.py", line 60, in _ensure_coroutine_connect
    ws = yield from websockets.connect(gateway, loop=loop, klass=klass)
  File "lib\websockets\py35\client.py", line 19, in __await__
    return (yield from self.client)
  File "lib\websockets\client.py", line 215, in connect
    extra_headers=extra_headers)
  File "lib\websockets\client.py", line 125, in handshake
    raise InvalidStatusCode(status_code)
websockets.exceptions.InvalidStatusCode: Status code not 101: 403`

As I am new, I am very confused. I've tried restarting the bot, shutting down the bot and completely restarting the installation.

**Comment by Flame442** [comment]
It looks like you are using an outdated version of the bot. Make sure you install the latest V3 install of the bot from these docs: https://red-discordbot.readthedocs.io/en/stable/ 
If you need any more help installing, come down to our support server at **discord.gg/red**
