### ISSUE TITLE
[Downloader] UnicodeDecodeError in `[p]cog update`

### ISSUE THREAD

**Issue by Menteroth** [Cog-Creators/Red-DiscordBot#3637]
# Other bugs

#### What were you trying to do?

`cog update` (for all cogs)

#### What were you expecting to happen?

All cogs updated and available to reload.

#### What actually happened?

`Error in command 'cog update'. Check your console or logs for details.`

#### How can we reproduce this issue?

I have no clue sadly.

#### Debug Info for Red

Red version
3.3.2

Python version
3.8.1 (64bit)

Discord.py version
1.3.2

Pip version
20.0.2

System arch
AMD64

User
Chris

OS version
Windows 7 (version 6.1.7601)

Python executable
`c:\__\coding\redenv\scripts\python.exe`

#### Traceback

```
[ERROR] red: Exception in command 'cog update'
Traceback (most recent call last):
  File "c:\__\coding\redenv\lib\site-packages\discord\ext\commands\core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\downloader.py", line 885, in _cog_update
    await self._cog_update_logic(ctx, cogs=cogs)
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\downloader.py", line 979, in _cog_update_logic
    updated_cognames, message = await self._update_cogs_and_libs(
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\downloader.py", line 1237, in _update_cogs_and_libs
    failed_reqs = await self._install_requirements(cogs_to_update)
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\downloader.py", line 434, in _install_requirements
    if not await repo.install_raw_requirements([req], self.LIB_PATH):
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 931, in install_raw_requirements
    p = await self._run(
  File "c:\__\coding\redenv\lib\site-packages\redbot\cogs\downloader\repo_manager.py", line 533, in _run
    stderr = p.stderr.decode().strip()
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc5 in position 936: invalid continuation byte
```

**Comment by Jackenmen** [comment]
One question, is `c:\__\coding\redenv` actual path of your venv or is `__` a placeholder?

Also information to others looking at this issue, I haven't tried reproducing this yet.

**Comment by Menteroth** [comment]
It's the actual path.

**Comment by jack1142** [comment]
Update: Menteroth said in discord that this is indeed the real path and there are no placeholders.
