### ISSUE TITLE
[Audio] [p]genre fails if you disconnect while menu is open

### ISSUE THREAD

**Issue by PredaaA** [Cog-Creators/Red-DiscordBot#3712]
# Command bugs

#### Command name

[p]genre

#### What cog is this command from?

Audio

#### What were you expecting to happen?

Maybe close the menu if use disconnect command, or just don't error.

#### What actually happened?

```py
Traceback (most recent call last):
  File "/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/redbot/cogs/audio/audio.py", line 3214, in genre
    return await self._get_spotify_tracks(ctx, query)
  File "/redbot/cogs/audio/audio.py", line 3368, in _get_spotify_tracks
    player = lavalink.get_player(ctx.guild.id)
  File "/lavalink/lavalink.py", line 111, in get_player
    return node_.player_manager.get_player(guild_id)
  File "/lavalink/player_manager.py", line 412, in get_player
    raise KeyError("No such player for that guild.")
KeyError: 'No such player for that guild.'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 'No such player for that guild.'
```

#### How can we reproduce this issue?

1. Use `[p]genre`
2. Use `[p]disconnect`
3. Click on one of the reactions of the genre command.

**Comment by Drapersniper** [comment]
just fyi ... fix already done, but  will not PR until #3459 is merged

**Comment by Drapersniper** [comment]
Handled by #3502

**Comment by Drapersniper** [comment]
Welp I meant handled by #3459
