### ISSUE TITLE
Error in command 'play'. Check your console or logs for details.

### ISSUE THREAD

**Issue by Nekind** [Cog-Creators/Red-DiscordBot#3715]
# Command bugs

#### Command name

!play <url>

#### What cog is this command from?

AUDIO

#### What were you expecting to happen?

I expected a song to play in the voice channel

#### What actually happened?

The bot connects to it but nothing plays.

#### How can we reproduce this issue?

- !play <url>
- nothing plays

#### LOGS

Exception in command 'play'
Traceback (most recent call last):
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(args, **kwargs)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 2826, in play
    await self._enqueue_tracks(ctx, query)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/audio.py", line 3516, in _enqueue_tracks
    result, called_api = await self.music_cache.lavalink_query(ctx, player, query)
  File "/home/tom/redenv/lib/python3.8/site-packages/redbot/cogs/audio/apis.py", line 769, in lavalink_query
    results = await player.load_tracks(query)
  File "/home/tom/redenv/lib/python3.8/site-packages/lavalink/rest_api.py", line 319, in load_tracks
    data = await self._get(url)
  File "/home/tom/redenv/lib/python3.8/site-packages/lavalink/rest_api.py", line 286, in _get
    async with self._session.get(url, headers=self._headers) as resp:
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 1012, in aenter
    self._resp = await self._coro
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client.py", line 504, in _request
    await resp.start(conn)
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/client_reqrep.py", line 860, in start
    self._continue = None
  File "/home/tom/redenv/lib/python3.8/site-packages/aiohttp/helpers.py", line 596, in exit
    raise asyncio.TimeoutError from None
asyncio.exceptions.TimeoutError

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(ctx.args, **ctx.kwargs)
[1:59 PM] xTomR: File "/home/tom/redenv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TimeoutError:

**Comment by Drapersniper** [comment]
The exception alone is handled by #3459 
As in it is gracefully shown to the user, if there’s another issue here then that doesn’t fix it however  from a glance at the logs it just appears to be a local connectivity issue rather than something affecting Everyone on Red ( if this wasn’t the case a lot more people would be shouting about this)

**Comment by Nekind** [comment]
fixed.

**Comment by Drapersniper** [comment]
@jack1142 any QA can you please reopen to track the error handling
