### ISSUE TITLE
redbot --edit failed to exit properly after the confirmation was denied

### ISSUE THREAD

**Issue by laggron42** [Cog-Creators/Red-DiscordBot#3777]
# Other bugs

#### What were you trying to do?

Edit both owner ID and data path. I noticed the data path was wrong, so I denied the confirmation.

#### What were you expecting to happen?

See the program exit without problem.

#### What actually happened?

`RuntimeError: Event loop stopped before Future completed.`

#### How can we reproduce this issue?

See the details

```
redbot@laggron-VPS:~$ redbot --edit BotnolMusic2
Would you like to change instance's token?: [y/N] n
Would you like to change instance's prefixes?: [y/N] n
Would you like to change instance's owner?: [y/N] y
Remember:
ONLY the person who is hosting Red should be owner. This has SERIOUS security implications. The owner can access any data that is present on the host system.

Are you sure you want to change instance's owner?: [y/N] y
Please enter a Discord user id for new owner:
> 348415857728159745
Owner updated.

Would you like to change the instance name?: [y/N] n
Would you like to change the data location?: [y/N] y

We've attempted to figure out a sane default data location which is printed below. If you don't want to change this default please press [ENTER], otherwise input your desired data location.

Default: /home/redbot/.local/share/Red-DiscordBot/data/BotnolMusic2
>
You have chosen /home/redbot/.local/share/Red-DiscordBot/data/BotnolMusic2 to be your data directory.
Please confirm [Y/n]: n
Please start the process over.
Traceback (most recent call last):
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/__main__.py", line 306, in handle_edit
    loop.run_until_complete(edit_instance(red, cli_flags))
  File "uvloop/loop.pyx", line 1450, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1443, in uvloop.loop.Loop.run_until_complete
  File "uvloop/loop.pyx", line 1351, in uvloop.loop.Loop.run_forever
  File "uvloop/loop.pyx", line 519, in uvloop.loop.Loop._run
  File "uvloop/loop.pyx", line 436, in uvloop.loop.Loop._on_idle
  File "uvloop/cbhandles.pyx", line 90, in uvloop.loop.Handle._run
  File "uvloop/cbhandles.pyx", line 70, in uvloop.loop.Handle._run
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/__main__.py", line 139, in edit_instance
    _edit_data_path(data, name, data_path, copy_data, no_prompt)
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/__main__.py", line 271, in _edit_data_path
    data["DATA_PATH"] = get_data_dir(instance_name)
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/setup.py", line 102, in get_data_dir
    sys.exit(0)
SystemExit: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/redbot/.local/bin/redbot", line 8, in <module>
    sys.exit(main())
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/__main__.py", line 463, in main
    handle_edit(cli_flags)
  File "/home/redbot/.local/lib/python3.8/site-packages/redbot/__main__.py", line 311, in handle_edit
    loop.run_until_complete(asyncio.sleep(1))
  File "uvloop/loop.pyx", line 1454, in uvloop.loop.Loop.run_until_complete
RuntimeError: Event loop stopped before Future completed.
redbot@laggron-VPS:~$
```

**Comment by Jackenmen** [comment]
This seems to be an issue with `uvloop`, I'm freezing this until I get response on the issue:
https://github.com/MagicStack/uvloop/issues/336
