### ISSUE TITLE
Casesfor AttributeError

### ISSUE THREAD

**Issue by SharkyTheKing** [Cog-Creators/Red-DiscordBot#3778]
# Command bugs

#### Command name

casesfor

#### What cog is this command from?

ModLog

#### What were you expecting to happen?

To showcases on the member or say user doesn't have any cases

#### What actually happened?

Errored out with an AttributeError:
```py
Traceback (most recent call last):
  File "/red-v32/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/red-v32/lib/python3.8/site-packages/redbot/cogs/modlog/modlog.py", line 142, in casesfor
    rendered_cases = [await case.message_content(embed=embed_requested) for case in cases]
  File "/red-v32/lib/python3.8/site-packages/redbot/cogs/modlog/modlog.py", line 142, in <listcomp>
    rendered_cases = [await case.message_content(embed=embed_requested) for case in cases]
  File "/red-v32/lib/python3.8/site-packages/redbot/core/modlog.py", line 296, in message_content
    moderator = escape_spoilers(f"{self.moderator} ({self.moderator.id})")
AttributeError: 'int' object has no attribute 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/red-v32/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/red-v32/lib/python3.8/site-packages/discord/ext/commands/core.py", line 824, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/red-v32/lib/python3.8/site-packages/discord/ext/commands/core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'int' object has no attribute 'id'
```

#### How can we reproduce this issue?

Try to check someone's cases...Sometimes this works other times this errors.

**Comment by Jackenmen** [comment]
This needs a new fix again cause my PR had to be reverted because of bigger issue it introduced. I'm gonna handle that when I have time.
