### ISSUE TITLE
Audio works fine in 3.3.7, broken in 3.3.8

### ISSUE THREAD

**Issue by DJChupa13** [Cog-Creators/Red-DiscordBot#3888]
Can't load audio cog in 3.3.8, broke immediately after upgrading. Kept crashing at instance load on command line, so I unloaded it.  Now everytime I do [p]load audio I get the following log.
If I had to guess, it's got something to do with either lavalink or multidict.

```
[2020-05-29 21:48:14] [ERROR] red: Package import failed
Traceback (most recent call last):
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\core\core_commands.py", line 102, in _load
    spec = await bot._cog_mgr.find_cog(name)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\core\cog_manager.py", line 286, in find_cog
    return await self._find_core_cog(name)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\core\cog_manager.py", line 254, in _find_core_cog
    mod = import_module(real_name, package=package)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\__init__.py", line 3, in <module>
    from .core import Audio
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\core\__init__.py", line 14, in <module>
    from . import abc, cog_utils, commands, events, tasks, utilities
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\core\cog_utils.py", line 9, in <module>
    from ..converters import get_lazy_converter, get_playlist_converter
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\converters.py", line 13, in <module>
    from .apis.api_utils import standardize_scope
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\apis\__init__.py", line 1, in <module>
    from . import (
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\cogs\audio\apis\global_db.py", line 8, in <module>
    from lavalink.rest_api import LoadResult
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\lavalink\rest_api.py", line 9, in <module>
    from . import log
ImportError: cannot import name 'log' from 'lavalink' (c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\lavalink\__init__.py)
[2020-05-29 21:48:38] [WARNING] red.main: Please do not use Ctrl+C to Shutdown Red! (attempting to die gracefully...)
[2020-05-29 21:48:38] [ERROR] red.main: Received KeyboardInterrupt, treating as interrupt
[2020-05-29 21:48:38] [INFO] red.main: Signals.SIGINT received. Quitting...
[2020-05-29 21:48:38] [INFO] red.main: Please wait, cleaning up a bit more
[2020-05-29 21:48:38] [CRITICAL] red.main: Caught unhandled exception in task:
Traceback (most recent call last):
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\__main__.py", line 511, in main
    loop.run_forever()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 567, in run_forever
    self._run_once()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 1819, in _run_once
    event_list = self._selector.select(timeout)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 430, in select
    self._poll(timeout)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 779, in _poll
    status = _overlapped.GetQueuedCompletionStatus(self._iocp, ms)
KeyboardInterrupt

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\__main__.py", line 517, in main
    loop.run_until_complete(shutdown_handler(red, signal.SIGINT))
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 599, in run_until_complete
    self.run_forever()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 316, in run_forever
    super().run_forever()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 567, in run_forever
    self._run_once()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\base_events.py", line 1855, in _run_once
    handle._run()
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\site-packages\redbot\__main__.py", line 418, in shutdown_handler
    sys.exit(ExitCodes.SHUTDOWN)
SystemExit: ExitCodes.SHUTDOWN

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\proactor_events.py", line 768, in _loop_self_reading
    f.result()  # may raise
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 808, in _poll
    value = callback(transferred, key, ov)
  File "c:\users\chupa\appdata\local\programs\python\python38-32\lib\asyncio\windows_events.py", line 457, in finish_recv
    raise ConnectionResetError(*exc.args)
ConnectionResetError: [WinError 995] The I/O operation has been aborted because of either a thread exit or an application request
```

**Comment by Kowlin** [comment]
The issue was fixed in Support on Discord as a reinstall with ``pip install -U --force-reinstall Red-DiscordBot`` did the trick here.
