### ISSUE TITLE
RedBot won't start- [SSL: CERTIFICATE_VERIFY_FAILED]

### ISSUE THREAD

**Issue by jmessmer-bu** [Cog-Creators/Red-DiscordBot#4000]
**What were you trying to do?**
Turn on the bot via command prompt, `redbot [my bot name]`

**What were you expecting to happen?**
For the bot to turn on.

**What actually happened?**
The bot refuses to turn on and provides the following error message:

```
[2020-06-21 15:06:06] [CRITICAL] red.main: The main bot task didn't handle an ex
ception and has crashed
Traceback (most recent call last):
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 936,
in _wrap_create_connection
    return await self._loop.create_connection(*args, **kwargs)  # type: ignore
# noqa
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base
_events.py", line 1050, in create_connection
    transport, protocol = await self._create_connection_transport(
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\asyncio\base
_events.py", line 1080, in _create_connection_transport
    await waiter
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslp
roto.py", line 529, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\asyncio\sslp
roto.py", line 189, in feed_ssldata
    self._sslobj.do_handshake()
  File "C:\Users\User\AppData\Local\Programs\Python\Python38-32\lib\ssl.py", lin
e 944, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verif
y failed: certificate has expired (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\users\user\redenv\lib\site-packages\redbot\__main__.py", line 458, in
 red_exception_handler
    red_task.result()
  File "c:\users\user\redenv\lib\site-packages\redbot\__main__.py", line 384, in
 run_bot
    await red.start(token, bot=True, cli_flags=cli_flags)
  File "c:\users\user\redenv\lib\site-packages\redbot\core\bot.py", line 682, in
 start
    return await super().start(*args, **kwargs)
  File "c:\users\user\redenv\lib\site-packages\discord\client.py", line 584, in
start
    await self.login(*args, bot=bot)
  File "c:\users\user\redenv\lib\site-packages\discord\client.py", line 442, in
login
    await self.http.static_login(token.strip(), bot=bot)
  File "c:\users\user\redenv\lib\site-packages\discord\http.py", line 261, in st
atic_login
    data = await self.request(Route('GET', '/users/@me'))
  File "c:\users\user\redenv\lib\site-packages\discord\http.py", line 165, in re
quest
    async with self.__session.request(method, url, **kwargs) as r:
  File "c:\users\user\redenv\lib\site-packages\aiohttp\client.py", line 1012, in
 __aenter__
    self._resp = await self._coro
  File "c:\users\user\redenv\lib\site-packages\aiohttp\client.py", line 480, in
_request
    conn = await self._connector.connect(
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 523,
in connect
    proto = await self._create_connection(req, traces, timeout)
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 858,
in _create_connection
    _, proto = await self._create_direct_connection(
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 1004,
 in _create_direct_connection
    raise last_exc
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 980,
in _create_direct_connection
    transp, proto = await self._wrap_create_connection(
  File "c:\users\user\redenv\lib\site-packages\aiohttp\connector.py", line 938,
in _wrap_create_connection
    raise ClientConnectorCertificateError(
aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to hos
t discordapp.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_
VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1108)'
)]
[2020-06-21 15:06:06] [WARNING] red.main: Attempting to die as gracefully as pos
sible...
[2020-06-21 15:06:06] [INFO] red.main: Shutting down from unhandled exception
```

**How can we reproduce this issue?**
Not sure? I'm using Windows 7, Python 3.8.3, all dependencies installed manually, and reinstalled several times to ensure that this was not the problem. Bot itself has also been completely deleted several times and reinstalling has not fixed this.

Any help would be much appreciated, thank you!

**Comment by Drapersniper** [comment]
You appear to be having issues with running the bot.
For help with running the bot please go to our support server (https://discord.gg/red).
