### ISSUE TITLE
Regenerating the token when bot online causes crash

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#4065]
# Other bugs

#### What were you trying to do?

Regenerate my token in the Discord Developer Portal, then give the token to Red.

#### What were you expecting to happen?

Red to error and ask for a new token

#### What actually happened?

It crashed with an unhandled exception.

<details>
<summary>Exception:</summary>

```
[2020-07-10 08:20:51] [CRITICAL] red.main: The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\gateway.py", line 470, in poll_event
    msg = await self.recv()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\websockets\protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 4004 (private use), reason = Authentication failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\__main__.py", line 458, in red_exception_handler
    red_task.result()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\__main__.py", line 384, in run_bot
    await red.start(token, bot=True, cli_flags=cli_flags)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\core\bot.py", line 682, in start
    return await super().start(*args, **kwargs)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\shard.py", line 275, in _connect
    f.result()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\shard.py", line 78, in poll
    await self.ws.poll_event()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\gateway.py", line 478, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: code = 4004 (private use), reason = Authentication failed.
CRITICAL:red.main:The main bot task didn't handle an exception and has crashed
Traceback (most recent call last):
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\gateway.py", line 470, in poll_event
    msg = await self.recv()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\websockets\protocol.py", line 509, in recv
    await self.ensure_open()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\websockets\protocol.py", line 812, in ensure_open
    raise self.connection_closed_exc()
websockets.exceptions.ConnectionClosedError: code = 4004 (private use), reason = Authentication failed.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\__main__.py", line 458, in red_exception_handler
    red_task.result()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\__main__.py", line 384, in run_bot
    await red.start(token, bot=True, cli_flags=cli_flags)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\redbot\core\bot.py", line 682, in start
    return await super().start(*args, **kwargs)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\client.py", line 585, in start
    await self.connect(reconnect=reconnect)
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\client.py", line 499, in connect
    await self._connect()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\shard.py", line 275, in _connect
    f.result()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\shard.py", line 78, in poll
    await self.ws.poll_event()
  File "C:\Data\Red\BotVenv-3.8.2\lib\site-packages\discord\gateway.py", line 478, in poll_event
    raise ConnectionClosed(exc, shard_id=self.shard_id) from exc
discord.errors.ConnectionClosed: code = 4004 (private use), reason = Authentication failed.
[2020-07-10 08:20:51] [WARNING] red.main: Attempting to die as gracefully as possible...
WARNING:red.main:Attempting to die as gracefully as possible...
[2020-07-10 08:20:51] [INFO] red.main: Shutting down from unhandled exception
INFO:red.main:Shutting down from unhandled exception
```

</details>

#### How can we reproduce this issue?

1. Start a bot
2. Regenerate the token when the bot is running
3. See the bot have an unhandled exception and crash

**Comment by mikeshardmind** [comment]
Discord auth errors due to changing a token while the bot is running aren't something that can be handled very gracefully, and token regeneration isn't something people should need to do often or at all.

**Comment by Flame442** [comment]
The current handling is already as graceful as possible. The only thing that *might* be able to be added is a specific warning saying "hey bozo, you regenerated your token, maybe don't do that while the bot runs". Since this is an issue of user error, we currently don't see any reason it should have any extra special handling.
