### ISSUE TITLE
softban

### ISSUE THREAD

**Issue by xSignificant** [Cog-Creators/Red-DiscordBot#4073]
# Command bugs

#### Command name

Softban

#### What cog is this command from?

Mod

#### What were you expecting to happen?

Kick a user and delete 1 day's worth of their messages.

#### What actually happened?

```
Traceback (most recent call last):
  File "/root/dbot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/dbot/lib/python3.8/site-packages/redbot/cogs/mod/kickban.py", line 538, in softban
    invite = await self.get_invite_for_reinvite(ctx)
  File "/root/dbot/lib/python3.8/site-packages/redbot/cogs/mod/kickban.py", line 34, in get_invite_for_reinvite
    return await guild.vanity_invite()
  File "/root/dbot/lib/python3.8/site-packages/discord/guild.py", line 1712, in vanity_invite
    data = await self._state.http.get_invite(payload['code'])
  File "/root/dbot/lib/python3.8/site-packages/discord/http.py", line 221, in request
    raise Forbidden(r, data)
discord.errors.Forbidden: 403 Forbidden (error code: 40007): The user is banned from this guild.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/root/dbot/lib/python3.8/site-packages/discord/ext/commands/bot.py", line 892, in invoke
    await ctx.command.invoke(ctx)
  File "/root/dbot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 797, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "/root/dbot/lib/python3.8/site-packages/discord/ext/commands/core.py", line 92, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 40007): The user is banned from this guild.
```

#### How can we reproduce this issue?

Unknown. [A little context of Support Squad in #support trying to troubleshoot the issue](https://puu.sh/G6R46/8081cab447.png)

**Comment by Kowlin** [comment]
Couldn't find a true cause of this. As it seems that Discord is returning this status code, we really cannot do much here.
