### ISSUE TITLE
An error that prevents me from starting up bot

### ISSUE THREAD

**Issue by NekoTony** [Cog-Creators/Red-DiscordBot#423]
```

[25/10/2016 20:15] ERROR red <module> 436: Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 589, in _create_direct_connection
    hosts = yield from self._resolve_host(req.host, req.port)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 561, in _resolve_host
    self._resolver.resolve(host, port, family=self._family)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/resolver.py", line 29, in resolve
    host, port, type=socket.SOCK_STREAM, family=family)
  File "/usr/lib/python3.5/asyncio/futures.py", line 361, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 296, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/concurrent/futures/thread.py", line 55, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/lib/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 418, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "red.py", line 402, in main
    yield from bot.login(settings.email)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 382, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/discord/client.py", line 312, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 195, in static_login
    data = yield from self.get(self.ME)
  File "/usr/local/lib/python3.5/dist-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/usr/local/lib/python3.5/dist-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno -2] Cannot connect to host discordapp.com:443 ssl:True [Name or service not known]

Task was destroyed but it is pending!
task: <Task pending coro=<Admin.announce_manager() running at /cherry/cogs/admin.py:317> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Scheduler.queue_manager() running at /cherry/cogs/scheduler.py:263> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Statistics.reload_stats() running at /cherry/cogs/statistics.py:129> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() done, defined at /cherry/cogs/audio.py:1796> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /cherry/cogs/audio.py:1956> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /cherry/cogs/audio.py:1845> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /cherry/cogs/audio.py:1960> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /cherry/cogs/streams.py:396> wait_for=<Future pending cb=[Task._wakeup()]>>
```

What's wrong??

**Comment by Discord-ian** [comment]
`cd cherry`
`git pull`
m'tip

**Comment by NekoTony** [comment]
Thx

**Comment by NekoTony** [comment]
Apparently, it starts the bot, still got the error.

**Comment by Twentysix26** [comment]
Seems like temporary connection issues

**Comment by NekoTony** [comment]
Been happening alot lately :C

**Comment by Twentysix26** [comment]
Not much we can do on our end.
