### ISSUE TITLE
Error in [p]cleanup messages command

### ISSUE THREAD

**Issue by tmercswims** [Cog-Creators/Red-DiscordBot#442]
When I use the command `[p] cleanup messages <n>` I get the following error in Discord from the bot:
```
Error in command 'cleanup messages' - TypeError: Argument should be str
```

And the following traceback in console:
```
ERROR red on_command_error 88: Exception in command 'cleanup messages'
Traceback (most recent call last):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in w
    ret = yield from coro(*args, **kwargs)
  File "/home/ubuntu/Red-DiscordBot/cogs/mod.py", line 424, in messages
    async for message in self.bot.logs_from(channel, limit=number+1):
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/iterators.py", line 173, in __anext_
    msg = yield from self.iterate()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/iterators.py", line 115, in iterate
    yield from self.fill_messages()
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/iterators.py", line 123, in fill_mes
    data = yield from self._retrieve_messages(retrieve)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/iterators.py", line 141, in _retriev
    data = yield from self.client._logs_from(self.channel, retrieve, before=self.before)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/discord/http.py", line 105, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client.py", line 548, in __iter__
    resp = yield from self._coro
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client.py", line 198, in _request
    proxy=proxy, proxy_auth=proxy_auth, timeout=timeout)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/aiohttp/client_reqrep.py", line 79, in __ini
    url2 = url.with_query(params)
  File "/home/ubuntu/.local/lib/python3.5/site-packages/yarl/__init__.py", line 607, in with_query
    for k, v in query.items())
  File "/home/ubuntu/.local/lib/python3.5/site-packages/yarl/__init__.py", line 607, in <genexpr>
    for k, v in query.items())
  File "yarl/_quoting.pyx", line 46, in yarl._quoting._quote (yarl/_quoting.c:1384)
TypeError: Argument should be str
```

I am running the latest Red, as well as the latest discord.py (0.14.2 as of this writing).

**Comment by skeith** [comment]
I wonder how you get 0.14.2 as I can only get 0.14.1. tested using latest Red and discord.py 0.14.1, can't reproduce

**Comment by tmercswims** [comment]
Was updated to 0.14.2 yesterday: https://github.com/Rapptz/discord.py/commit/4fa13498699970752d1ab07edb715c11c6baccad

**Comment by tmercswims** [comment]
So... it works again. I changed nothing, tried again, and it works. ¯\_(ツ)_/¯
