### ISSUE TITLE
[Audio] Lavalink.jar Status

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#4505]
**If you are experiencing any problems listed in this issue, they are known and will be addressed as soon as fixes can be identified, written, and published/pushed to a new version of Red. This issue will be edited with new information as it's available to us.**

(Last updated March 29 2026. Please visit our support server at https://discord.gg/red if you need assistance.)

---

This information is for our latest Lavalink.jar, [released in Mar 2026: version 3.7.13+red.5](https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.7.13+red.5) and the [Lavalink yt plugin version 1.18.0](https://github.com/lavalink-devs/youtube-source/releases/tag/1.18.0).

### `ScriptExtractionException: Must find sig function from script` in Lavalink logs
This error in your lavalink logs indicates that you are affected by YouTube changing their cipher signature. The current solution requires the following steps:
- Switch to an unmanaged/external lavalink node that you host yourself ([guide](<https://docs.discord.red/en/stable/cog_guides/audio.html#setting-up-an-unmanaged-lavalink-node-on-a-remote-vps-or-server>)).
- In the `application.yml` file, update the `youtube-source` plugin version you are using to at least `1.14.0` and configure the new `yt-cipher` settings to point to either an external cipher server or a server you are hosting ([documentation](<https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-a-remote-cipher-server>)).

### "Sign in if you're not a bot" or "This video requires login" or "This video is unavailable"
This is an IP ban that is usually resolvable by using Oauth.
### "This content isn't available"
This means your Oauth account has been flagged and you need a new one.

**You will need to use a managed instance of Lavalink to resolve any of these errors.**
See <https://docs.discord.red/en/stable/cog_guides/audio.html#setting-up-an-unmanaged-lavalink-node-on-a-remote-vps-or-server>. This is not a 1:1 guide for this situation.
When using a managed install of Lavalink, you will need to pay attention to Red updates where we may update Red's Lavalink.jar or the application.yml, and integrate the changes into your own, modified copy of the application.yml.

**Specific "Solutions" which may or may not work for you:**
* **Find a Lavalink node on the internet and use [p]llset commands to configure your bot**
  You will be trusting a service with your bot's IP address and your users' playback queries
  You must use a Lavalink v3 node, not v4
* **You can use Oauth** - DO NOT USE AN IMPORTANT ACCOUNT
    You must re-arrange the sources used on your application.yml so that TVHTML5EMBEDDED is first and TV is second
    Follow the additional instructions at <https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-oauth-tokens>
* **You can set a potoken**
    Follow the instructions at <https://github.com/lavalink-devs/youtube-source?tab=readme-ov-file#using-a-potoken>
* **You can configure your Lavalink host to use IP rotation with an service that is not yet IP banned**
    You must have a /64 or greater assigned to you
    A basic guide can be found at <https://lavalink.dev/configuration/ipv6/>

**With any of these methods:**
You must provide your own application.yml to:
\- detail which sources the plugin will use
\- provide your Oauth information
\- provide the proper potoken information
\- outline which rotation strategy you choose to use and your IP block(s)

[See the plugin readme for more information.](<https://github.com/lavalink-devs/youtube-source?tab=readme-ov-fi>)

_______________________

#### "Something broke when playing the track." with `Caused by: java.lang.IllegalStateException: Must find action functions from script: /s/player/6450230e/player_ias.vflset/` in Lavalink logs
**A fix for this issue was added in 3.5.20.** Please update your bot to the latest version and try again. If you continue to experience this issue, after updating please let us know.

#### "Something broke when playing the track." with `Caused by: java.lang.IllegalStateException: Must find decipher function from script.` in Lavalink logs
**A fix for this issue was added in 3.5.18.** Please update your bot to the latest version and try again. If you continue to experience this issue, after updating please let us know.

[Release from Apr 2024, version 3.7.11+red.3](https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.7.11+red.3)

#### "Something broke when playing the track" with a 403 Forbidden error in Lavalink logs
**A fix for this issue was added in 3.5.14.** Please update your bot to the latest version and try again. If you continue to experience this issue, after updating please let us know.

#### Some users may get messages saying "Sign in to confirm you're not a bot".
This seems to be related to where the bot is being hosted - see the above message for 3.7.12
_______________________
[Release from Apr 2024, version 3.7.11+red.2](https://github.com/Cog-Creators/Lavalink-Jars/releases/tag/3.7.11+red.2)

Some tracks are getting stuck at 0:00.

Trying to play some private videos will result in a more generic traceback that includes the JSON response from the site instead of a proper FriendlyException string.

**Comment by Drapersniper** [comment]
Edit by aika: Superceded, comment here is regarding the 1115 build.

- Yet another yt songs returning `Something broke when playing the track`.


```
2020-10-26 13:10:41.074  INFO 30584 --- [XNIO-1 I/O-8] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "133049272517001216", "track": "QAAAgAIAHFRva3lvIEdob3VsICJVTlJBVkVMIiBMeXJpY3MACldhdER1WXVXYW4AAAAAAAOlmAALVzJfT0d5UVBxQnMAAQAraHR0cHM6Ly93d3cueW91dHViZS5jb20vd2F0Y2g/dj1XMl9PR3lRUHFCcwAHeW91dHViZQAAAAAAAAAA"}
2020-10-26 13:10:41.545 ERROR 30584 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of W2_OGyQPqBs

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:43) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:117) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.58.jar!/:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.NullPointerException: null
	at java.base/java.util.concurrent.ConcurrentHashMap.get(Unknown Source) ~[na:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.getCipherKeyFromScript(YoutubeSignatureCipherManager.java:136) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeSignatureCipherManager.resolveFormatUrl(YoutubeSignatureCipherManager.java:103) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:87) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.source.youtube.YoutubeAudioTrack.process(YoutubeAudioTrack.java:42) ~[lavaplayer-1.3.58.jar!/:na]
	at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.58.jar!/:na]
	... 4 common frames omitted
```


EDIT: Should be resolved now on build 1128

**Comment by Drapersniper** [comment]
Errors on 
```
        Version:        3.3.1.4
        Build:          1128
        Build time:     28.10.2020 16:23:24 UTC
        Branch          JackTheEternalVirgin
        Commit:         6f0a682
        Commit time:    29.09.2020 10:25:53 UTC
        JVM:            11.0.6
        Lavaplayer      1.3.53
```

```
2020-10-29 12:26:50.941  INFO 22864 --- [   XNIO-1 I/O-2] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "133049272517001216", "track": "QAABDQIAGOS6jOS6uuOBruODouODjuOCsOODqeODoAAJ576O6aKo6JeNf/////////8AY2h0dHBzOi8vY2RuLmRpc2NvcmRhcHAuY29tL2F0dGFjaG1lbnRzLzE2OTg2ODg0Njc1OTU0Mjc4NS81ODA4Mzk0NTgzODM5ODY3MTgvRnV0YXJpX25vX01vbm9ncmFtLm9nZwEBAGNodHRwczovL2Nkbi5kaXNjb3JkYXBwLmNvbS9hdHRhY2htZW50cy8xNjk4Njg4NDY3NTk1NDI3ODUvNTgwODM5NDU4MzgzOTg2NzE4L0Z1dGFyaV9ub19Nb25vZ3JhbS5vZ2cABGh0dHAAA29nZwAAAAAAAAAA", "noReplace": false, "startTime": "0"}
2020-10-29 12:30:20.073 ERROR 22864 --- [back-1-thread-5] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of https://cdn.discordapp.com/attachments/169868846759542785/580839458383986718/Futari_no_Monogram.ogg

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something went wrong when decoding the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:44) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:294) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.process(OggAudioTrack.java:39) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.source.http.HttpAudioTrack.process(HttpAudioTrack.java:54) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:105) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:349) ~[lavaplayer-1.3.53.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
        at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
Caused by: java.lang.IllegalStateException: Cannot load the next track while the previous one has not been consumed.
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggPacketInputStream.startNewTrack(OggPacketInputStream.java:56) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.detectCodec(OggTrackLoader.java:41) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggTrackLoader.loadTrackBlueprint(OggTrackLoader.java:31) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.processTrackLoop(OggAudioTrack.java:61) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.container.ogg.OggAudioTrack.lambda$process$0(OggAudioTrack.java:41) ~[lavaplayer-1.3.53.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.executeProcessingLoop(LocalAudioTrackExecutor.java:276) ~[lavaplayer-1.3.53.jar!/:na]
        ... 8 common frames omitted
```
