### ISSUE TITLE
ReactionPredicate cannot handle custom emoji.

### ISSUE THREAD

**Issue by madebylydia** [Cog-Creators/Red-DiscordBot#4592]
# Other bugs

#### What were you trying to do?

I added a custom emoji to a message that the bot is waiting for adding a reaction.

#### What were you expecting to happen?

I expected `wait_for` to ignore the emoji, since I have set a specific emoji to be added.

#### What actually happened?

The code errored:
```python
Traceback (most recent call last):
  File "/home/pi/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/dev_commands.py", line 202, in _eval
    result = await func()
  File "<string>", line 4, in func
  File "/home/pi/.pyenv/versions/3.8.6/lib/python3.8/asyncio/tasks.py", line 455, in wait_for
    return await fut
  File "/home/pi/.pyenv/versions/red/lib/python3.8/site-packages/discord/client.py", line 360, in dispatch
    result = condition(*args)
  File "/home/pi/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/utils/predicates.py", line 905, in __call__
    return self._pred(self, reaction, user)
  File "/home/pi/.pyenv/versions/red/lib/python3.8/site-packages/redbot/core/utils/predicates.py", line 971, in predicate
    self.result = emojis.index(r.emoji)
TypeError: must be str, not Emoji  # Can also be PartialEmoji if from another server
```

#### How can we reproduce this issue?

- Run this 
```python
from redbot.core.utils.predicates import ReactionPredicate
rp = ReactionPredicate.with_emojis("AddAnEmojiHere,CanBeWhatever", message=ctx.message, user=ctx.author)
return await bot.wait_for("reaction_add", check=rp)
```
- Add a custom emoji to your message.

**Comment by madebylydia** [comment]
In the same time, I have encoutered 2 another issues which seem related.
- https://predeactor.please-end.me/1e9pi0.png
`ctx`, `message` and `user` are optional argument, which I ignored and made this error, I wasn't able to react, I directly got this error.

Otherwise, adding `message` and `user` will work fine.

**Comment by Jackenmen** [comment]
Custom emojis need to be passed using `discord.Emoji` objects

**Comment by madebylydia** [comment]
Closing, the issue is actually wrong.
