### ISSUE TITLE
[Core] Load tries to load non-packages

### ISSUE THREAD

**Issue by aikaterna** [Cog-Creators/Red-DiscordBot#4623]
# Command bugs

#### Command name

[p]load

#### What cog is this command from?

Core

#### What were you expecting to happen?

For the bot to say that the module wasn't found in any cog path.

#### What actually happened?

```
[2020-11-18 13:02:41] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "c:\envs\joker3.4\lib\site-packages\redbot\core\core_commands.py", line 172, in _load
    await bot.load_extension(spec)
  File "c:\envs\joker3.4\lib\site-packages\redbot\core\bot.py", line 1202, in load_extension
    lib = spec.loader.load_module()
TypeError: load_module() missing 1 required positional argument: 'fullname'
```

#### How can we reproduce this issue?

Use `[p]load locales`

**Comment by Kowlin** [comment]
Seems that the bot thinks that the folder ``locales`` in ``~/redbot/cogs`` is a cog folder, we can probably just go ahead and exclude the entire ``locales`` from being loadable.
