### ISSUE TITLE
`[p]streamalert youtube` raises an error

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#4625]
# Command bugs

#### Command name

`[p]streamalert youtube`

#### What cog is this command from?

Streams

#### What were you expecting to happen?

I expected it to work.

#### What actually happened?

I got an error:
```
Exception in command 'streamalert youtube'
Traceback (most recent call last):
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/discord/ext/commands/core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/cogs/streams/streams.py", line 322, in youtube_alert
    await self.stream_alert(ctx, YoutubeStream, channel_name_or_id)
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/cogs/streams/streams.py", line 411, in stream_alert
    stream = _class(name=channel_name, token=token)
  File "/home/ubuntu/red-venv/lib/python3.8/site-packages/redbot/cogs/streams/streamtypes.py", line 92, in __init__
    self._config = kwargs.pop("config")
KeyError: 'config'
```

#### How can we reproduce this issue?

Just try calling `[p]streamalert youtube` with some YouTube channel.

**Comment by laggron42** [comment]
Gonna work on a fix myself for that one
