### ISSUE TITLE
Can't remove paths added before backup

### ISSUE THREAD

**Issue by Vexed01** [Cog-Creators/Red-DiscordBot#4662]
# Command bugs

#### Command name

`removepath`

#### What cog is this command from?

CogManagerUI

#### What were you expecting to happen?

The path to be removed

#### What actually happened?

It errored: 

<details>
<summary>Traceback</summary>

```py
Exception in command 'removepath'
Traceback (most recent call last):
  File "C:\Users\host\redenv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\host\redenv\lib\site-packages\redbot\core\cog_manager.py", line 383, in removepath
    await ctx.bot._cog_mgr.remove_path(to_remove)
  File "C:\Users\host\redenv\lib\site-packages\redbot\core\cog_manager.py", line 183, in remove_path
    paths.remove(path)
ValueError: list.remove(x): x not in list

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\host\redenv\lib\site-packages\discord\ext\commands\bot.py", line 903, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\host\redenv\lib\site-packages\discord\ext\commands\core.py", line 859, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\host\redenv\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: ValueError: list.remove(x): x not in list
```

</details>

#### How can we reproduce this issue?

1. Set up a bot with a custom path added
2. Back it up and restore on another machine (I reproduced this on Linux -> Windows, might work on the same operating system, idk)
3. Attempt to remove the path that was added on the original machine

![theres an image here that only embeds nicely on github, not in discord webhooks. sorry.](http://i.vex.my.to/Vo0pUA)

**Comment by NeuroAssassin** [comment]
Will be closed by #4466
