### ISSUE TITLE
[Streams] Error checking stream feeds since latest update

### ISSUE THREAD

**Issue by TrustyJAID** [Cog-Creators/Red-DiscordBot#4735]
# Other bugs

#### What were you trying to do?

Running my bot with the streams cog loaded with a handful of followed accounts.

#### What were you expecting to happen?

Bot update and cog update work just fine with no errors.

#### What actually happened?

Checked my logs after a few days and noticed pages and pages of logs filled with the following error.
```
Jan 15 23:25:32 TrustyBot redbot[939]: [2021-01-15 23:25:32] [ERROR] red.core.cogs.Streams: An error has occured with Streams. Please report it.
Jan 15 23:25:32 TrustyBot redbot[939]: Traceback (most recent call last):
Jan 15 23:25:32 TrustyBot redbot[939]:   File "/home/trusty/red/lib/python3.8/site-packages/redbot/cogs/streams/streams.py", line 737, in check_streams
Jan 15 23:25:32 TrustyBot redbot[939]:     embed, is_schedule = await stream.is_online()
Jan 15 23:25:32 TrustyBot redbot[939]:   File "/home/trusty/red/lib/python3.8/site-packages/redbot/cogs/streams/streamtypes.py", line 117, in is_online
Jan 15 23:25:32 TrustyBot redbot[939]:     for video_id in get_video_ids_from_feed(rssdata):
Jan 15 23:25:32 TrustyBot redbot[939]:   File "/home/trusty/red/lib/python3.8/site-packages/redbot/cogs/streams/streamtypes.py", line 47, in get_video_ids_from_feed
Jan 15 23:25:32 TrustyBot redbot[939]:     root = ET.fromstring(feed)
Jan 15 23:25:32 TrustyBot redbot[939]:   File "/usr/lib/python3.8/xml/etree/ElementTree.py", line 1320, in XML
Jan 15 23:25:32 TrustyBot redbot[939]:     parser.feed(text)
Jan 15 23:25:32 TrustyBot redbot[939]:   File "<string>", line None
Jan 15 23:25:32 TrustyBot redbot[939]: xml.etree.ElementTree.ParseError: not well-formed (invalid token): line 2, column 11
```

#### How can we reproduce this issue?

I am not quite sure but I can help diagnose exactly what's causing it.

**Comment by TrustyJAID** [comment]
Turns out there was a youtube stream setup at some point that was causing this error.
