### ISSUE TITLE
[Streams] Background check raises ContentTypeError for Twitch stream

### ISSUE THREAD

**Issue by Injabie3** [Cog-Creators/Red-DiscordBot#4811]
**What Red version are you using?**

3.4.6.dev1

**What were you trying to do?**

Testing 3.4.6.dev1 with the new streams patches.

**What did you expect to happen?**

Nothing

**What actually happened?**

One instance of the following message being printed:
```
[2021-02-11 17:54:07] [ERROR] red.core.cogs.Streams: An error has occured with Streams. Please report it.
Traceback (most recent call last):
  File "/home/ubuntu/github/renchan/lib/python3.8/site-packages/Red_DiscordBot-3.4.6.dev1-py3.8.egg/redbot/cogs/streams/streams.py", line 734, in check_streams
    embed, is_rerun = await stream.is_online()
  File "/home/ubuntu/github/renchan/lib/python3.8/site-packages/Red_DiscordBot-3.4.6.dev1-py3.8.egg/redbot/cogs/streams/streamtypes.py", line 279, in is_online
    data = await r.json(encoding="utf-8")
  File "/home/ubuntu/github/renchan/lib/python3.8/site-packages/aiohttp-3.7.3-py3.8-linux-x86_64.egg/aiohttp/client_reqrep.py", line 1097, in json
    raise ContentTypeError(
aiohttp.client_exceptions.ContentTypeError: 0, message='Attempt to decode JSON with unexpected mimetype: text/html', url=URL('https://api.twitch.tv/helix/streams/?user_id=108375107')
```

**How can we reproduce this error?**

Unsure, I have only seen this message once so far. I have not added/removed twitch streams in over 3 months.

**Comment by Flame442** [comment]
Typically when an HTTP request returns `text/html` unexpectedly, it is due to a 5xx error that is not formatted the same way as the endpoint typically is. Since this issue was only seen one time in over a year, I am going to assume that was the problem, and close this issue. Feel free to add a comment if this issue persists.
