### ISSUE TITLE
Error with !yt command

### ISSUE THREAD

**Issue by joshoram80** [Cog-Creators/Red-DiscordBot#493]
When attempting to play youtube audio I get the following

Error in command 'yt' - AttributeError: 'NoneType' object has no attribute 'replace'
Error in command 'yt' - ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..

and

Error in command 'yt' - ConnectionClosed: WebSocket connection is closed: code = 4006, reason = Session is no longer valid..
Error in command 'yt' - ConnectTimeout: We timed out connecting to a voice channel

Bot Console shows

[26/11/2016 15:39] ERROR red on_command_error 238: Exception in command 'yt'
Traceback (most recent call last):
  File "C:\Users\Sancho\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\audio.py", line 1806, in yt_search
    await ctx.invoke(self.play, url_or_search_terms=search_terms)
  File "C:\Users\Sancho\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\ext\commands\context.py", line 112, in invoke
    ret = yield from command.callback(*arguments, **kwargs)
  File "C:\Red-DiscordBot\cogs\audio.py", line 1276, in play
    await self._join_voice_channel(voice_channel)
  File "C:\Red-DiscordBot\cogs\audio.py", line 589, in _join_voice_channel
    await self.bot.join_voice_channel(channel)
  File "C:\Users\Sancho\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\client.py", line 3179, in join_voice_channel
    yield from voice.connect()
  File "C:\Users\Sancho\AppData\Local\Programs\Python\Python35\lib\site-packages\discord\voice_client.py", line 247, in connect
    self.endpoint = self.endpoint.replace(':80', '')
AttributeError: 'NoneType' object has no attribute 'replace'

Was previously working fine for a week. Nothing has changed apart from changing bot's permissions on 2 channels

**Comment by Kowlin** [comment]
It appears to come from your connection. The connection between (What I assume) Discord and the bot closed.

**Comment by Kowlin** [comment]
Closing due to inactivity.
