### ISSUE TITLE
`[p]addpath` raises `OSError`s for paths with invalid characters

### ISSUE THREAD

**Issue by Jackenmen** [Cog-Creators/Red-DiscordBot#5138]
### What Red version are you using?

3.4.11

### Cog name

CogManagerUI

### Command name

addpath

### What did you expect to happen?

The command to send a friendly error message.

### What actually happened?

An exception was raised during the execution of the command.

### How can we reproduce this error?

1. Run `[p]addpath 'C:\'`
2. See error:
```py
Exception in command 'addpath'
Traceback (most recent call last):
  File "C:\Users\Jakub\OneDrive\Dokumenty\Red-DiscordBot\.venv\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Jakub\OneDrive\Dokumenty\Red-DiscordBot\redbot\core\cog_manager.py", line 350, in addpath
    if not path.is_dir():
  File "C:\Python38\lib\pathlib.py", line 1415, in is_dir
    return S_ISDIR(self.stat().st_mode)
  File "C:\Python38\lib\pathlib.py", line 1197, in stat
    return self._accessor.stat(self)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: "'C:\\'"
```

### Anything else?

Tested on Windows (as in the NTFS file system), might also be reproducible with the use of `:` on Mac (as in the HFS/HFS+ file system)

**Comment by Jackenmen** [comment]
This turns out to be a Python bug that has been fixed in Python 3.8.10 and 3.9.5 so there's no need to fix it on our side.
