### ISSUE TITLE
Queuing up songs causing error

### ISSUE THREAD

**Issue by Sorgrum** [Cog-Creators/Red-DiscordBot#515]
Doing a "play songURL" causes an error, but the song still plays.

`
Task exception was never retrieved
future: <Task finished coro=<Audio._update_bot_status() done, defined at /home/mgheiler/RedBot/Red-DiscordBot/cogs/audio.py:941> exception=AttributeError("'<class '__main__.Bot'>' object has no attribute 'change_presence'",)>
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/home/mgheiler/RedBot/Red-DiscordBot/cogs/audio.py", line 954, in _update_bot_status
    await self._add_song_status(song)
  File "/home/mgheiler/RedBot/Red-DiscordBot/cogs/audio.py", line 260, in _add_song_status
    await self.bot.change_presence(status=status, game=game)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 264, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Bot'>' object has no attribute 'change_presence'
`

**Comment by Twentysix26** [comment]
Update discord.py
`update.bat`
or
`pip3 install -U git+https://github.com/Rapptz/discord.py@master#egg=discord.py[voice]`
