### ISSUE TITLE
Problem with audio cogs

### ISSUE THREAD

**Issue by cind8** [Cog-Creators/Red-DiscordBot#521]
So I followed the instructions step by step and everything seemed okay, but for some reason my audio cogs won't install/work. I downloaded 64 bit opus and tried "!load audio". The following message appeared : "Module was found and possibly loaded but something went wrong. Check your console or logs for more information. Error: 8". In my cmd box, the following appeared:

> [10/12/2016 00:30] ERROR owner load 75: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\owner.py", line 746, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 724, in load_extension
    lib.setup(self)
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\audio.py", line 2136, in setup
    player = verify_ffmpeg_avconv()
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\audio.py", line 2108, in verify_ffmpeg_avconv
    subprocess.call(["ffmpeg", "-version"], stdout=subprocess.DEVNULL)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application
Traceback (most recent call last):
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\owner.py", line 65, in load
    self._load_cog(module)
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\owner.py", line 746, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\site-packages\discord\ext\commands\bot.py", line 724, in load_extension
    lib.setup(self)
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\audio.py", line 2136, in setup
    player = verify_ffmpeg_avconv()
  File "C:\Users\cindy\Desktop\Red-DiscordBot\cogs\audio.py", line 2108, in verify_ffmpeg_avconv
    subprocess.call(["ffmpeg", "-version"], stdout=subprocess.DEVNULL)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 557, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 947, in __init__
    restore_signals, start_new_session)
  File "C:\Users\cindy\AppData\Local\Programs\Python\Python35-32\lib\subprocess.py", line 1224, in _execute_child
    startupinfo)
OSError: [WinError 193] %1 is not a valid Win32 application

Just for reference, my folder looks like this:

![2016-12-10 1](https://cloud.githubusercontent.com/assets/24490360/21072278/9d9b4b5e-be71-11e6-8329-d1a60bdcf7e8.png)

And my cogs folder looks like this:

![2016-12-10](https://cloud.githubusercontent.com/assets/24490360/21072281/a576b3d6-be71-11e6-99ac-2c3fd48699ca.png)

**Comment by PlanetTeamSpeakk** [comment]
You do not have the right ffmpeg, ffmprobe and ffmplay files, you can download them with download_ffmpeg.bat

**Comment by cind8** [comment]
Thank you!
