### ISSUE TITLE
[Installation] UnicodeDecodeError: 'utf-8'

### ISSUE THREAD

**Issue by LuisSousaRego** [Cog-Creators/Red-DiscordBot#549]
Hello, I am trying to install the bot using windows, but when I run the update.bat it always gives me this error that prevents me from going any further
```
Exception:
Traceback (most recent call last):
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 19: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\commands\install.py", line 324, in run
    requirement_set.prepare_files(finder)
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_set.py", line 634, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_set.py", line 129, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\req\req_install.py", line 439, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\LR\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 19: invalid continuation byte
```

I believe I did everything according to the wiki, even reinstalled python and, nothing changed. Also tried to run the py `-3 -m pip install --upgrade pip` command but everything was fine

Any ideia how can I fix this? thanks

**Comment by Twentysix26** [comment]
In case you still need help: try using Python 3.5 instead. 3.6 causes some issues during the installation for now.

**Comment by DangoShu** [comment]
Same problem here:
```
Exception:
Traceback (most recent call last):
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\compat\__init__.py", line 47, in console_to_str
    return s.decode(sys.__stdout__.encoding)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\encodings\cp65001.py", line 17, in decode
    return codecs.code_page_decode(65001, input, errors, True)
UnicodeDecodeError: 'CP_UTF8' codec can't decode bytes in position 0--1: No mapping for the Unicode character exists in the target code page.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\commands\install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 505, in _prepare_file
    abstract_dist.prep_for_dist()
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 123, in prep_for_dist
    self.req_to_install.run_egg_info()
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_install.py", line 410, in run_egg_info
    command_desc='python setup.py egg_info')
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\utils\__init__.py", line 711, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\compat\__init__.py", line 49, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 17: invalid continuation byte
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```
And then, when I tried "py -3 -m pip install --upgrade pip" I got:
```
Collecting pip
  Using cached pip-9.0.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 7.1.2
Exception:
Traceback (most recent call last):
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\basecommand.py", line 211, in main
    status = self.run(options, args)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\commands\install.py", line 311, in run
    root=options.root_path,
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_set.py", line 640, in install
    requirement.uninstall(auto_confirm=True)
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\req\req_install.py", line 673, in uninstall
    for path in pip.wheel.uninstallation_paths(dist):
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\wheel.py", line 512, in unique
    for item in fn(*args, **kw):
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\wheel.py", line 531, in uninstallation_paths
    r = csv.reader(FakeFile(dist.get_metadata_lines('RECORD')))
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1619, in get_metadata_lines
    return yield_lines(self.get_metadata(name))
  File "C:\Users\梓涵\AppData\Local\Programs\Python\Python35-32\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 1616, in get_metadata
    return self._get(self._fn(self.egg_info, name)).decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe8 in position 22365: invalid continuation byte
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```

**Comment by tekulvw** [comment]
do we have a list of issues with 3.6 yet?

**Comment by Kowlin** [comment]
@tekulvw Anything tagged with Python 3.6?? <3

**Comment by LuisSousaRego** [comment]
@Twentysix26 I did try using python 3.5 and I still got the same error

**Comment by DangoShu** [comment]
I later found out that my problem was caused by the Chinese characters in my path. For everyone having similar problems.

**Comment by tekulvw** [comment]
Yup, that'd be utf-16 character encoding. Python 3.X by default encodes/decodes to UTF-8, therefore this is not in fact a 3.6 issue

**Comment by Aareon** [comment]
Not necessarily a bug, either. This seems to me to be 100% user error.

**Comment by Kowlin** [comment]
Problem was solved with the launcher.

**Comment by DarthJahus** [comment]
Just got this error while installing MarkupSafe, in order to install Jupyter.
As @DangoShu stated, it's a problem with `PATH`.
You can actually solve it this way:
1. Save your PATH somewhere
2. Set your PATH to something ordinary and trivial like `PATH C:\Python36`
3. Install MarkupSafe
4. Recover your previous PATH

**Comment by tekulvw** [comment]
What does the MarkupSafe installation do to your path? Could you provide us your PATH at steps 1, 2, and 3?

**Comment by DarthJahus** [comment]
Not sure what it does to the path, but thing is that something in the path prevented it from installing successfully. After "flushing" the PATH, I installed MarkupSafe and then restored PATH to previous state.

Here's my actual path:

`C:\Users\jahus>PATH
PATH=C:\Python36\Scripts\;C:\Python36\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Python27\;C:\Program Files\Python35\Scripts\;C:\Program Files\Python35\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\AMD\ATI.ACE\Core-Static;C:\Program Files (x86)\Druide\Antidote 8\Programmes64\;C:\Program Files (x86)\Druide\Antidote 8\Programmes32\;C:\Program Files (x86)\Windows Live\Shared;C:\WINDOWS\system32\config\systemprofile\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\OpenVPN\bin;C:\Program Files\Calibre2\;C:\ProgramData\Anaconda3;C:\ProgramData\Anaconda3\Scripts;C:\ProgramData\Anaconda3\Library\bin;C:\Users\jahus\AppData\Local\Microsoft\WindowsApps;E:\$ Program Files\FAHClient;`

**Comment by rinkky** [comment]
I got this error while installing spidermonkey.  
I solved this by running `cmd` as Admin.

**Comment by Kowlin** [comment]
Locking this issue since this is not related to the Red project.
