### ISSUE TITLE
Error in Downloader Cog

### ISSUE THREAD

**Issue by Jan200101** [Cog-Creators/Red-DiscordBot#562]
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/red-discordbot/cogs/downloader.py", line 366, in _install
    install_cog = await self.install(repo_name, cog, notify_reqs=True)
  File "/home/pi/red-discordbot/cogs/downloader.py", line 413, in install
    requirements = data.get("REQUIREMENTS", [])
AttributeError: 'NoneType' object has no attribute 'get'

```

**Comment by Jan200101** [comment]
The cog has no info.json in the same directory as itself if it helps
