### ISSUE TITLE
Bot unable to play music  - "Object has no attribute 'duration'"

### ISSUE THREAD

**Issue by abdiuhawiudahiu** [Cog-Creators/Red-DiscordBot#593]
Hello. So I have been using Discord Red for a couple of months now, and this problem has all of a sudden arisen. I haven't done anything to the bot recently, and my bot for some reason now cannot play music.

Here is the command line it gives me:

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "lib\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_fu
nction
    errnote='Download of %s failed' % player_url)
  File "lib\youtube_dl\extractor\common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote,
 fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "lib\youtube_dl\extractor\common.py", line 436, in _download_webpage_hand
le
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal,
 data=data, headers=headers, query=query)
  File "lib\youtube_dl\extractor\common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "lib\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "lib\youtube_dl\utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "D:\Documents\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "D:\Documents\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "D:\Documents\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/bas
e.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are
 using the latest version; see  https://yt-dl.org/update  on how to update. Be s
ure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at D:\Documents
\badman\Red-DiscordBot\cogs\audio.py:1994> exception=AttributeError("'NoneType'
object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "D:\Documents\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 2027, in queue_m
anager
    song = await self._play(sid, url)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 796, in _play
    song = await self._guarantee_downloaded(server, url)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 600, in _guarant
ee_downloaded
    self.downloaders[server.id].duration_check()
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 252, in duration
_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at D:\Documents
\badman\Red-DiscordBot\cogs\audio.py:1994> exception=AttributeError("'NoneType'
object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "D:\Documents\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 2027, in queue_m
anager
    song = await self._play(sid, url)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 796, in _play
    song = await self._guarantee_downloaded(server, url)
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 600, in _guarant
ee_downloaded
    self.downloaders[server.id].duration_check()
  File "D:\Documents\badman\Red-DiscordBot\cogs\audio.py", line 252, in duration
_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```

So far I've restarted discord red numerous times, restarted my computer altogether, and I have tried updating and repairing discord red. Anyone have any suggestions on what I should do? Thank you for your time.

**Comment by Twentysix26** [comment]
#594

**Comment by abdiuhawiudahiu** [comment]
Thanks!
