### ISSUE TITLE
Play command does not work with youtube

### ISSUE THREAD

**Issue by tonytej** [Cog-Creators/Red-DiscordBot#594]
Every time I used the play command with youtube links this error showed up:
```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib\youtube_dl\extractor\youtube.py", line 1057, in _decrypt_signature
    video_id, player_url, s
  File "lib\youtube_dl\extractor\youtube.py", line 971, in _extract_signature_function
    errnote='Download of %s failed' % player_url)
  File "lib\youtube_dl\extractor\common.py", line 529, in _download_webpage
    res = self._download_webpage_handle(url_or_request, video_id, note, errnote, fatal, encoding=encoding, data=data, headers=headers, query=query)
  File "lib\youtube_dl\extractor\common.py", line 436, in _download_webpage_handle
    urlh = self._request_webpage(url_or_request, video_id, note, errnote, fatal, data=data, headers=headers, query=query)
  File "lib\youtube_dl\extractor\common.py", line 416, in _request_webpage
    return self._downloader.urlopen(url_or_request)
  File "lib\youtube_dl\YoutubeDL.py", line 2000, in urlopen
    req = sanitized_Request(req)
  File "lib\youtube_dl\utils.py", line 525, in sanitized_Request
    return compat_urllib_request.Request(sanitize_url(url), *args, **kwargs)
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 269, in __init__
    self.full_url = url
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 295, in full_url
    self._parse()
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python35-32\lib\urllib\request.py", line 324, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'
 (caused by ValueError("unknown url type: '/yts/jsbin/player-en_US-vflV3n15C/base.js'",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py:1994> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "C:\Users\Tony\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py", line 2027, in queue_manager
    song = await self._play(sid, url)
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py", line 796, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py", line 600, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py", line 252, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```

I tried upgrading youtube_dl, uninstall and reinstall discord.py in git bash suggested from previous posts but the error still came up. Thanks.

**Comment by palmtree5** [comment]
It's an upstream issue with youtube-dl. https://github.com/rg3/youtube-dl/pull/11892

**Comment by tonytej** [comment]
People reported that this code fixes the youtube_dl error but how do I upgrade the one used by Red? Where do I paste the command? I pasted it on git bash but the error still persisted.
`pip install --upgrade git+git://github.com/Khang-NT/youtube-dl@master#egg=youtube-dl`

**Comment by tonytej** [comment]
I applied the fix to the youtube_dl myself but then the audio cog wont work with this error:
```
RuntimeError: You need to run `pip3 install youtube_dl`
[31/01/2017 00:29] ERROR red load_cogs 558: You need to run `pip3 install youtube_dl`
Traceback (most recent call last):
  File "red.py", line 555, in load_cogs
    owner_cog._load_cog(extension)
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\owner.py", line 798, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib\discord\ext\commands\bot.py", line 740, in load_extension
    lib.setup(self)
  File "C:\Users\Tony\Documents\Red-DiscordBot\cogs\audio.py", line 2186, in setup
    raise RuntimeError("You need to run `pip3 install youtube_dl`")
RuntimeError: You need to run `pip3 install youtube_dl`

Failed to load: cogs.audio
```

I guess I should wait until the fix is merged.

**Comment by ghost** [comment]
go here : https://github.com/user890104/youtube-dl/releases/tag/2017.01.31-user890104
download the source 
take the "youtube_dl" folder and replace the one you already have in the red/lib/ folder with the new one, works fine for me

**Comment by abdiuhawiudahiu** [comment]
> go here : https://github.com/user890104/youtube-dl/releases/tag/2017.01.31-user890104
download the source
take the "youtube_dl" folder and replace the one you already have in the red/lib/ folder with the new one, works fine for me

link doesn't work

**Comment by Twentysix26** [comment]
Should be fine with the latest youtube_dl

**Comment by Jan200101** [comment]
Its fine for me already and youtube-dl functions normal again 👍

**Comment by abdiuhawiudahiu** [comment]
nvm its fixed for me now, thanks!

**Comment by Kowlin** [comment]
This issue seems to be be resolved with the merge of https://github.com/rg3/youtube-dl/commit/3c90cc8b6fc069930264b41f5505dc34c1077442.
