### ISSUE TITLE
[Installing error] Multidict

### ISSUE THREAD

**Issue by Md6989** [Cog-Creators/Red-DiscordBot#607]
Anyone can help me please.

Installing collected packages: pip, chardet, multidict, async-timeout, aiohttp, websockets, six, pycparser, cffi, PyNaCl, discord.py, youtube-dl, requests, imgurpython
  Running setup.py install for chardet ... done
  Running setup.py install for multidict ... error
Exception:
Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\compat\__init__.py", line 73, in console_to_str
    return s.decode(sys.__stdout__.encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 68: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\basecommand.py", line 215, in main
    status = self.run(options, args)
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\commands\install.py", line 342, in run
    prefix=options.prefix_path,
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_set.py", line 784, in install
    **kwargs
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\req\req_install.py", line 878, in install
    spinner=spinner,
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\utils\__init__.py", line 676, in call_subprocess
    line = console_to_str(proc.stdout.readline())
  File "C:\Users\***\AppData\Local\Programs\Python\Python36\lib\site-packages\pip\compat\__init__.py", line 75, in console_to_str
    return s.decode('utf_8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 68: invalid continuation byte

An error occured and the requirements setup might not be completed. Consult the docs.

I can't find the docs. Thanks for your help.

**Comment by palmtree5** [comment]
Use 3.5 instead

**Comment by Md6989** [comment]
Thank a lot for your fast answer, IT' work. 😄
