### ISSUE TITLE
Unable to load downloader

### ISSUE THREAD

**Issue by IReficul** [Cog-Creators/Red-DiscordBot#6091]
### What Red version are you using?

3.4.19

### Cog name

Downloader

### Command name

.cog

### What did you expect to happen?

I expected the cog Downloader to load.

### What actually happened?

The cog downloader does not initialize and I get the following message: There was an error during Downloader's initialization. Check logs for more information.

logs:

```
Apr 20 13:21:13 lyseocraft python[1623]: /home/ubuntu/redenv/lib/python3.9/site-packages/pkg_resources/__init__.py:121: DeprecationWarning: pkg_resources is deprecated as an API
Apr 20 13:21:13 lyseocraft python[1623]:   warnings.warn("pkg_resources is deprecated as an API", DeprecationWarning)
Apr 20 13:21:14 lyseocraft python[1623]: [2023-04-20 13:21:14] [INFO] red: Loading packages...
Apr 20 13:21:14 lyseocraft python[1623]: [2023-04-20 13:21:14] [INFO] red: Loaded packages: audio, alias, admin, downloader
Apr 20 13:21:14 lyseocraft python[1623]: [2023-04-20 13:21:14] [ERROR] red.downloader: An unexpected error occurred during Downloader's initialization.
Apr 20 13:21:14 lyseocraft python[1623]: Traceback (most recent call last):
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/downloader.py", line 113, in initialize
Apr 20 13:21:14 lyseocraft python[1623]:     await self._repo_manager.initialize()
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/repo_manager.py", line 1022, in initialize
Apr 20 13:21:14 lyseocraft python[1623]:     await self._load_repos(set_repos=True)
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/repo_manager.py", line 1218, in _load_repos
Apr 20 13:21:14 lyseocraft python[1623]:     ret[folder.name] = await Repo.from_folder(folder, branch)
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/repo_manager.py", line 1002, in from_folder
Apr 20 13:21:14 lyseocraft python[1623]:     repo.url = await repo.current_url()
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/repo_manager.py", line 770, in current_url
Apr 20 13:21:14 lyseocraft python[1623]:     p = await self._run(git_command)
Apr 20 13:21:14 lyseocraft python[1623]:   File "/home/ubuntu/redenv/lib/python3.9/site-packages/redbot/cogs/downloader/repo_manager.py", line 560, in _run
Apr 20 13:21:14 lyseocraft python[1623]:     p: CompletedProcess = await asyncio.get_running_loop().run_in_executor(
Apr 20 13:21:14 lyseocraft python[1623]:   File "/usr/lib/python3.9/concurrent/futures/thread.py", line 58, in run
Apr 20 13:21:14 lyseocraft python[1623]:     result = self.fn(*self.args, **self.kwargs)
Apr 20 13:21:14 lyseocraft python[1623]:   File "/usr/lib/python3.9/subprocess.py", line 505, in run
Apr 20 13:21:14 lyseocraft python[1623]:     with Popen(*popenargs, **kwargs) as process:
Apr 20 13:21:14 lyseocraft python[1623]:   File "/usr/lib/python3.9/subprocess.py", line 951, in __init__
Apr 20 13:21:14 lyseocraft python[1623]:     self._execute_child(args, executable, preexec_fn, close_fds,
Apr 20 13:21:14 lyseocraft python[1623]:   File "/usr/lib/python3.9/subprocess.py", line 1821, in _execute_child
Apr 20 13:21:14 lyseocraft python[1623]:     raise child_exception_type(errno_num, err_msg, err_filename)
Apr 20 13:21:14 lyseocraft python[1623]: FileNotFoundError: [Errno 2] No such file or directory: 'git'
Apr 20 13:21:15 lyseocraft python[1623]: [2023-04-20 13:21:15] [INFO] red: Connected to Discord. Getting ready...
```

### How can we reproduce this error?

1. Run command .load downloader
2. Run .cog

**Comment by Jackenmen** [comment]
If you need help using Red, you should ask on our support server at [discord.gg/red](https://discord.gg/red).
