### ISSUE TITLE
Unban sends a attributeerror

### ISSUE THREAD

**Issue by ltzmax** [Cog-Creators/Red-DiscordBot#6219]
### What Red version are you using?

3.5.3

### Cog name

Mod

### Command name

unban

### What did you expect to happen?

To unban without sending a error.

### What actually happened?

```py
Exception in command 'unban'
Traceback (most recent call last):
  File "/home/redbot/.pyenv/versions/3.11.2/envs/redbot-3.5/lib/python3.11/site-packages/discord/ext/commands/core.py", line 235, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redbot/Ballsdex-redbot/cogs/CogManager/cogs/mod/mod.py", line 704, in unban
    if await self._config.guild(guild).reinvite_on_unban():
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redbot/.pyenv/versions/3.11.2/envs/redbot-3.5/lib/python3.11/site-packages/redbot/core/config.py", line 364, in __getattr__
    raise AttributeError("'{}' is not a valid registered Group or value.".format(item))
AttributeError: 'reinvite_on_unban' is not a valid registered Group or value.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/redbot/.pyenv/versions/3.11.2/envs/redbot-3.5/lib/python3.11/site-packages/discord/ext/commands/bot.py", line 1350, in invoke
    await ctx.command.invoke(ctx)
  File "/home/redbot/.pyenv/versions/3.11.2/envs/redbot-3.5/lib/python3.11/site-packages/discord/ext/commands/core.py", line 1029, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/redbot/.pyenv/versions/3.11.2/envs/redbot-3.5/lib/python3.11/site-packages/discord/ext/commands/core.py", line 244, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'reinvite_on_unban' is not a valid registered Group or value.
```

### How can we reproduce this error?

1. unban <user>
2. Wait until it send `Unbanned that user from this server.`
3. Check traceback

**Comment by Jackenmen** [comment]
Is it possible that you didn't resolve conflicts properly? I see this config value here:
https://github.com/Cog-Creators/Red-DiscordBot/blob/93b51acf310419440caecbd4d35fce7e51ff47b8/redbot/cogs/mod/mod.py#L57

**Comment by Jackenmen** [comment]
Actually, it looks like you're not using the core cog, the path shows that you override it with 3rd-party one.

**Comment by ltzmax** [comment]
Yeah its not a fork lmao, i missed that it's from a cog. sorry! :P
