### ISSUE TITLE
[Audio] Something broke when playing the track on Lavalink 3.7.11+red.3

### ISSUE THREAD

**Issue by 1Pac0** [Cog-Creators/Red-DiscordBot#6479]
# ***If you are experiencing issues with Audio, please read***
*This issue has been patched in `3.5.14`. New issues with Audio are tracked in #4505. If you need additional help, please feel free to join our support server at https://discord.gg/red*

---

### What Red version are you using?

3.5.13

### What were you trying to do?

Use the !Play command to play music from youtube

### What did you expect to happen?

Hear the music from Youtube

### What actually happened?

Track Error
Something broke when playing the track.

### How can we reproduce this error?

1.!play <youtube link>
2.
3.
...

**Comment by athompson-hoho** [comment]
I am also experiencing this issue. I don't know if it's the same as the OP but my spring.log files show the following

`2024-11-23 20:19:34.056  INFO 150 --- [XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "play", "guildId": "326259390372118541", "track": "QAAAnwIAOlRoZSBFbXB0aW5lc3MgTWFjaGluZSAoT2ZmaWNpYWwgTXVzaWMgVmlkZW8pIC0gTGlua2luIFBhcmsAC0xpbmtpbiBQYXJrAAAAAAADESgAC1NSWEg5QWJUMjgwAAEAK2h0dHBzOi8vd3d3LnlvdXR1YmUuY29tL3dhdGNoP3Y9U1JYSDlBYlQyODAAB3lvdXR1YmUAAAAAAAAAAA==", "noReplace": false, "startTime": "0", "pause": false}
2024-11-23 20:19:34.196  INFO 150 --- [XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "voiceUpdate", "guildId": "326259390372118541", "sessionId": "6d6e28956f0e34fae7824a70cf105d9f", "event": {"token": "c2230f5f627ae239", "guild_id": "326259390372118541", "endpoint": "us-south8917.discord.media:443"}}
2024-11-23 20:19:35.662  INFO 150 --- [lava-daemon-pool-playback-1-thread-1] d.l.y.http.YoutubeAccessTokenTracker     : Updating YouTube visitor id succeeded, new one is CgtJSWRnd1pjdzJ1byi3moq6BjIKCgJVUxIEGgAgUjoMCAEg3OqL7PCmo6Fn, next update will be after 600 seconds.
2024-11-23 20:19:35.937 ERROR 150 --- [lava-daemon-pool-playback-1-thread-1] c.s.d.l.t.p.LocalAudioTrackExecutor      : Error in playback of SRXH9AbT280

com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
        at com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[lavaplayer-1.5.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:113) ~[lavaplayer-1.5.4.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$1(DefaultAudioPlayerManager.java:324) ~[lavaplayer-1.5.4.jar!/:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:840) ~[na:na]
        Suppressed: com.sedmelluq.discord.lavaplayer.tools.exception.EnvironmentInformation:
  lavaplayer.version: 1.5.4
  os.arch: amd64
  os.name: Linux
  os.version: 6.8.0-49-generic
  java.vendor: Debian
  java.version: 17.0.13
  java.runtime.version: 17.0.13+11-Debian-2deb12u1
  java.vm.version: 17.0.13+11-Debian-2deb12u1
Caused by: java.io.IOException: Invalid status code for player api response: 403
        at com.sedmelluq.discord.lavaplayer.tools.io.HttpClientTools.assertSuccessWithContent(HttpClientTools.java:154) ~[lavaplayer-1.5.4.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadJsonResponse(NonMusicClient.java:58) ~[youtube-plugin-1.7.2.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.NonMusicClient.loadTrackInfoFromInnertube(NonMusicClient.java:97) ~[youtube-plugin-1.7.2.jar!/:na]
        at dev.lavalink.youtube.clients.skeleton.StreamingNonMusicClient.loadFormats(StreamingNonMusicClient.java:35) ~[youtube-plugin-1.7.2.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.loadBestFormatWithUrl(YoutubeAudioTrack.java:188) ~[youtube-plugin-1.7.2.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:114) ~[youtube-plugin-1.7.2.jar!/:na]
        at dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:72) ~[youtube-plugin-1.7.2.jar!/:na]
        at com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:101) ~[lavaplayer-1.5.4.jar!/:na]
        ... 4 common frames omitted

2024-11-23 20:19:35.962  INFO 150 --- [XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "326259390372118541"}
2024-11-23 20:19:36.132  INFO 150 --- [XNIO-1 I/O-5] lavalink.server.io.SocketServer          : {"op": "stop", "guildId": "326259390372118541"}`

**Comment by ymt0220** [comment]
I have the same problem

**Comment by Flame442** [comment]
Known issues with Audio are tracked in #4505. This issue is one of our known issues that we plan on patching in the next release. **You can follow the instructions in that issue in the meantime**, though they are more complicated than a bot update. If you need additional help, please feel free to join our support server at https://discord.gg/red

**Comment by alex-huff** [comment]
> ```
> Download or wget this application.yml file: https://gist.githubusercontent.com/aikaterna/4227dbf1c45640c7ee57cbe36e85ea53/raw/1b1c0f79350e69bbb1cbfd9c1301cc2ef930fc2d/application.yml
> ```

This `application.yml` did not fix the issue for me but the one pinned in the Discord did: `https://gist.githubusercontent.com/aikaterna/cb32441fba460ebf09567b8f718f9224/raw/bbe378b25944a3549d17ba16ebddfe3c4ca7ec12/application.yml`

**Comment by Cryztalzone** [comment]
I have had the same problem for about two weeks, `Invalid status code for player api response: 403`.
With Red running on Docker none of the provided application.yml seems to fix it, but when checking the `spring.log` I saw
```
YOUTUBE-SOURCE VERSION 1.10.2 AVAILABLE
https://github.com/lavalink-devs/youtube-source/releases/tag/1.10.2
Update to ensure the YouTube source remains operational!
```
so I did just that. Download the `youtube-plugin-1.10.2.jar` from [here](https://github.com/lavalink-devs/youtube-source/releases/tag/1.10.2) and replace the file in `/data/cogs/Audio/plugins`. You need to rename the `youtube-plugin-1.10.2.jar` to `youtube-plugin-1.7.2.jar` because otherwise, it seems to be automatically replaced by the included version which caused the error in the first place. Restart the bot and (hopefully) enjoy playing YouTube Videos!

**Comment by Flame442** [comment]
The application.yml is supposed to change the version, but it can only be modified if you use an unmanaged node. Docker is not a supported environment, so I'm not sure how it can be set up to be unmanaged to be able to apply the fix.

**Comment by b1nary-b0b** [comment]
I am facing the same issue with API Error 403 on a dockerized env.

**Comment by hungrybeetle-bit** [comment]
I was able to do this in docker by using the `fredboat/lavalink:v3-legacy` image and mounting the file to `/opt/Lavalink/application.yml`

**Comment by tatsudo** [comment]
> I have had the same problem for about two weeks, `Invalid status code for player api response: 403`. With Red running on Docker none of the provided application.yml seems to fix it, but when checking the `spring.log` I saw
> 
> ```
> YOUTUBE-SOURCE VERSION 1.10.2 AVAILABLE
> https://github.com/lavalink-devs/youtube-source/releases/tag/1.10.2
> Update to ensure the YouTube source remains operational!
> ```
> 
> so I did just that. Download the `youtube-plugin-1.10.2.jar` from [here](https://github.com/lavalink-devs/youtube-source/releases/tag/1.10.2) and replace the file in `/data/cogs/Audio/plugins`. You need to rename the `youtube-plugin-1.10.2.jar` to `youtube-plugin-1.7.2.jar` because otherwise, it seems to be automatically replaced by the included version which caused the error in the first place. Restart the bot and (hopefully) enjoy playing YouTube Videos!


For me youtube-plugin-1.10.2 didn't solve the problem, but youtube-plugin-1.11.1.jar from [here](https://github.com/lavalink-devs/youtube-source/releases/tag/1.11.1) did.

**Comment by vChroniq** [comment]
Docker is not a part of the supported platforms.

**Comment by MrrZed0** [comment]
i got red all set up and the audio was working great till one day i am getting the same errors, it just cant play nothing, i thought maybe my install was bad so i did a clean install but same thing, i've tried to manuly update the files myself the lavalink and youtube.jar but still not wokring

**Comment by Flame442** [comment]
@MrrZed0 The particular error described in this issue has already been resolved, but there is a new bug with YouTube playback as of April 22, 2025. There is not currently a fix, but one is currently being developed. YouTube playback breaks frequently, so we try to keep a status page in #4505 that you can check to see if other people are having issues or if a patch has already been released. You can also "watch" this repo to get an email when new updates are released. Feel free to join [our support server](https://discord.gg/red) if you need additional assistance.

**Comment by MrrZed0** [comment]
> [@MrrZed0](https://github.com/MrrZed0) The particular error described in this issue has already been resolved, but there is a new bug with YouTube playback as of April 22, 2025. There is not currently a fix, but one is currently being developed. YouTube playback breaks frequently, so we try to keep a status page in [#4505](https://github.com/Cog-Creators/Red-DiscordBot/issues/4505) that you can check to see if other people are having issues or if a patch has already been released. You can also "watch" this repo to get an email when new updates are released. Feel free to join [our support server](https://discord.gg/red) if you need additional assistance.

alright good to know, i though maybe i was doing something wrong with the install or setting the bot up, ill keep a watch out thanks for the information
