### ISSUE TITLE
Owner Problems?

### ISSUE THREAD

**Issue by haaddaa1** [Cog-Creators/Red-DiscordBot#650]
Ignoring exception in message
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/ext/commands/bot.py", line 252, in _run_extra
    yield from coro(*args, **kwargs)
  File "/Users/ /Desktop/G/Red-DiscordBot/cogs/selfembed.py", line 33, in on_message
    if self.eee["toggle"] and author.id == self.bot.owner.user.id:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 296, in __getattr__
    raise AttributeError(msg.format(self.__class__, name))
AttributeError: '<class '__main__.Bot'>' object has no attribute 'owner'
**
NEED HELP**

**Comment by palmtree5** [comment]
https://github.com/Nerdietony/Nerdie-Cogs

Did you set the owner using `aself, setowner`?

**Comment by arrowetyt** [comment]
im on my other acc and no the only time i used was today because it kept saying owner something and so i did set owner

**Comment by Twentysix26** [comment]
`Bot.owner` is not even a thing. Badly coded cog.

**Comment by arrowetyt** [comment]
then what do i do?

**Comment by Twentysix26** [comment]
Contact the author. Open an issue in their repo. This is for standard Red not 3rd party content.

**Comment by palmtree5** [comment]
https://github.com/Nerdietony/Nerdie-Cogs
Open an issue there
