### ISSUE TITLE
[Downloader] Sporadic issue with [p]cog update

### ISSUE THREAD

**Issue by Twentysix26** [Cog-Creators/Red-DiscordBot#660]
```
Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(args, **kwargs)
  File "C:\Users\bot\Downloads\X\cogs\downloader.py", line 243, in update
    name, updates, oldhash = await f
  File "C:\Users\bot\AppData\Local\Programs\Python\Python36\lib\asyncio\tasks.py", line 452, in _wait_for_one
    return f.result()  # May raise f.exception().
  File "C:\Users\bot\AppData\Local\Programs\Python\Python36\lib\concurrent\futures\thread.py", line 55, in run
    result = self.fn(self.args, **self.kwargs)
  File "C:\Users\bot\Downloads\X\cogs\downloader.py", line 615, in update_repo
    status, cogpath = f.split('\t')
ValueError: too many values to unpack (expected 2)
```

Reported by a user. Seems to cease after a restart.

**Comment by calebj** [comment]
Please have them test c2938c51122f76c306a689811b9bc395c8cd3cb1 and report back.
