### ISSUE TITLE
Cant start the bot since today :/ Error attatched

### ISSUE THREAD

**Issue by typho0nz** [Cog-Creators/Red-DiscordBot#733]
Cant start the bot since today :/

```
Logging into Discord...
[23/04/2017 21:23] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "C:\Program Files (x86)\python\lib\asyncio\base_events.py", line 342, in run_until_complete
    return future.result()
  File "C:\Program Files (x86)\python\lib\asyncio\futures.py", line 274, in result
    raise self._exception
  File "C:\Program Files (x86)\python\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(value)
  File "red.py", line 603, in main
    yield from bot.connect()
  File "lib\discord\client.py", line 444, in connect
    self.ws = yield from DiscordWebSocket.from_client(self)
  File "lib\discord\gateway.py", line 197, in from_client
    timeout=60, loop=client.loop)
  File "C:\Program Files (x86)\python\lib\asyncio\tasks.py", line 365, in wait_for
    fut = ensure_future(fut, loop=loop)
  File "C:\Program Files (x86)\python\lib\asyncio\tasks.py", line 531, in ensure_future
    raise TypeError('A Future or coroutine is required')
TypeError: A Future or coroutine is required
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at E:\Program Files (x86)\Red\Red-DiscordBot\cogs\audio.py:2103> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at E:\Program Files (x86)\Red\Red-DiscordBot\cogs\audio.py:1976> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at E:\Program Files (x86)\Red\Red-DiscordBot\cogs\audio.py:2107> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_scheduler() running at E:\Program Files (x86)\Red\Red-DiscordBot\cogs\audio.py:1931> wait_for=<Future pending cb=[Task._wakeup()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at E:\Program Files (x86)\Red\Red-DiscordBot\cogs\streams.py:517> wait_for=<Future pending cb=[Task._wakeup()]>>
Red has been terminated. Exit code: 1
Press enter to continue.
```

**Comment by palmtree5** [comment]
What version of python and what version of Windows. Also have you updated the bot/reqs recently?

**Comment by typho0nz** [comment]
- updated ~1 time a week (also tried repair/fresh install)
- latest win10 x64 creators update build (1703)
- py 3.5

**Comment by Hocheon** [comment]
+bump same problem :((

**Comment by Kowlin** [comment]
Open up a CMD and type in ``python --version``, give us that output. If its lower then 3.5.1, update Python

**Comment by typho0nz** [comment]
C:\Users\*******>python --version
Python 3.5.2

**Comment by Rapptz** [comment]
Sorry about this. It was an issue with the library. I've fixed it upstream by reverting the offending commit.

**Comment by typho0nz** [comment]
You're a GOD ;D
Working like a charm again! Thanks for your fast response!

**Comment by JeSTeRFLA** [comment]
i got the same issue and im using 3.6 and i just downloaded the bot today.

**Comment by Zephyrkul** [comment]
Are you on Windows? If so...
![](https://cdn.discordapp.com/attachments/171665724262055936/329731260949856258/36.PNG)

**Comment by JeSTeRFLA** [comment]
who the hell uses winblows anymore im on linux

**Comment by Zephyrkul** [comment]
Then I suggest opening up a new issue with the full traceback instead of randomly digging up an old, unrelated issue.

**Comment by JeSTeRFLA** [comment]
WELL i got the SAME exact error message just now

**Comment by Zephyrkul** [comment]
Extremely doubtful. Either post the full traceback in a new issue that isn't closed / unrelated, or don't expect an answer / solution.

**Comment by Kowlin** [comment]
Please open a new issue with your full traceback and other relevant information you can provide.
