### ISSUE TITLE
ERROR: Signature extraction failed

### ISSUE THREAD

**Issue by DeeJayhX** [Cog-Creators/Red-DiscordBot#737]
Something apparently changed on youtube, broke the signature extraction. Tried repair=>code, fully update redbot+requirements, still same error. Happens on .yt or .play commands.

Sometimes it works, sometimes it doesn't...

`.yt baka baka baka` works.
`.yt chinese chicken song` causes crash.

Seems random depending on search terms.

```
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib/youtube_dl/extractor/youtube.py", line 1081, in _decrypt_signature
    video_id, player_url, s
  File "lib/youtube_dl/extractor/youtube.py", line 969, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vflppxuSE/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at /servers/redbot/cogs/audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "/servers/redbot/cogs/audio.py", line 2060, in queue_manager
    song = await self._play(sid, url)
  File "/servers/redbot/cogs/audio.py", line 810, in _play
    song = await self._guarantee_downloaded(server, url)
  File "/servers/redbot/cogs/audio.py", line 606, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "/servers/redbot/cogs/audio.py", line 256, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'
```

**Comment by Zephyrkul** [comment]
The popular Youtube downloading tool/library used by many bots (including Red) is experiencing difficulties at the moment. Sadly, there is nothing we can do. please be patient. Until it comes back up, you can always use local playlists: https://twentysix26.github.io/Red-Docs/red_audio/

**Comment by DeeJayhX** [comment]
Thanks, sad to hear, but glad to know what's going on.

**Comment by Zephyrkul** [comment]
Just thought I'd let you know - looks like it's been fixed, update your bot and all its requirements (option 1 of the launcher's Update menu) and it should work now.

**Comment by DeeJayhX** [comment]
@zephyrkul It was and I did and it is fixed. Thank you though! Super considerate of you!
