### ISSUE TITLE
Interesting Error about Bitness..

### ISSUE THREAD

**Issue by gnarf** [Cog-Creators/Red-DiscordBot#745]
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.

<details>

```

==========================
Red Discord Bot - Launcher
==========================

1. Run Red /w autorestart in case of issues
2. Run Red
3. Update
4. Install requirements
5. Maintenance (repair, reset...)

0. Quit
> 1
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
[01/05/2017 22:27] ERROR red load_cogs 573: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "/mnt/Red-DiscordBot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/mnt/Red-DiscordBot/cogs/audio.py", line 2226, in setup
    "Your opus library's bitness must match your python installation's"
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
ImgurClientError: JSON decoding of response failed.
[01/05/2017 22:27] ERROR red load_cogs 573: JSON decoding of response failed.
Traceback (most recent call last):
  File "lib/imgurpython/client.py", line 156, in make_request
    response_data = response.json()
  File "lib/requests/models.py", line 866, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/local/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/local/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/local/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "red.py", line 570, in load_cogs
    owner_cog._load_cog(extension)
  File "/mnt/Red-DiscordBot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/mnt/Red-DiscordBot/cogs/image.py", line 168, in setup
    bot.add_cog(Image(bot))
  File "/mnt/Red-DiscordBot/cogs/image.py", line 22, in __init__
    self.imgur = ImgurClient(CLIENT_ID, CLIENT_SECRET)
  File "lib/imgurpython/client.py", line 85, in __init__
    self.credits = self.get_credits()
  File "lib/imgurpython/client.py", line 94, in get_credits
    return self.make_request('GET', 'credits', None, True)
  File "lib/imgurpython/client.py", line 158, in make_request
    raise ImgurClientError('JSON decoding of response failed.')
imgurpython.helpers.error.ImgurClientError: JSON decoding of response failed.

Failed to load: cogs.audio cogs.image

Logging into Discord...
Login successful. (2.186829ms)

```

</details>

**Comment by ghost** [comment]
I assume you're using a 32 bit version of Opus and 64 bit version of Python 3? Try downloading the 64 bit version of Opus, see similar issue here: https://github.com/Twentysix26/Red-DiscordBot/issues/90

**Comment by tekulvw** [comment]
^
