### ISSUE TITLE
Audio not Work

### ISSUE THREAD

**Issue by D4rk56** [Cog-Creators/Red-DiscordBot#748]
```
[05/05/2017 00:30] ERROR red on_command_error 369: Exception in command 'reload'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/opt/Red-DiscordBot/cogs/owner.py", line 149, in _reload
    self._load_cog(module)
  File "/opt/Red-DiscordBot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/opt/Red-DiscordBot/cogs/audio.py", line 2226, in setup
    "Your opus library's bitness must match your python installation's"
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
```

**Comment by palmtree5** [comment]
ok, what distro are you using?

**Comment by D4rk56** [comment]
Debian 8

**Comment by Overlordmittenz** [comment]
Also having this issue. I think it has something to do with the new Youtube update? None of the music bots are working.

**Comment by Overlordmittenz** [comment]
I'm getting 

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib\youtube_dl\extractor\youtube.py", line 1070, in _decrypt_signature
    video_id, player_url, s
  File "lib\youtube_dl\extractor\youtube.py", line 958, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
youtube_dl.utils.ExtractorError: Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl05vreg/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError("Cannot identify player 'https://www.youtube.com/yts/jsbin/player-vfl05vreg/en_US/base.js'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Administrator\Desktop\Corazon.current\cogs\audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Administrator\Desktop\Corazon.current\cogs\audio.py", line 2060, in queue_manager
    song = await self._play(sid, url)
  File "C:\Users\Administrator\Desktop\Corazon.current\cogs\audio.py", line 810, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Users\Administrator\Desktop\Corazon.current\cogs\audio.py", line 606, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Users\Administrator\Desktop\Corazon.current\cogs\audio.py", line 256, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'

**Comment by palmtree5** [comment]
Update your bot and all its reqs.

**Comment by D4rk56** [comment]
After update, same error.

**Comment by skeith** [comment]
Can you post the result of this bash command : `pip freeze | grep youtube-dl` or `pip3 freeze | grep youtube-dl`

**Comment by D4rk56** [comment]
root@nsxx : ~# pip freeze | grep youtube-dl
youtube-dl==2017.1.24

**Comment by palmtree5** [comment]
That version of youtube-dl is out of date

**Comment by D4rk56** [comment]
After update youtube-dl==**2017.5.1**

`[05/05/2017 20:46] ERROR red on_command_error 369: Exception in command 'reload'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/opt/Red-DiscordBot/cogs/owner.py", line 149, in _reload
    self._load_cog(module)
  File "/opt/Red-DiscordBot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 738, in load_extension
    lib.setup(self)
  File "/opt/Red-DiscordBot/cogs/audio.py", line 2226, in setup
    "Your opus library's bitness must match your python installation's"
RuntimeError: Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.
`

**Comment by skeith** [comment]
`Your opus library's bitness must match your python installation's bitness. They both must be either 32bit or 64bit.`

Pretty straightforward from there

**Comment by D4rk56** [comment]
Where to find this for a linux distribution?

**Comment by palmtree5** [comment]
Follow these instructions: http://twentysix26.github.io/Red-Docs/red_install_debian/

**Comment by D4rk56** [comment]
Thank you, it works! After install pre-requirements.
`apt-get install build-essential libssl-dev libffi-dev git ffmpeg libopus-dev unzip -y`

Close issue.
