### ISSUE TITLE
Red Bot launch Failing after every PC restart

### ISSUE THREAD

**Issue by Zenreality** [Cog-Creators/Red-DiscordBot#751]
Starting Red...
Traceback (most recent call last):
  File "red.py", line 21, in <module>
    from cogs.utils.settings import Settings
ImportError: No module named 'cogs'
Red has been terminated. Exit code: 1

C:\Users\Galvatron\Desktop\Red-DiscordBot-develop>pause
Press any key to continue . . .

Anyway around this? It is rather annoying.

**Comment by Zenreality** [comment]
I literally have to Re-do the installation process every boot up to get it to work.

**Comment by Twentysix26** [comment]
Install by following the [windows guide](https://twentysix26.github.io/Red-Docs/red_install_windows/).

**Comment by Zenreality** [comment]
I have.

**Comment by Zenreality** [comment]
the only way im getting it to work, is to delete red and reinstall everything.  Factory reset and repair options are failing and not executing.

**Comment by Twentysix26** [comment]
I can tell by what you posted that you have not installed with git.

**Comment by Zenreality** [comment]
I did the Git Bash Here and entered the command.

**Comment by Zenreality** [comment]
Galvatron@Galvatron-PC MINGW32 ~/Desktop/Red-DiscordBot (develop)
$ git clone -b develop --single-branch https://github.com/Twentysix26/Red-DiscordBot.git Red-DiscordBot
Cloning into 'Red-DiscordBot'...
remote: Counting objects: 2540, done.
remote: Total 2540 (delta 0), reused 0 (delta 0), pack-reused 2540
Receiving objects: 100% (2540/2540), 1.22 MiB | 0 bytes/s, done.
Resolving deltas: 100% (1670/1670), done.

**Comment by tekulvw** [comment]
are you running the batfile from cmd?

**Comment by Kowlin** [comment]
Closing due to inactivity. Please open a new issue if you still have this problem.

**Comment by LuxNotAvailable** [comment]
Has anyone solved this yet?
I'm having the same problem

Traceback (most recent call last):
  File "red.py", line 12, in <module>
    from discord.ext import commands
  File "lib\discord\__init__.py", line 20, in <module>
    from .client import Client, AppInfo, ChannelPermissions
  File "lib\discord\client.py", line 42, in <module>
    from .voice_client import VoiceClient
  File "lib\discord\voice_client.py", line 43, in <module>
    import websockets
  File "lib\websockets\__init__.py", line 3, in <module>
    from .client import *
  File "lib\websockets\client.py", line 12, in <module>
    from .protocol import CONNECTING, OPEN, WebSocketCommonProtocol
  File "lib\websockets\protocol.py", line 17, in <module>
    from .compatibility import asyncio_ensure_future
  File "lib\websockets\compatibility.py", line 9
    asyncio_ensure_future = asyncio.async           # Python < 3.5
                                        ^

I can figure out why it does this and no one else has documented anything about it
any help?

**Comment by Tobotimus** [comment]
@Ryanthekid22 What version of Python are you using?

**Comment by LuxNotAvailable** [comment]
Fixed. I was using the wrong version of Python, turns out i was on 3.7 not 3.5
