### ISSUE TITLE
Song request error

### ISSUE THREAD

**Issue by Zenreality** [Cog-Creators/Red-DiscordBot#762]
Bot has been working flawlessly and this morning after boot up yt request have not been working.  I did the yt-dl pip update and still does not work.

Here is the error I am receiving.

ERROR: Signature extraction failed: Traceback (most recent call last):
  File "lib\youtube_dl\extractor\youtube.py", line 1162, in _decrypt_signature
    video_id, player_url, s
  File "lib\youtube_dl\extractor\youtube.py", line 1085, in _extract_signature_function
    cache_res = res(test_string)
  File "lib\youtube_dl\extractor\youtube.py", line 1138, in <lambda>
    return lambda s: initial_function([s])
  File "lib\youtube_dl\jsinterp.py", line 254, in resf
    res, abort = self.interpret_statement(stmt, local_vars)
  File "lib\youtube_dl\jsinterp.py", line 55, in interpret_statement
    v = self.interpret_expression(expr, local_vars, allow_recursion)
  File "lib\youtube_dl\jsinterp.py", line 211, in interpret_expression
    raise ExtractorError('Unsupported JS expression %r' % expr)
youtube_dl.utils.ExtractorError: Unsupported JS expression 'oE["do"](a,67)'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError('Unsupported JS expression \'oE["do"](a,67)\'; please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.',)); please report this issue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to call youtube-dl with the --verbose flag and include its complete output.
Task exception was never retrieved
future: <Task finished coro=<Audio.queue_manager() done, defined at C:\Users\Galvatron\Downloads\Red-DiscordBot-develop\Red-DiscordBot-develop\cogs\audio.py:2027> exception=AttributeError("'NoneType' object has no attribute 'duration'",)>
Traceback (most recent call last):
  File "C:\Users\Galvatron\AppData\Local\Programs\Python\Python35-32\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "C:\Users\Galvatron\Downloads\Red-DiscordBot-develop\Red-DiscordBot-develop\cogs\audio.py", line 2060, in queue_manager
    song = await self._play(sid, url)
  File "C:\Users\Galvatron\Downloads\Red-DiscordBot-develop\Red-DiscordBot-develop\cogs\audio.py", line 810, in _play
    song = await self._guarantee_downloaded(server, url)
  File "C:\Users\Galvatron\Downloads\Red-DiscordBot-develop\Red-DiscordBot-develop\cogs\audio.py", line 606, in _guarantee_downloaded
    self.downloaders[server.id].duration_check()
  File "C:\Users\Galvatron\Downloads\Red-DiscordBot-develop\Red-DiscordBot-develop\cogs\audio.py", line 256, in duration_check
    log.debug("duration {} for songid {}".format(self.song.duration,
AttributeError: 'NoneType' object has no attribute 'duration'

**Comment by Stylite** [comment]
ytdl is down

**Comment by Zenreality** [comment]
Oh, thank you so much!

**Comment by Zenreality** [comment]
Any updates from them?

**Comment by Kowlin** [comment]
```The popular Youtube downloading tool/library used by many bots is experiencing difficulties at the moment. Sadly, there is nothing we can do. please be patient. Until it comes back up, you can always use local playlists. type >audio in this channel to find out more.```

Quoted from the bot on our support server, expect a fix from the Ytdl team in a day or 2. And update your requirements when that happens.

*I will keep this issue open until this is resolved*

**Comment by Kowlin** [comment]
This has now been resolved, the Ytdl team pushed out an update. Update the requirements from the launcher or your favorite method of updating ;)
