### ISSUE TITLE
Bot can not load a new cog. Please help me

### ISSUE THREAD

**Issue by ghost** [Cog-Creators/Red-DiscordBot#803]
Cog was found and possibly loaded but something went wrong. Check your console or logs for more information.

**Comment by Twentysix26** [comment]
You provided zero details about your issue. Post errors, what you're trying to load, etc

**Comment by ghost** [comment]
[09/06/2017 17:27] ERROR owner load 73: extension does not have a setup function
Traceback (most recent call last):
  File "/home/pi/red-discordbot/cogs/owner.py", line 64, in load
    self._load_cog(module)
  File "/home/pi/red-discordbot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 736, in load_extension
    raise discord.ClientException('extension does not have a setup function')
discord.errors.ClientException: extension does not have a setup function
Traceback (most recent call last):
  File "/home/pi/red-discordbot/cogs/owner.py", line 64, in load
    self._load_cog(module)
  File "/home/pi/red-discordbot/cogs/owner.py", line 947, in _load_cog
    self.bot.load_extension(mod_obj.__name__)
  File "lib/discord/ext/commands/bot.py", line 736, in load_extension
    raise discord.ClientException('extension does not have a setup function')
discord.errors.ClientException: extension does not have a setup function

**Comment by ghost** [comment]
error on the menu and the Recyclingplant cog

**Comment by Twentysix26** [comment]
This repository covers core functionalities and the default cogs. Those are 3rd party ones and you should ask the individual authors about them. I can tell you that "menu" is not supposed to be used and it's just there as an example though.

**Comment by Kowlin** [comment]
@SnappyDragon18 that's your cog. Have fun with making a ``__init__``.

**Comment by ghost** [comment]
oh, thank you
