### ISSUE TITLE
PyNaCl required to use voice.

### ISSUE THREAD

**Issue by JakeyPrime** [Cog-Creators/Red-DiscordBot#818]
I keep getting the following error after months of no problems on 200+ servers using the bot. Nothing has changed, besides pulling from source a few times and updating, then I suddenly started getting this problem, and music wont play.
` ERROR red on_command_error 369: Exception in command 'play'
Traceback (most recent call last):
  File "lib/discord/ext/commands/core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/jacobmcilravey/JakeBot2/cogs/audio.py", line 1361, in play
    await self._join_voice_channel(voice_channel)
  File "/home/jacobmcilravey/JakeBot2/cogs/audio.py", line 644, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "/usr/lib/python3.5/asyncio/tasks.py", line 392, in wait_for
    return fut.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "lib/discord/client.py", line 3201, in join_voice_channel
    voice = VoiceClient(**kwargs)
  File "lib/discord/voice_client.py", line 217, in __init__
    raise RuntimeError("PyNaCl library needed in order to use voice")
RuntimeError: PyNaCl library needed in order to use voice
`
Not sure what I'm doing wrong,
I have libsodium and pynacl installed. I've tried reinstalling both a few times, as well as disabling all of my cogs, just in the rare case that's the problem. Music is very important to me, and would love to get it solved.

Many thanks in advance!

**Comment by Twentysix26** [comment]
Have you tried reinstalling "basic + audio" requirements from the launcher?

**Comment by JakeyPrime** [comment]
Yes I have, it says that all the dependencies are satisfied.

**Comment by tekulvw** [comment]
Have you resolved this?

**Comment by JakeyPrime** [comment]
Nope. Still having issues.

**Comment by tekulvw** [comment]
Okay please come to the support server and we'll get it fixed there.
