### ISSUE TITLE
Bot not working after one song

### ISSUE THREAD

**Issue by Heronickproductions** [Cog-Creators/Red-DiscordBot#86]
I have a strange problem since a couple of days.the bot plays one song and after that it wont anymore.
the  error,s it gives [Errno 3] No such process.
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 267, in                                                                                                                      _run_event
    yield from getattr(self, event)(_args, *_kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", lin                                                                                                                     e 607, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", li                                                                                                                     ne 342, in invoke
    yield from injected(_ctx.args, *_ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", li                                                                                                                     ne 46, in wrapped
    ret = yield from coro(_args, *_kwargs)
  File "/home/nick/discord/test/Red-DiscordBot/cogs/audio.py", line 79, in play
    self.music_player.stop()
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 12                                                                                                                     6, in stop
    self.process.kill()
  File "/usr/local/lib/python3.5/subprocess.py", line 1769, in kill
    self.send_signal(signal.SIGKILL)
  File "/usr/local/lib/python3.5/subprocess.py", line 1759, in send_signal
    os.kill(self.pid, sig)
ProcessLookupError: [Errno 3] No such process
[Errno 3] No such process

i did run on version 2 of the bot since it came out without problems its just since a couple of days.
i run on 
git version 2.7.0
CentOS Linux release 7.2.1511 
Python 2.7.5
ffmpeg version N-77891-g757248e

**Comment by irdumbs** [comment]
also getting repeating
[Errno 3] No such process
[Errno 3] No such process
...

This error preceded one of the "crashes". Not sure if related as I've gotten similar errors previous to this issue.
Application provided invalid, non monotonically increasing dts to muxer in stream 0: 2216 >= 2191

git version 2.5.4 (Apple Git-61)
OSX 10.11.3
Python 3.5.0
ffmpeg version 2.8.6 Copyright (c) 2000-2016 the FFmpeg developers built with Apple LLVM version 7.0.2 (clang-700.1.81)

**Comment by Twentysix26** [comment]
I can't seem to reproduce it, at least on Windows. There haven't been changes in the audio module for quite a while now, so I don't think that's the problem. From what it looks like ffmpeg is crashing on its own and discord.py errors out when it tries to kill the process.  Try updating to the latest ffmpeg build and see if anything changes?

**Comment by Heronickproductions** [comment]
I reinstalled python on linux now it seems to work again

**Comment by irdumbs** [comment]
I tried reinstalling python 3.5 on mac. Tried latest snapshot from https://ffmpeg.org and 3-4 other prebuilt versions of ffmpeg. Tried different versions of opus. 
None of these seemed to make a difference. 
[p]mix playlist followed by [p]next still always gives [Errno 3] No such process

**Comment by Twentysix26** [comment]
https://github.com/Twentysix26/Red-DiscordBot/commit/6f26f39d4632bd9bc9039b7d71d341fa84bc21c1

Should be fixed.
