### ISSUE TITLE
redbot discord disconnecting 

### ISSUE THREAD

**Issue by krz111** [Cog-Creators/Red-DiscordBot#886]
Official server: https://discord.gg/red
Make sure to keep your bot updated. Select the 'Update' option from the launcher.
Task exception was never retrieved
future: <Task finished coro=<VoiceClient.poll_voice_ws() done, defined at lib\discord\voice_client.py:269> exception=ConnectionClosed('WebSocket connection is closed: code = 1001, no reason.',)>
Traceback (most recent call last):
  File "lib\discord\gateway.py", line 676, in poll_event
    msg = yield from asyncio.wait_for(self.recv(), timeout=30.0, loop=self.loop)
  File "C:\Users\ichiy\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 400, in wait_for
    return fut.result()
  File "C:\Users\ichiy\AppData\Local\Programs\Python\Python35\lib\asyncio\futures.py", line 293, in result
    raise self._exception
  File "C:\Users\ichiy\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "lib\websockets\protocol.py", line 299, in recv
    raise ConnectionClosed(self.close_code, self.close_reason)
websockets.exceptions.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ichiy\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 239, in _step
    result = coro.send(None)
  File "lib\discord\voice_client.py", line 276, in poll_voice_ws
    yield from self.ws.poll_event()
  File "lib\discord\gateway.py", line 679, in poll_event
    raise ConnectionClosed(e) from e
discord.errors.ConnectionClosed: WebSocket connection is closed: code = 1001, no reason.

**Comment by tekulvw** [comment]
Please go to the support server if you still have questions.

**Comment by MOZGIII** [comment]
I caught a kernel bug on 4.13.0-17-generic (ubuntu) that casued this behavior on linux. Downgrading to 4.11.0-14-generic helped.
