### ISSUE TITLE
Can't open file "launcher.py" 

### ISSUE THREAD

**Issue by PreXs** [Cog-Creators/Red-DiscordBot#891]
Hello
I'm trying to install the RED bot on my mac. Everything works fine until i type "python3 launcher.py".
I get this error: " /usr/local/Cellar/python3/3.6.2/Frameworks/Python.framework/Versions/3.6/Resources/Python.app/Contents/MacOS/Python: can't open file 'launcher.py': [Errno 2] No such file or directory "

Thanks!

**Comment by Jan200101** [comment]
Please go into the Red-Discordbot directory

**Comment by PreXs** [comment]
Okay thanks! Got that working, but i have another problem now..
When i start RED, i get the following message:
task: <Task pending coro=<Audio.cache_scheduler() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/audio.py:1928> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e70978>()]>>
Task was destroyed but it is pending!
After that RED gets terminated.

**Comment by Twentysix26** [comment]
Post the entirety of the error please

**Comment by PreXs** [comment]
```
Starting Red...
Logging into Discord...
[09/08/2017 14:37] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 601, in _create_direct_connection
    local_addr=self._local_addr)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 803, in create_connection
    sock, protocol_factory, ssl, server_hostname)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 829, in _create_connection_transport
    yield from waiter
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 503, in data_received
    ssldata, appdata = self._sslpipe.feed_ssldata(data)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/sslproto.py", line 201, in feed_ssldata
    self._sslobj.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/ssl.py", line 683, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 304, in connect
    yield from self._create_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 578, in _create_connection
    transport, proto = yield from self._create_direct_connection(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 624, in _create_direct_connection
    (req.host, req.port, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)]

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/aiohttp/connector.py", line 314, in connect
    .format(key, exc.strerror)) from exc
aiohttp.errors.ClientOSError: [Errno 1] Cannot connect to host discordapp.com:443 ssl:True [Can not connect to discordapp.com:443 [[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:748)]]
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/audio.py:2100> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e70858>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/audio.py:1973> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e708b8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/audio.py:2104> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e70918>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_scheduler() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/audio.py:1928> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e70978>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /Applications/Discord Stuff/Red-DiscordBot/cogs/streams.py:614> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x108e709d8>()]>>
Red has been terminated. Exit code: 1
Press enter to continue...
logout
```

**Comment by Twentysix26** [comment]
Navigate to `Applications/Python 3.6/`, there should be a `Install Certificates.command`  
Double click it and try again.

**Comment by PreXs** [comment]
Thanks! It worked :)
