### ISSUE TITLE
ERROR red <module> 634: Fatal exception, attempting graceful logout

### ISSUE THREAD

**Issue by JeSTeRFLA** [Cog-Creators/Red-DiscordBot#932]
```Logging into Discord...
[17/08/2017 23:19] ERROR red <module> 634: Fatal exception, attempting graceful logout
Traceback (most recent call last):
  File "red.py", line 614, in <module>
    loop.run_until_complete(main(bot))
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "red.py", line 599, in main
    bot=not bot.settings.self_bot)
  File "lib/discord/client.py", line 416, in login
    yield from getattr(self, '_login_' + str(n))(*args, **kwargs)
  File "lib/discord/client.py", line 346, in _login_1
    data = yield from self.http.static_login(token, bot=is_bot)
  File "lib/discord/http.py", line 258, in static_login
    data = yield from self.request(Route('GET', '/users/@me'))
  File "lib/discord/http.py", line 137, in request
    r = yield from self.session.request(method, url, **kwargs)
  File "lib/aiohttp/client.py", line 555, in __iter__
    resp = yield from self._coro
  File "lib/aiohttp/client.py", line 198, in _request
    conn = yield from self._connector.connect(req)
  File "lib/async_timeout/__init__.py", line 46, in __exit__
    raise asyncio.TimeoutError from None
concurrent.futures._base.TimeoutError
Task was destroyed but it is pending!
task: <Task pending coro=<Streams.stream_checker() running at /root/Red-DiscordBot/cogs/streams.py:614> wait_for=<Future finished result=None>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.cache_manager() done, defined at /root/Red-DiscordBot/cogs/audio.py:1918> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fcfbeb9a8>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.queue_scheduler() running at /root/Red-DiscordBot/cogs/audio.py:2100> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fcfbebc48>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.disconnect_timer() running at /root/Red-DiscordBot/cogs/audio.py:1973> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fcfbeb918>()]>>
Task was destroyed but it is pending!
task: <Task pending coro=<Audio.reload_monitor() running at /root/Red-DiscordBot/cogs/audio.py:2104> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f5fcfbeb888>()]>>

SERVER Versions

root@xda:~/Red-DiscordBot# python -V
Python 2.7.13
root@xda:~/Red-DiscordBot# python3 -V
Python 3.5.3
root@xda:~/Red-DiscordBot# python3.6 -V
Python 3.6.0
root@xda:~/Red-DiscordBot# pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
root@xda:~/Red-DiscordBot# pip3 -V
pip 9.0.1 from /usr/local/lib/python3.6/site-packages (python 3.6)```

**Comment by Twentysix26** [comment]
This issue lacks details. What are you attempting to do? Does this happen every time? Randomly? After a certain action?

**Comment by JeSTeRFLA** [comment]
only happens when i run bot or run bot with auto start everything else works great install, update work it is only on bot run
no added modules yet not extra stuff only discord[voice] and i used the install script

**Comment by Kowlin** [comment]
Closing due to inactivity, unknown error source.
