### ISSUE TITLE
Error when using [p]playlist rapidly

### ISSUE THREAD

**Issue by NamedJohn** [Cog-Creators/Red-DiscordBot#96]
Last git pull: 1000 Pacific 3/17/2016
Severity: Low (bot still functions as expected and recovers after error)

Description: The bot gives an error in the terminal after using a command that plays a link, playlist, or local song at least twice in a short interval.

Error output:

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 267, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "red.py", line 63, in on_message
    await bot.process_commands(message)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/bot.py", line 607, in process_commands
    yield from command.invoke(ctx)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 343, in invoke
    yield from injected(*ctx.args, **ctx.kwargs)
  File "/usr/local/lib/python3.5/site-packages/discord/ext/commands/core.py", line 47, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "/home/pi/Red-DiscordBot/cogs/audio.py", line 199, in local
    if await self.check_voice(msg.author, ctx.message):
  File "/home/pi/Red-DiscordBot/cogs/audio.py", line 583, in check_voice
    await self.bot.join_voice_channel(author.voice_channel)
  File "/usr/local/lib/python3.5/site-packages/discord/client.py", line 2532, in join_voice_channel
    yield from asyncio.wait_for(self._voice_data_found.wait(), timeout=5.0, loop=self.loop)
  File "/usr/local/lib/python3.5/asyncio/tasks.py", line 390, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

**Comment by Twentysix26** [comment]
Same as your other issue.
