### ISSUE TITLE
Error after calling [p]stop

### ISSUE THREAD

**Issue by NamedJohn** [Cog-Creators/Red-DiscordBot#97]
Last git pull: 1000 Pacific 3/17/2016
Severity: Low (bot still functions as expected and recovers after error)

Description: Happens at random times after using [p]stop while playing audio. This has happened while playing a local playlist as well as a youtube playlist.

Error output:

```
Exception in thread Thread-17:
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.5/site-packages/discord/voice_client.py", line 87, in run
    data = self.buff.read(self.frame_size)
ValueError: read of closed file
```

**Comment by Twentysix26** [comment]
Thanks for the report. I'll see if I can handle the exception but it isn't anything of note
