### ISSUE TITLE
cogs.audio.ConnectTimeout error

### ISSUE THREAD

**Issue by RageBoy009** [Cog-Creators/Red-DiscordBot#986]
When i try to play local tracks or yt links im getting this error:

```
[17/09/2017 23:10] ERROR audio _join_voice_channel 702:
Traceback (most recent call last):
  File "C:\Red-DiscordBot\cogs\audio.py", line 700, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 410, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
[17/09/2017 23:10] ERROR red on_command_error 369: Exception in command 'local start'
Traceback (most recent call last):
  File "C:\Red-DiscordBot\cogs\audio.py", line 700, in _join_voice_channel
    timeout=5, loop=self.bot.loop)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 410, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\discord\ext\commands\core.py", line 50, in wrapped
    ret = yield from coro(*args, **kwargs)
  File "C:\Red-DiscordBot\cogs\audio.py", line 1364, in play_local
    await self._join_voice_channel(voice_channel)
  File "C:\Red-DiscordBot\cogs\audio.py", line 704, in _join_voice_channel
    raise ConnectTimeout("We timed out connecting to a voice channel,"
cogs.audio.ConnectTimeout: We timed out connecting to a voice channel, please try again in 10 minutes.
```

it worked that day before, now its broken. tried to find similar issue with no luck.
already reinstalled everything ( except windows)

plz help

**Comment by RageBoy009** [comment]
Looks like it was discords fault.

**Comment by RageBoy009** [comment]
And again not working. Same error. Is this rly Discord related?

**Comment by Kowlin** [comment]
Closing due to inactivity. For what we know this is caused on Discord's end and so far we don't know what to do about it.

**Comment by JaykeBird** [comment]
I've just started getting this error constantly. It's been about 3 weeks now, so I doubt it's been Discord's fault. I've tried updating the bot, updating/clearing/reinstalling all the requirements and lib folder and stuff, resetting the bot. Other bots seem totally fine being able to connect and play, but this one can't. I'm at a loss about what to do here.

**Comment by kennnyshiwa** [comment]
This is most definitely a discord issue, if you are running red v2 then it will never work with audio again due to discord changes, if its red v3 then join the support server and we can assist you further

**Comment by JaykeBird** [comment]
I can't tell which version I am using, as a different error was thrown when I tried to check. I'll try to do a clean install of the Red bot, and I'll report in the Discord server if I have questions/issues. Thank you :)

**Comment by Vexed01** [comment]
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\lib\asyncio\tasks.py", line 410, in wait_for

You are using V2 as your Python version is 3.5 and V3 doesn't run on 3.5.
To make audio work you need to use V3.

**Comment by Vexed01** [comment]
Wait that's a different person's traceback...
![facepalm](http://static.skaip.org/img/emoticons/180x180/f6fcff/facepalm.gif)
Just ask in Discord 😂
